### ISSUE TITLE
invalid options "--github-token="

### ISSUE THREAD

**Issue by foxbunny** [travis-ci/dpl#1002]
I have [configured](https://github.com/foxbunny/datetimejs/blob/master/.travis.yml) travis to publish docs to gh-pages. This worked on a feature branch, but then when I merged the feature branch I got this error:

    invalid options "--github-token="

Not sure if this is a dpl issue so my apologies if I'm in the wrong room.

**Comment by BanzaiMan** [comment]
It means your token was not decrypted successfully.

**Comment by foxbunny** [comment]
Hi, @BanzaiMan, and thanks for the explanation. Is it still a bug that it sometimes works and sometimes not?

**Comment by BanzaiMan** [comment]
It shouldn't behave that way. Could you point to the relevant build logs?

**Comment by foxbunny** [comment]
Actually, my bad. It always has this error. I just didn't realize that because the github page always gets published afterwards. Here's [build 8](https://travis-ci.org/foxbunny/datetimejs/builds/543708587), for instance, which is marked as failure, but I can see the result online regardless.

**Comment by BanzaiMan** [comment]
https://github.com/foxbunny/datetimejs/blob/50a3b89891cfcee9bc8132fd750f28e4cb23c23f/.travis.yml#L11 tells the deployment to use `$GITHUB_TOKEN`, but it is not defined in `.travis.yml` nor Settings, so it is blank.

**Comment by foxbunny** [comment]
By settings, you mean like this, or somewhere else?

![image](https://user-images.githubusercontent.com/65413/59202169-3319d200-8b9c-11e9-9b81-eb2f93dba3d1.png)

**Comment by BanzaiMan** [comment]
Yes, that's what I mean. Is this from the same repository? They should be announced in the build logs: https://travis-ci.org/BanzaiMan/travis_production_test/builds/541253375#L425-L427 But I don't see the evidence in your logs.

**Comment by foxbunny** [comment]
Yeah, from the same repo (as far as I can tell).

![image](https://user-images.githubusercontent.com/65413/59202901-c43d7880-8b9d-11e9-8219-be847886e64a.png)

I think I even saw it at one point in the logs, it said something like `GITHUB_TOKEN=[secret]` but I can't locate it now.

**Comment by BanzaiMan** [comment]
Ah, I see the problem now. Your build is now running on .com: https://travis-ci.com/foxbunny/datetimejs/builds/114933480#L426 but you are seeing the deployment failures in .org https://travis-ci.org/foxbunny/datetimejs/builds/543708587.

**Comment by foxbunny** [comment]
Would you say I'm crazy if I told you I find that very confusing? :D

**Comment by BanzaiMan** [comment]
"Crazy" is not the word I would use here, but I agree with you that it is confusing. We are working on combining the .org and .com data, so that we won't have this issue. We are almost there.

In the mean time, I think we are all set in this instance, so I'll close this.

Thanks.
