### ISSUE TITLE
DigitalOcean support

### ISSUE THREAD

**Issue by EmielSchmeink** [travis-ci/dpl#1016]
Since the other issue was closed years ago when there was no api, it may be interesting if there could be any DigitalOcean support. The API DigitalOcean uses is pretty extensive: https://developers.digitalocean.com/documentation/v2/

**Comment by jdickey** [comment]
Noting that that’s the v2 API; v1 was in production for quite some time (up until [9 November 2015](https://developers.digitalocean.com/documentation/changelog/api-v1/)) before being replaced by the current [API v2](https://developers.digitalocean.com/documentation/v2/)), and considering that DigitalOcean is a widely-used platform, especially for small teams and startups, it boggles my mind that *nobody* has stepped up yet. When I get some free time, I’ll start poking around.

Someone might be confused that the old-style traditional (v1) API interface Gem was [motdotla/digitalocean](https://github.com/motdotla/digitalocean); this has been superseded by [digitalocean/droplet_kit](https://github.com/digitalocean/droplet_kit), which, as the owner name suggests, is “the official DigitalOcean API client for Ruby” and supports DO API v2.

**Comment by glhrmv** [comment]
Voicing more support for this. This would be highly appreciated by many, I'm sure.

**Comment by svenfuchs** [comment]
if anyone wants to take a stab at it, a PR would be very appreciated :)

**Comment by hoektoe** [comment]
DigitalOcean support would be much appreciated

**Comment by EmielSchmeink** [comment]
> Thanks for contributing to this issue. As it has been 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again! You can read more here: https://blog.travis-ci.com/2018-03-09-closing-old-issues

This is definitely not solved.

**Comment by svenfuchs** [comment]
I suppose we would be happy to accept a PR for this, even if just a draft without tests, in case Ruby skills are an issue.

I am going to close this in the meantime. Feel free to re-open when there is a PR or if needed otherwise.
