### ISSUE TITLE
Unexpected HTTP response code 505 returned from Bintray while checking if package exists.

### ISSUE THREAD

**Issue by medengineer** [travis-ci/dpl#1020]
Re-opening an issue that was never resolved (closed by bots): #8872 #692.

Looks like both previous posters never resolved the issue and moved onto different hosting platforms. Details are the same as in their posts.

**Comment by svenfuchs** [comment]
@medengineer sorry about the issue.

We have a major rewrite in the works, which includes an integration test that [successfully pushes to Bintray](https://travis-ci.org/travis-ci/dpl/builds/561021313#L541). I vaguely remember seeing the issue (or a similar one?) when working on this.

You should be able to opt into the dpl v2 by specifying this in your `.travis.yml` file:

```
deploy:
  - provider: bintray
    edge:
      branch: dpl-2
    [...]
```

Would you be able to confirm if it works for you with the new version?

**Comment by medengineer** [comment]
@svenfuchs 

I updated the travis.yml to use dpl-2, now getting a Ruby LoadError on deploy: https://travis-ci.org/medengineer/ni-daq/builds/561126600

**Comment by svenfuchs** [comment]
@medengineer ah, you're running this on windows. thank you!

hmmm, ok, i think we can install bundler conditionally. in the meantime, you could try adding a `before_deploy` step like so:

```
before_deploy: gem install bundler
```

to see if that fixes it.

**Comment by medengineer** [comment]
@svenfuchs That fixes the bundler issue. Now complains about missing MSYS2 and suggests to run 'ridk install'. I tried:

```
before_deploy:
    - gem install bundler
    - ridk install
```
and this gives 'ridk command not found'. I would expect 'ridk.cmd' to be in the same directory as 'gem.cmd' as I see on my local Win machine...

https://travis-ci.org/medengineer/ni-daq/builds/561150467

**Comment by medengineer** [comment]
@svenfuchs Any additional thoughts here? Otherwise the plan now is to migrate to AppVeyor for Windows builds until things become more stable on TravisCI + Windows. Appreciate your help.
