### ISSUE TITLE
file.app is not a regular file. Skipping.

### ISSUE THREAD

**Issue by Bob-Thomas** [travis-ci/dpl#1059]
I am trying to use travis to upload a osx app bundle but it keeps skipping it saying it is not a regular file.

**Comment by BanzaiMan** [comment]
In macOS, the "app" is just a special kind of directory, one which Finder (and the OS) works tricks to launch processes.

```sh-session
$ ls -l /Applications/Calendar.app
total 0
drwxr-xr-x  9 root  wheel  288 Jul 27 12:42 Contents
```

If you need to move things around, you'll have to create an archive (e.g., app.tar.gz or app.zip) and handle that.

**Comment by Bob-Thomas** [comment]
Ah that could be it. Thanks for the quick response
