### ISSUE TITLE
New deploy key release still tries to auth with GitHub

### ISSUE THREAD

**Issue by domenic** [travis-ci/dpl#1081]
See https://travis-ci.com/w3c/payment-method-manifest/builds/124287169, a result of https://github.com/w3c/payment-method-manifest/commit/0f923b60cf51bd9726e09e131b1fe2614bbd509b.

I was attempting to test https://github.com/travis-ci/dpl/pull/1031, but there is a failure of

```
GET https://api.github.com/user: 401 - Requires authentication // See: https://developer.github.com/v3/users/#get-the-authenticated-user (Octokit::Unauthorized)
```

which implies to me that it's still trying to do something with the GitHub token (which I have removed).

/cc @svenfuchs @webknjaz as the main people on that pull request.

**Comment by svenfuchs** [comment]
@domenic Thanks a lot for the report!

You're right. It seems the option `committer_from_gh` that your build [uses](https://github.com/w3c/payment-method-manifest/blob/0f923b60cf51bd9726e09e131b1fe2614bbd509b/.travis.yml#L14) still makes the provider talk to GitHub's API, which needs the token:

[`committer_name`](https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/pages.rb#L177) calls [`user`](https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/pages.rb#L221) ... which uses the octokit client.

I think the only viable solution to this is to tell the user, and make the option `committer_from_gh` require the option `github_token`. 

What do you think?

**Comment by domenic** [comment]
Hmm. I guess that would work fine, because I can just use a new GitHub token with no permissions, instead of the current approach which requires using a token with write permissions on all of my repositories.

However, I wonder if it'd be possible to just figure out the committer based on the local repository data? That is, at this point Travis CI has already checked out my repository. Can't it look at the metadata for commit https://github.com/w3c/payment-method-manifest/commit/0f923b60cf51bd9726e09e131b1fe2614bbd509b and know that it was authored/committed by `Domenic Denicola <d@domenic.me>`, and use that, without having to make a GitHub API request?

I can understand if that's kind of a separate feature request, different from the `committer_from_gh` feature. But something like that would be the ideal way, IMO, to preserve authorship information without needing GitHub API calls.

**Comment by svenfuchs** [comment]
@domenic You're totally right, not sure why i haven't thought of that :)

I'll look into changing that. Thank you!

**Comment by svenfuchs** [comment]
@domenic see https://github.com/travis-ci/dpl/pull/1082 ... untested besides unit tests though.

if you would like to give this a try you should be able to use that branch using:

```yaml
deploy:
  provider: pages
  edge:
    branch: sf-fix-pages-committer
```

**Comment by svenfuchs** [comment]
since we're now discussing things on https://github.com/travis-ci/dpl/pull/1082 i'm going to close this one here. feel free to reopen if needed.
