### ISSUE TITLE
Github Pages: deployment script chokes on ' inside value for project_name

### ISSUE THREAD

**Issue by andreasabel** [travis-ci/dpl#1085]
See https://travis-ci.org/andreasabel/agda-scope/builds/575573744 : I had deployment to `gh-pages` crash with
```
sh: 1: Syntax error: Unterminated quoted string
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
By accident I discovered that an apostrophe in field `project_name` was the culprit, like in
```
  project_name: "Andreas' cool stuff"
```
Er, string sanitization 101!?  
Such problems could also be security holes, allowing code injection...

Would be nice if the script was more robust.

**Comment by svenfuchs** [comment]
Thanks for the report, @andreasabel.

As far as I can tell this is an issue in dpl v1 (currently released/used on Travis CI), but will be addressed in v2.

I am going to close this here. Please feel free to reopen if needed.
