### ISSUE TITLE
GitHub Pages: misleading error message: invalid option "--github_token="

### ISSUE THREAD

**Issue by andreasabel** [travis-ci/dpl#1086]
The `pages` deployment script threw me this error:
```
invalid option "--github_token="
failed to deploy
```
Turned out the option is __not__ invalid!  
Instead I had in travis-ci the GITHUB_TOKEN restricted to branch `gh-pages` (seemed intuitively the right choice to me).  Allowing access to _all branches_ fixed the problem.

The error `invalid option` is very misleading.  It lead me to try to fix the problem by switching to option `api_key` instead, without success, see https://travis-ci.org/andreasabel/agda-scope/builds/575572048 .

A suggestion: if there is no better error information available, at least word the error about problems with the GITHUB_TOKEN as
```
Somethings went wrong with the authentification on github
```
rather than claiming an invalid option was supplied.

Related: #1002

**Comment by svenfuchs** [comment]
Thanks for the report, @andreasabel.

As far as I can tell this is an issue in dpl v1 (currently released/used on Travis CI), but will be addressed in v2.

I am going to close this here. Please feel free to reopen if needed.
