### ISSUE TITLE
GitHub pages deploy should not be considered failed if no changes are deployed

### ISSUE THREAD

**Issue by domenic** [travis-ci/dpl#1095]
Consider the build at https://travis-ci.org/WICG/kv-storage/builds/581318941. It ends with

```
Cloning the branch gh-pages from the remote repo
Copying /home/travis/build/WICG/kv-storage/out contents to /tmp/d20190905-5413-1tfp4w3
$ rsync -rl --exclude .git --delete "/home/travis/build/WICG/kv-storage/out/" .
Preparing to deploy gh-pages branch to gh-pages
$ git add -A .
$ git commit -qm "Deploy WICG/kv-storage to github.com/WICG/kv-storage.git:gh-pages"
On branch gh-pages
Your branch is up to date with 'origin/gh-pages'.

nothing to commit, working tree clean


Failed
failed to deploy
```

I think this should count as a success, not a failure, right?

**Comment by svenfuchs** [comment]
@domenic sorry, i've missed this here. yes, i think you're right, this shouldn't fail.

i've added https://github.com/travis-ci/dpl/pull/1097/files to address this.

**Comment by svenfuchs** [comment]
merged https://github.com/travis-ci/dpl/pull/1097 ... please note that this is not released as a gem, yet. if you want to try it out you'd need to use

```yaml
deploy:
- provider: pages
  edge:
    branch: master
```

i'm going to close this here, please reopen if needed.
````

**Comment by andrewdavidmackenzie** [comment]
This seems to still not be the default behaviour?
- is it planned to be rolled out as the default behaviour
