### ISSUE TITLE
github pages does not seem to rsync all files?

### ISSUE THREAD

**Issue by njt1982** [travis-ci/dpl#1120]
This is possibly similar to #1115 ; I'm not entirely sure this is fixed? Although I could also be doing something stupid ;) 

In this build, I have added an `ls -l` to the "dist" folder:
https://travis-ci.com/DrupalModuleSearch/DrupalModuleSearch.github.io/builds/131660814

I get this:
```
The command "yarn run build" exited with 0.
0.01s$ ls -l dist
total 108
-rw-rw-r-- 1 travis travis 10617 Oct 12 21:26 android-chrome-192x192.png
-rw-rw-r-- 1 travis travis 34799 Oct 12 21:26 android-chrome-512x512.png
-rw-rw-r-- 1 travis travis  9599 Oct 12 21:26 apple-touch-icon.png
drwxrwxr-x 2 travis travis  4096 Oct 12 21:26 css
-rw-rw-r-- 1 travis travis   620 Oct 12 21:26 favicon-16x16.png
-rw-rw-r-- 1 travis travis  1236 Oct 12 21:26 favicon-32x32.png
-rw-rw-r-- 1 travis travis 15406 Oct 12 21:26 favicon.ico
drwxrwxr-x 2 travis travis  4096 Oct 12 21:26 fonts
drwxrwxr-x 2 travis travis  4096 Oct 12 21:26 img
-rw-rw-r-- 1 travis travis  1050 Oct 12 21:26 index.html
drwxrwxr-x 2 travis travis  4096 Oct 12 21:26 js
-rw-rw-r-- 1 travis travis   263 Oct 12 21:26 site.webmanifest
The command "ls -l dist" exited with 0.
```

As you can see, there are several favicons.

The last commit at this time was:
https://github.com/DrupalModuleSearch/DrupalModuleSearch.github.io/tree/bcfb72d736cf587e598ffe790c272bf9e97eafa1

As you can see, on the master branch there are no favicons. (Pages build from "master", the main site/app is in "src").

The build later goes on to say:
```
Cloning the branch master from the remote repo
Copying /home/travis/build/DrupalModuleSearch/DrupalModuleSearch.github.io/dist contents to /tmp/d20191012-7757-18w57sg
$ rsync -rl --exclude .git --delete "/home/travis/build/DrupalModuleSearch/DrupalModuleSearch.github.io/dist/" .
There are no changes to commit, stopping.
```

I've checked the raw logs and it appears to be using the 2.0.0.alpha.10:
`Successfully installed dpl-2.0.0.alpha.10`

I'm not sure if I'm doing something wrong here or not? It seems strange that the Vue Build into Dist has put the files there, but the later rsync step does not see them? Why does rsync not copy over the favicons?

**Comment by njt1982** [comment]
So... randomly... this seemed to work last night?!
https://travis-ci.com/DrupalModuleSearch/DrupalModuleSearch.github.io/builds/131664798

The rsync magically found something this time?

```
Run deployment
Cloning the branch master from the remote repo
Copying /home/travis/build/DrupalModuleSearch/DrupalModuleSearch.github.io/dist contents to /tmp/d20191012-7809-4bde5w
$ rsync -rl --exclude .git --delete "/home/travis/build/DrupalModuleSearch/DrupalModuleSearch.github.io/dist/" .
Preparing to deploy master branch to gh-pages
$ git add -A .
$ git commit --allow-empty -qm "Deploy DrupalModuleSearch/DrupalModuleSearch.github.io to github.com/DrupalModuleSearch/DrupalModuleSearch.github.io.git:master"
$ git show --stat-count=10 HEAD
commit 71dc3cee117c0145ce28407ab2510f473f4bf3ad (HEAD -> master)
Author: Nicholas Thompson (via Travis CI) <nick@fullfatthings.com>
Date:   Sat Oct 12 22:21:25 2019 +0000
    Deploy DrupalModuleSearch/DrupalModuleSearch.github.io to github.com/DrupalModuleSearch/DrupalModuleSearch.github.io.git:master
 android-chrome-192x192.png                      | Bin 0 -> 10617 bytes
 android-chrome-512x512.png                      | Bin 0 -> 34799 bytes
 apple-touch-icon.png                            | Bin 0 -> 9599 bytes
 favicon-16x16.png                               | Bin 0 -> 620 bytes
 favicon-32x32.png                               | Bin 0 -> 1236 bytes
 favicon.ico                                     | Bin 0 -> 15406 bytes
 index.html                                      |   2 +-
 js/{app.13292497.js => app.7e0c2ba9.js}         |   2 +-
 js/{app.13292497.js.map => app.7e0c2ba9.js.map} |   2 +-
 site.webmanifest                                |   1 +
 10 files changed, 4 insertions(+), 3 deletions(-)
Pushing to github.com/DrupalModuleSearch/DrupalModuleSearch.github.io.git
$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
Done. Your build exited with 0.
```

Same DPL Gem too?
`Successfully installed dpl-2.0.0.alpha.10`

**Comment by svenfuchs** [comment]
@njt1982 thanks a lot for the report!

i've had a look at this, and i believe what happened here is that it didn't consider the new `png` files when checking if the working dir is dirty https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/pages/git.rb#L99, and thus just aborted the deployment ... `git diff` returns nothing for new files that aren't added to the index https://github.com/travis-ci/dpl/blob/6386fbd3f4f4d5274417c340c6febba3a0488b94/lib/dpl/ctx/bash.rb#L415

i have just pushed a change that should fix this https://github.com/travis-ci/dpl/commit/0b29048625d464625f81bb0b3eb5b32d67c2399f

**Comment by njt1982** [comment]
Yeah, a status instead of diff makes much more sense.

Awesome! This seems to be working now :) I'll reopen this (or open a new ticket and refer to this) if I have any further issues.

Thanks @svenfuchs
