### ISSUE TITLE
Heroku API provider doesn't work on Windows

### ISSUE THREAD

**Issue by NoNameProvided** [travis-ci/dpl#1132]
When running the following on Windows:
```bash
dpl heroku --api_key xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx --app fesfse-test-staging-1
```

It results in an error from `tar`:

```
tar (child): Cannot connect to C: resolve failed
tar: Child returned status 128
tar: Error is not recoverable: exiting now
```

This error is raised because tar handles the path as a remote path because of the `:` sign. This behaviour can be prevented via passing the `--force-local` flag. [Source](https://stackoverflow.com/a/37996249/2019689)

I wonder if this flag can be added to support deployment on windows or not.

**Comment by BanzaiMan** [comment]
That looks promising. Could you open a PR with this idea, and test it? Thank you!
