### ISSUE TITLE
Deploy failing when `skip_cleanup: true` removed (using `cleanup: false` implicitly or explicitly)

### ISSUE THREAD

**Issue by myii** [travis-ci/dpl#1138]
Opted in to the new beta feature after finding out about it:

* https://docs.travis-ci.com/user/build-config-validation

All changes working well but not being able to remove `skip_cleanup: true` and rely on `cleanup: false` implicitly or explicitly.

* https://travis-ci.org/myii/ssf-formula/jobs/612834738#L238
  - Not working when `skip_cleanup: true` has been removed
* https://travis-ci.org/myii/ssf-formula/jobs/612840446#L238
  - Working when `skip_cleanup: true` has been reinstated

**Comment by myii** [comment]
Also tested on travis-ci.com with the same problem:

* https://travis-ci.com/myii/ssf-formula/jobs/257266822#L238

**Comment by svenfuchs** [comment]
@myii sorry about the confusion here. the Build Config Validation feature normalizes your config in such a way that it is assumed that you are using `dpl v2`, too (https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release). we are soon going to make `v2` the default version.

in the meantime, could you please add this to to your config:

```
deploy:
  provider: script
  edge: true
```

**Comment by myii** [comment]
@svenfuchs OK, thanks for the info, I'll do that.
