### ISSUE TITLE
Missing arguments (given: 0, required: 1)

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/dpl#1152]
Reported here: https://github.com/travis-ci/dpl/issues/1105#issuecomment-574214664

> I'm using Linux. The deployment worked fine before with `2.0.0.alpha.11`, but now with `2.0.0.alpha.12` it fails with this error message:
> ```
> Missing arguments (given: 0, required: 1)
> failed to deploy
> ```
> I don't have the debug mode ready for this project so far, so that's all I got atm... I'm using this config
> 
> ```
> provider: pages
> keep_history: true
> deploy_key: github_deploy_key
> cleanup: false
> edge: true
> repo: ...
> target_branch: master
> local_dir: "...."
> verbose: true
> on:
>   branch: master
> ```

**Comment by svenfuchs** [comment]
@spflueger do you have a link to an example build log for this? is this happening on Travis CI or elsewhere?

**Comment by svenfuchs** [comment]
@spflueger i have been able to reproduce the issue, and released a new version which should fix it.

i am going to close the issue here for now. please feel free to reopen it if the problem still persists.

**Comment by spflueger** [comment]
> @spflueger i have been able to reproduce the issue, and released a new version which should fix it.

Ok thanks a lot @svenfuchs. I'm testing it right now!

**Comment by spflueger** [comment]
Works! Thanks again!

**Comment by svenfuchs** [comment]
Thanks for testing this, and for the feedback, @spflueger
