### ISSUE TITLE
AWS S3 Cache control document example not working

### ISSUE THREAD

**Issue by ivanbreet** [travis-ci/dpl#1159]
Hi,

We tried the `dpl v2` cache-control example outlined in the [documentation](https://docs.travis-ci.com/user/deployment-v2/providers/s3/#http-cache-control):
```
expires: '$(date -u +"%Y-%m-%d %H:%M:%S -0000" --date "next Year"): *.{jpg,gif,png,webp,css,js,ico}'
```

but the builds are failing with:
```
$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl --pre
Successfully installed regstry-1.0.15
Successfully installed cl-1.2.1
Successfully installed dpl-2.0.0.pre.beta.1
3 gems installed
date: invalid option -- '0'
Try 'date --help' for more information.
Invalid format: expires (format: /^"?\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} .+"?.*$/)
failed to deploy
```

**Comment by BanzaiMan** [comment]
On Linux, with the system clock set to UTC, you get:

```sh-session
travis@1f47151d5c5d:~$ date -u +"%Y-%m-%d %H:%M:%S -0000" --date "next Year"
2021-02-04 18:26:29 -0000
```

The `-0000` bit is probably getting passed to `dpl` as a flag, so you get the error message. You'll have to fix that.

Also note that the `--date` is not a universally accepted flag, so it would fail on macOS, if you try.

**Comment by BanzaiMan** [comment]
Oh, I realize that this is verbatim the example! We'll take a look. Sorry about the confusion there.

**Comment by BanzaiMan** [comment]
Could you try:

```yaml
expires: "$(date -u +'%Y-%m-%d %H:%M:%S -0000' --date 'next Year'): *.{jpg,gif,png,webp,css,js,ico}"
```
Notice the switch of quotation marks; double quotes on the outside, and single quotes inside `$()`.

Thanks.
