### ISSUE TITLE
Leaks of secrets

### ISSUE THREAD

**Issue by falsandtru** [travis-ci/dpl#1167]
***Today, Travis leaks secrets!***

```
Unknown command: npm --api_token=2d0a8d99-...
```

https://travis-ci.org/falsandtru/spica/jobs/651662343#L393

Looks like this is caused by dpl.

**Comment by svenfuchs** [comment]
wow, it seems there's been a mistake in coordinating dpl v2 releases with one of it's dependencies.

i have rolled this back, and just tested it, seems fixed.

are you able to double check that it now recognizes the command?

**Comment by falsandtru** [comment]
I'm not using dpl directly. Can I check it on https://travis-ci.org/?

**Comment by svenfuchs** [comment]
@falsandtru yes, you can. you're using dpl under the hood when you deploy on Travis CI, and you've opted into v2 using `edge: true`.

thank you!

**Comment by falsandtru** [comment]
Confirmed. Thanks for you extremely quick response!

**Comment by svenfuchs** [comment]
awesome, thanks a lot for the report and for double checking!
