### ISSUE TITLE
dplv2 github releases provider doesn't booleanize bool flags

### ISSUE THREAD

**Issue by iartarisi** [travis-ci/dpl#1177]
Trying out the dplv2 provider in travis, we have an issue if we try to set the `prerelease` value from an envvar e.g.:

```
...
  before_deploy:
    - source ./scripts/travis_release.sh
  deploy:
  - provider: releases
    edge: true
    prerelease: ${PRE_RELEASE}
```

In this case, travis complains, in the Build config pane:

`jobs.include.deploy.prerelease: unexpected str, expected bool (${PRE_RELEASE}) `

![image](https://user-images.githubusercontent.com/35473/75978386-457c2e80-5ed6-11ea-8a32-a97288d48151.png)

The envvar is set when running the `scripts/travis_release.sh` and when dpl runs, it doesn't see it as a boolean, it still sees it as a string, so we get this log error:
```
/home/travis/.rvm/gems/ruby-2.4.5/gems/cl-1.2.4/lib/cl/parser.rb:21:in `initialize': needless argument: --prerelease=true (OptionParser::NeedlessArgument)
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/cl-1.2.4/lib/cl/cmd.rb:40:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/cl-1.2.4/lib/cl/cmd.rb:40:in `parse'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/cl-1.2.4/lib/cl/cmd.rb:61:in `initialize'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.pre.beta.1/lib/dpl/provider.rb:186:in `initialize'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/cl-1.2.4/lib/cl/runner/default.rb:32:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/cl-1.2.4/lib/cl/runner/default.rb:32:in `cmd'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/cl-1.2.4/lib/cl/runner/default.rb:26:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/cl-1.2.4/lib/cl.rb:34:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.pre.beta.1/lib/dpl/cli.rb:11:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.pre.beta.1/bin/dpl:9:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'
```

This seems to be a new bug (or regression) introduced with the refactoring of `releases.rb`, in dplv1, I can see that it tries to *booleanize* strings: 
https://github.com/travis-ci/dpl/blob/v1.10.15/lib/dpl/provider/releases.rb#L170-L183
But that code is missing from `master`.

**Comment by BanzaiMan** [comment]
Hello, there!

Sorry for the troubles, but thanks for testing v2 and reporting this issue.

Personally, I am inclined to think that the v1 behavior of allowing "truthy" value to pass through is the wrong behavior (it was implemented this way to prevent existing code to not break; if we are to introduce the breaking behavior, v2 is a good time to do so). https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository clearly indicates that this value should be a boolean. What is `${PRE_RELEASE}` set to, why do you want to delay the decision to the run time, and how is the script determining whether or not to be a pre-release?

**Comment by iartarisi** [comment]
Hi @BanzaiMan thanks for the quick reply. 

I've had a look at a few of our repos and mostly the logic would be `prerelease: branch != master`, however this doesn't seem to work. Using that logic, I get a configuration error like this:

![image](https://user-images.githubusercontent.com/35473/76331011-74374200-62e6-11ea-8f92-1f99a9c7dbb4.png)

What would you suggest to do in that case?
