### ISSUE TITLE
bad credentials with dplv2

### ISSUE THREAD

**Issue by neelgala** [travis-ci/dpl#1183]
I am using github releases as the provider

My travis-ci file: [here](https://github.com/riscv/riscv-isa-manual/blob/master/.travis.yml)

I get the following error:
```
git stash pop
No stash entries found.
GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
failed to deploy
```
Full log: [here](https://travis-ci.org/github/riscv/riscv-isa-manual/builds/667246096#L10222)

This was working until last month with dpl-v1.10.15 [passed log](https://travis-ci.org/github/riscv/riscv-isa-manual/builds/656531455). I haven't changed the api_key or anything else but it suddenly started failing.

I thought probably shifting to dpl-v2 would fix it.. but it doesn't.

any help on this would be appreciated

**Comment by neelgala** [comment]
is it possible that the alias "api_key" for token doesn't work?

**Comment by svenfuchs** [comment]
the alias works (see here: ), but you'll have to have the feature "Build Config Validation" enabled. i see it is currently disabled for the repo `riscv/riscv-isa-manual`.

we recommend enabling this at this point. is there any reason for you to keep it disabled?

**Comment by neelgala** [comment]
It was enabled when the builds failed. There was different thread which suggested switching it off as a solution. I have turned it off and restarted the build: https://travis-ci.org/github/riscv/riscv-isa-manual

**Comment by svenfuchs** [comment]
ah, i see. sorry, should have read your config closer.

you are using an invalid format on the `api_key`:

```
  api_key:
    secure: $github_access_token
```

this should just be:

```
  api_key: $github_access_token
```

the string `$github_access_token` is not encrypted.

**Comment by neelgala** [comment]
That worked thanks a lot !
