### ISSUE TITLE
CodeDeploy failure during `wait_until_deployed` does not cause `deploy` to fail

### ISSUE THREAD

**Issue by frenata** [travis-ci/dpl#1186]
When using the `CodeDeploy` provider and the `wait_until_deployed` option, the deploy does not fail when the returned status is `Failed`. This can happen when working with a script that times out, returning the AWS `ScriptTimedOut` error code, but probably also for a variety of other reasons.

This is unexpected behavior: when CodeDeploy reports a failure, the corresponding dpl job running that deploy should also in general fail.

The function that does not behave as expected follows:

https://github.com/travis-ci/dpl/blob/793b282ec332b39c42107f79769a6a2847267052/lib/dpl/providers/codedeploy.rb#L84-L88

I believe that a reasonable fix would be to adjust the `wait_until_deployed` function to behave more like its `OpsWorks` counterpart by calling `error` rather than `info` when the returned status is not a successful one:

https://github.com/travis-ci/dpl/blob/793b282ec332b39c42107f79769a6a2847267052/lib/dpl/providers/opsworks.rb#L71-L77

Edit: To be clear, I'm seeing this behavior with `v2`.

**Comment by frenata** [comment]
I'd be happy to prepare a patch assuming the maintainers agree this is an issue that should be fixed.

**Comment by BanzaiMan** [comment]
That sounds reasonable. We welcome your PR!
