### ISSUE TITLE
Dpl GitHub Action

### ISSUE THREAD

**Issue by TiagoGouvea** [travis-ci/dpl#1195]
Hello!

I've just published [Dpl Github Action ](https://github.com/TiagoGouvea/github-dpl-action), and want to invite you to check it. 😁

It's a very simple implementation, and I just added heroku as provider, because is the one I needed to deploy my project like used to do on GitLab.

I will be grateful to receive your feedback.

**Comment by TiagoGouvea** [comment]
Ok. Seems that no one got excited about it. No problem.

A question, I did it with dpl v1. Would be more relevant if I use v2 on action? Will be more useful for the community?

**Comment by BanzaiMan** [comment]
Hello, there.

Sorry for the late response. Yes, indeed, using v2 would be more relevant going forward.

**Comment by TiagoGouvea** [comment]
Thanks @BanzaiMan. I will focus on new versions, maybe. Thanks!
