### ISSUE TITLE
skip_cleanup key is deprecated, but docs don't list alternatives

### ISSUE THREAD

**Issue by arturtamborski** [travis-ci/dpl#1200]
Example job: https://travis-ci.com/github/CodeForPoznan/codeforpoznan.pl_v3/jobs/353019186/config#rccb_codeforpoznan.pl_v3:.travis.yml@6020e09bddab2413.25
Go to `view config` -> `build config validation` -> notice message `deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)`

The `cleanup` option is not described in docs? at least I couldn't find it, whereas `skip_cleanup` is documented all over the place (https://docs.travis-ci.com/user/deployment).

How to use `cleanup` option?

**Comment by BanzaiMan** [comment]
You are looking at the v1 doc. In the top "notice" box, you see the link to the v2 link, which explains the `cleanup` option.
