### ISSUE TITLE
Firebase deployment fails due to old firebase-tools version

### ISSUE THREAD

**Issue by rzueger** [travis-ci/dpl#1212]
I'm using the firebase provider to deploy my projects and one month ago all deployments started to fail with the following log output:

```
[...]
functions: ensuring necessary APIs are enabled...
Error: HTTP Error: 404, Method not found.
Firebase deployment failed
```

I was able to reproduce the error on my local machine using the old firebase-tools version 6.12 that is used in the deployment provider.

Then I forked your project and installed the current firebase-tools version in the firebase provider and now my deployments are succeeding again.

Is there a reason that `firebase-tools@^6.3` is used in that provider? Can this be changed so that always the latest version of firebase-tools is installed? Or would you prefer a new configuration option to override the firebase-tools version and use the latest version as the default?

I'd be happy to contribute a pull request - just tell me your preferred option.

**Comment by 5d-jh** [comment]
This issue should be reopened since the problem still exists.
