### ISSUE TITLE
Private repositories cancelling jobs at 50m instead of 120m 

### ISSUE THREAD

**Issue by GLJeffery** [travis-ci/dpl#1223]
macOS jobs for a private repository are now auto terminating for me at 50m instead of the 120m it was last week. Nothing has changed in configuration.

Is anyone experiencing this? Was this part of the new billing credits change?

**Comment by mustafa-travisci** [comment]
Hey, @GLJeffery, please reach us out from support@travis-ci.com with the repository name that you are seeing this issue. Thanks.
