### ISSUE TITLE
Failed to install dpl dependencies: get-pip.py failed

### ISSUE THREAD

**Issue by ifduyue** [travis-ci/dpl#1235]
> Installing deploy dependencies
> 
> Successfully installed dpl-pypi-1.10.16
> 
> 1 gem installed
> 
> 2021-03-04 14:08:40 URL:https://bootstrap.pypa.io/get-pip.py [1927626/1927626] -> "-" [1]
> 
> ERROR: This script does not work on Python 2.7 The minimum supported Python version is 3.6. Please use https://bootstrap.pypa.io/2.7/get-pip.py in2021-03-04 14:08:40 URL:https://bootstrap.pypa.io/get-pip.py [1927626/1927626] -> "-" [1]stead.
> 
> Couldn't install pip, setuptools, twine or wheel.
> 
> failed to deploy

os: osx
osx_image: xcode9.4
provider: pypi

**Comment by ifduyue** [comment]
Fixed with
```yaml
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      python3 -m venv ~/venv;
      source ~/venv/bin/activate;
    fi
```

**Comment by zhaoqin-github** [comment]
> ```yaml
> ~/venv/bin/activate
> ```

@ifduyue Does this workaround let dpl to execute upon Python 3, and it will still upload the artifacts built in Python 2.7 environment to Pypi?

**Comment by ifduyue** [comment]
> Does this workaround let dpl to execute upon Python 3, and it will still upload the artifacts built in Python 2.7 environment to Pypi?

Yes, it does.
