### ISSUE TITLE
Unit tests do not run locally

### ISSUE THREAD

**Issue by modohash** [travis-ci/dpl#1292]
When trying to run the unit tests for the project locally, no matter how many versions I go back, they always fail with the error:

`An error occurred while loading spec_helper.
Failure/Error: require 'webmock/rspec'

NameError:
  uninitialized constant CookieJar::CookieValidation::PATTERN::IPV4ADDR
 /usr/local/bundle/gems/cookiejar-0.3.4/lib/cookiejar/cookie_validation.rb:32:in `<module:PATTERN>'
 /usr/local/bundle/gems/cookiejar-0.3.4/lib/cookiejar/cookie_validation.rb:27:in `<module:CookieValidation>'
 /usr/local/bundle/gems/cookiejar-0.3.4/lib/cookiejar/cookie_validation.rb:25:in `<module:CookieJar>'
 /usr/local/bundle/gems/cookiejar-0.3.4/lib/cookiejar/cookie_validation.rb:5:in `<top (required)>'
 /usr/local/bundle/gems/cookiejar-0.3.4/lib/cookiejar/cookie.rb:3:in `<top (required)>'
 /usr/local/bundle/gems/cookiejar-0.3.4/lib/cookiejar.rb:1:in `<top (required)>'
 /usr/local/bundle/gems/em-http-request-1.1.7/lib/em-http/client.rb:1:in `<top (required)>'
 /usr/local/bundle/gems/em-http-request-1.1.7/lib/em-http.rb:17:in `<top (required)>'
 /usr/local/bundle/gems/em-http-request-1.1.7/lib/em-http-request.rb:1:in `<top (required)>'
 /usr/local/bundle/gems/webmock-3.24.0/lib/webmock/http_lib_adapters/em_http_request_adapter.rb:6:in `<top (required)>'
 /usr/local/bundle/gems/webmock-3.24.0/lib/webmock.rb:55:in `require_relative'
 /usr/local/bundle/gems/webmock-3.24.0/lib/webmock.rb:55:in `<top (required)>'
 /usr/local/bundle/gems/webmock-3.24.0/lib/webmock/rspec.rb:3:in `<top (required)>'
 ./spec/spec_helper.rb:8:in `<top (required)>'
Run options: exclude {:skip=>true}
`

Looking at the automated build for the project it also fails with the same error. Is there some other way to run the tests locally or some fix that can be applied? Not having the unit tests running seems like it would inhibit contributions.

Any help would be appreciated.

**Comment by jordan-brough** [comment]
This is from this issue: https://github.com/ruby/uri/issues/131

**Comment by modohash** [comment]
@jordan-brough Great, thanks for this.
