### ISSUE TITLE
Status of the Azure provider

### ISSUE THREAD

**Issue by anweiss** [travis-ci/dpl#137]
Noticed that there was some development on an Azure provider in the rkh-azure branch. Do we have any updates on the status of this?

**Comment by jpoon** [comment]
+1

Would love to help or lead the charge on adding Azure support.

**Comment by rkh** [comment]
Feel free to look into it, we are not currently working on this and it's
not on our roadmap anymore.

**Comment by jpoon** [comment]
My plan is to extend the provider to push it to an Azure Website. @anweiss: Was that satisfy the scenario you had in mind?

**Comment by anweiss** [comment]
You got it. I'd be glad to help contribute although my Ruby skills aren't up to snuff lol

**Comment by BanzaiMan** [comment]
We've added Azure provider with #314.
