### ISSUE TITLE
Add support for cache control headers on s3

### ISSUE THREAD

**Issue by davidblurton** [travis-ci/dpl#138]
It would be brilliant if s3 deploy could add cache control headers. Syntax could be 

```
cache_control: max-age=2592000
```

**Comment by caub** [comment]
so how can you apply different cache_control to index.html for example? by putting another deploy entry?

**Comment by danielwhatmuff** [comment]
Looking for the same thing as you @caub did you figure it out?

**Comment by caub** [comment]
Some good way I think (not tested yet) is to use https://github.com/travis-ci/travis-ci/issues/3139#issuecomment-74105293 and 

```
deploy:
  provider: script
  script: aws sync ...
  ....
```
