### ISSUE TITLE
Standardize way to indicate when deployment was successful

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/dpl#143]
Currently, each provider's `push_app` has no standardized way to communicate with other parts of the library the outcome of the deployment.

It should perhaps return a Hash or a Struct with useful information: outcome (success/failure), message, etc.

Such communication will be useful for notifiers (e.g., New Relic (#86)), so that they can notify only when deployment was successful.

**Comment by BanzaiMan** [comment]
Those providers using `#system` call (such as NPM, CloudFoundry) should be relatively easy to save off the status code.

**Comment by pimterry** [comment]
This would be really useful - it's pretty annoying that our `npm publish` deploy can fail completely, but stay green and silent 🙁

**Comment by brentshields** [comment]
👍

**Comment by andamian** [comment]
Are there any plans to address this issue or is there a workaround (such as deploying via a custom script or allowing for a custom check of the result)? Specifically, I'm interested in the pypi deployment. Feedback is integral part of the travis jobs and without it, the use of deploy is less appealing.

**Comment by tdmalone** [comment]
^ I’m not sure if this is enough but I would still love to see a resolution to this issue!

**Comment by jimmykane** [comment]
Still?

**Comment by patrickfav** [comment]
I think this is a crucial issue. Ignoring the outcome of the deployment will make it extremely inconvenient to use continuous deployment in any form and can be a real time waster (if you have to check if the thing was actually deployed are the bug not fixed).

(btw. Travis CI is an awesome service ❤️)

**Comment by tdmalone** [comment]
unstale

**Comment by tdmalone** [comment]
unstale

**Comment by tdmalone** [comment]
👋

**Comment by svenfuchs** [comment]
I think this issue here can be closed as this is addressed in `master` (dpl v2). Please feel free to re-open if needed.
