### ISSUE TITLE
Simplify custom dpl install

### ISSUE THREAD

**Issue by johanneswuerbach** [travis-ci/dpl#146]
I use the following before_deploy script today to install a custom version of dpl. (for development and not merge-able providers)
```
before_deploy:
- git clone -b provider-deis-0.7 https://github.com/johanneswuerbach/dpl.git
- cd dpl && gem build dpl.gemspec
- rvm 1.9.3 do ruby -S gem install dpl-*.gem
- cd ..
```

This process is a bit error prone as it requires to set the custom dpl version > the published dpl and to switch into the same ruby version travis builder installs the dpl gem into when installing the local build gem.

**Comment by jschall** [comment]
Is this still the correct way to do this? I couldn't find any instructions anywhere on running a custom version of dpl. Seems a no-brainer given how rough and un-configurable some of the provider scripts are.

**Comment by Joshua-Anderson** [comment]
Maybe we could add a option to skip auto-installing dpl from rubygems.

**Comment by giltsl** [comment]
Anyone found a solution to skip auto-installing dpl?
It will help me too.

**Comment by rkh** [comment]
There's no way to skip auto-installing atm, but you can add `local: true`
to have it use a dpl-*.gem from the project root.

**Comment by BanzaiMan** [comment]
@rkh That behavior doesn't seem to be documented. Should it?

**Comment by rkh** [comment]
Probably? Added it when working on SDS.

**Comment by jasny** [comment]
@rkh It's still not really clear to me. Could you add a step by step explanation in README.md?

**Comment by BanzaiMan** [comment]
This is now more streamlined and documented in https://github.com/travis-ci/dpl/blob/master/TESTING.md.
