### ISSUE TITLE
S3 upload doesn't upload files and directories which start with dot.

### ISSUE THREAD

**Issue by akirasosa** [travis-ci/dpl#148]
I have a question about S3 Deployment.
http://docs.travis-ci.com/user/deployment/s3/

I have some files named like ".sessions.html" whose name starts with dot. These files can't be uploaded to S3.

Background:

I try to upload coverage reports created by Jacoco. Jacoco produces some files and directories whose name starts with dot.

**Comment by stianjensen** [comment]
Is this documented somewhere else now? Couldn't find a reference to it in the provided link.
