### ISSUE TITLE
[npm] failure to deploy shows no error message

### ISSUE THREAD

**Issue by tjwebb** [travis-ci/dpl#151]
It took me awhile to figure out that my `api_key` was wrong, since this is the output when my npm deployment "fails":
```
The command "npm test" exited with 0.
$ git fetch --tags
Done. Your build exited with 0.
```
Should look a little more faily; at least, not exit with 0.

**Comment by BanzaiMan** [comment]
We now show more detailed explanation for not firing deployment. I think this can be closed. If there is another issue to look at, please open a new one.
