### ISSUE TITLE
Bintray integration

### ISSUE THREAD

**Issue by mikepurvis** [travis-ci/dpl#160]
It's a pretty straightforward curl invocation:

https://gist.github.com/hgomez/4447779

Can obviously do this from after_success, but it's convenient having the on-tags functionality without a wrapper shell script.

**Comment by xbeta** [comment]
+1

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/dpl/pull/256.

Please refrain from :+1:'ing. If you want to be notified of updates, please subscribe instead.
