### ISSUE TITLE
Add Support for Docker builds

### ISSUE THREAD

**Issue by drGrove** [travis-ci/dpl#169]
When a build is successful. Add the ability to create a docker image, tag it and push it to docker (or private registry) with basic auth.

**Comment by wpietri** [comment]
I'm late to the party, but @Joshua-Anderson, I'd definitely have a use for triggering DockerHub builds. For now I'm just going to hack something together with a `curl` call from our `travis.yml` file. Right now DockerHub likes to build on every commit, successful or not, which is a little eager for my tastes. I'd rather have it only build from Travis-blessed commits.

**Comment by Joshua-Anderson** [comment]
> For now I'm just going to hack something together with a curl call from our travis.yml file.

That sounds like a pretty good approach. You can use the [script provider](https://github.com/travis-ci/dpl#script) to do that. If you have the time, you can also write up a provider that uses the curl to call the hook and open a PR with it.

**Comment by joshk** [comment]
Love the idea of having a proper DockerHub provider! :)

**Comment by wpietri** [comment]
Ok, I'll start with the script provider, get it working, and then make a proper provider. @Joshua-Anderson, is there a particular existing provider I should use as a model for the right way to make one?

**Comment by Joshua-Anderson** [comment]
@wpietri [cloud66[(https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/cloud66.rb) also is webhook based, so I'd take a look at that.

**Comment by cybertk** [comment]
+1
