### ISSUE TITLE
elastic beanstalk - specify folder to deploy

### ISSUE THREAD

**Issue by BenShaw** [travis-ci/dpl#172]
Is it possible to specify which folder to deploy to elastic beanstalk on a build.
Similar to **local-dir**  for s3 deployments. Similarly, i would like travis to not clean up built files (as these are the ones i want to deploy)  s3 deploy's achieve this through **skip_cleanup**

**Comment by dimascyriaco** [comment]
This would be great.

**Comment by awesomescot** [comment]
So it looks like the files that are being zipped up are coming from a 'git ls-files -z' command.  So should we change it to default to zip all files in the project root?  Or should we leave the default as using 'git ls-files -z'?  I assume we would not use the ls-files command when we use the local-dir.  Does anyone have a sugestion here or preference?
