### ISSUE TITLE
Heroku git provider doesn't recognise failures

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/dpl#185]
It looks like if the `git push` in the Heroku git provider fails (for example, if Heroku is down), we don't catch that properly and continue on with the deploy, and the deploy ends up being marked as passing, marking a build as passing as well.

I think this is because the `push_app` method is just a `system` call, which doesn't really do anything except return non-true for failures, and we never check the return value of `push_app`.

**Comment by meatballhat** [comment]
It's worth noting that this appears to be the case with the api provider as well.  The pass/fail of a `push_app` is ignored, which can be especially bad if there are `run` commands that do irreversible migrations afterward.
