### ISSUE TITLE
Modulus deploys failing without error

### ISSUE THREAD

**Issue by fiveisprime** [travis-ci/dpl#207]
When attempting to deploy to Modulus, the deploy step is empty and exits with 0 although my project isn't deployed. Is there a way to see if there are any error from the deploy provider module or any indication as to why the deploy never happens?

**Comment by joshmatz** [comment]
I'll second this one as it's currently happening to me... :\

**Comment by luisatlive** [comment]
Ditto...

**Comment by BanzaiMan** [comment]
What does the failure look like?

**Comment by luisatlive** [comment]
Unfortunately the OP is correct and there's no info provided. The logs show an empty line under the actual deploy step and report a success but nothing is actually deployed. 

To troubleshoot I downloaded dpl locally and ran the same dpl command that should be running in the deploy stage from my local box and that deployed correctly so this is only happening when using the deploy: stage in .travis.yml

**Comment by BanzaiMan** [comment]
Has this ever worked? The deployment is simply trying to run this shell command:

https://github.com/travis-ci/dpl/blame/f7925e384ff0b692232529cb946f1cbd1a6c027b/lib/dpl/provider/modulus.rb#L19

It is failing here without meaningful output. Is it possible to add more verbose output? (I'm happy to merge any PR for debugging purposes and deploy it so it can be tested.)

**Comment by benjsicam** [comment]
+1 Same thing for me. There are changes in my Github repo that needs to be deployed to Modulus but it says it's already up to date.

```Deploying application```
```Already up-to-date!```
```HEAD detached at 57c3f5c```
```nothing to commit, working directory clean```
```Dropped refs/stash@{0} (a7845f773433b2ca6304a3e6ed7df56ed3307629)```
```Done. Your build exited with 0.```

**Comment by BanzaiMan** [comment]
So, is Modulus deployment based on git and `modulus deploy` fails if there is nothing to commit? Do you need to do something with the git repository (for example, change branch, stash changes) before deploying? Or is `skip_cleanup: true` required? http://docs.travis-ci.com/user/deployment/modulus/#Deploying-build-artifacts

**Comment by fiveisprime** [comment]
The Modulus CLI is not git-based so I don't expect that output to be related.

The `api_key` is used for authentication (as `MODULUS_TOKEN`) then the
deploy command is called. Typical output from the Modulus CLI is

```
Welcome to Modulus
You are logged in as fiveisprime
Selecting project-name

Compressing project...
4.2 KB written
Uploading project...
```

I am able to run this from dpl directly so maybe it's a permissions error? The
CLI _does_ attempt to write a file before deploying.

**Comment by BanzaiMan** [comment]
Sorry, but I'm a bit at a loss. Is there a build log that I can look at that shows the failure? If the log location is sensitive, please email support@travis-ci.com.

**Comment by vanoorschot** [comment]
I have the same issue.
This is the deploy part from the log:
```
dpl.0
Fetching: dpl-1.7.18.gem (100%)
Successfully installed dpl-1.7.18
1 gem installed
12.02s
dpl.1
Installing deploy dependencies
/home/travis/.nvm/versions/node/v0.12.7/bin/modulus -> /home/travis/.nvm/versions/node/v0.12.7/lib/node_modules/modulus/bin/modulus
modulus@3.15.1 /home/travis/.nvm/versions/node/v0.12.7/lib/node_modules/modulus
├── progress@0.1.0
├── through@2.3.4
├── split@0.3.0
├── colors@0.6.2
├── find-file-sync@0.0.2
├── text-table@0.2.0
├── node-uuid@1.3.3
├── async@0.1.22
├── commander-plus@0.0.6 (keypress@0.1.0)
├── underscore@1.4.4
├── demeteorizer@2.3.1 (async@0.2.10, commander@1.1.1, semver@3.0.1, rimraf@2.3.2)
├── fstream-ignore@0.0.10 (inherits@2.0.1, minimatch@0.3.0, fstream@0.1.31)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.6, utile@0.2.1, winston@0.8.3)
├── request@2.27.0 (aws-sign@0.3.0, forever-agent@0.5.2, qs@0.6.6, tunnel-agent@0.3.0, oauth-sign@0.3.0, json-stringify-safe@5.0.1, cookie-jar@0.3.0, mime@1.2.11, node-uuid@1.4.3, form-data@0.1.4, http-signature@0.10.1, hawk@1.0.0)
├── fs-tools@0.2.11 (async@0.2.10, lodash@2.4.2)
├── zip-stream@0.5.1 (compress-commons@0.2.9, readable-stream@1.0.33, lodash@3.2.0)
└── update-notifier@0.1.10 (chalk@0.4.0, semver@2.3.2, request@2.60.0, configstore@0.3.2)
dpl.2
Preparing deploy
dpl.3
Deploying application
Done. Your build exited with 0.
```

**Comment by jakehewitt** [comment]
This is still a problem, any updates?

**Comment by jakehewitt** [comment]
This is the result of running ```dpl --provider=modulus --api-key=MY_KEY --project-name=development```

    Installing deploy dependencies
    Preparing deploy
    Saved working directory and index state WIP on develop: f590d55 Merge pull request #9 from            ApolloRobotics/SAFE-travis-config
    HEAD is now at f590d55 Merge pull request #9 from ApolloRobotics/SAFE-travis-config
    Deploying application
    Already up-to-date!
    On branch develop
    nothing to commit, working directory clean
    Dropped refs/stash@{0} (c7c162251e3475e4038a3ff3414e3b0d5290181f)

**Comment by BanzaiMan** [comment]
As I said previously, the deployment boils down to the command:

     MODULUS_TOKEN=#{option(:api_key)} modulus deploy -p #{option(:project_name)}

If it's not working, then I must say that `modulus` is not. Does anyone know how to get more output from it?

**Comment by jakehewitt** [comment]
I wrote this shell script 

    #!/bin/bash
    if [ "$TRAVIS_BRANCH" == "develop" ]; then
        MODULUS_TOKEN=MY_KEY modulus deploy -p Development
    fi
    if [ "$TRAVIS_BRANCH" == "master" ]; then
        MODULUS_TOKEN=MY_KEY modulus deploy -p Production
    fi

that executes after_success and it works perfectly so Modulus is working

**Comment by jakehewitt** [comment]
I changed the code to this:

    def push_app
        context.shell "MODULUS_TOKEN=#{option(:api_key)} modulus deploy -p #{option(:project_name)}"
        puts $?.exitstatus
    end

I'm getting an exit status of 127 which is command not found

**Comment by BanzaiMan** [comment]
@jakehewitt I'm sorry, but I can't figure out what you did, and how you determined that things didn't work. If modulus is not installed, it stands to reason that it's not found.

Instead, could you try deploying with slightly different configurations? Namely,

```yaml
after_success:
  - npm install -g modulus
  - MODULUS_TOKEN=MODULUS_API_KEY modulus deploy -p MODULUS_PROJECT_NAME
```

where `MODULUS_API_KEY` and `MODULUS_PROJECT_NAME` are appropriately set? (Do not forget to encrypt `MODULUS_API_KEY`.)
