### ISSUE TITLE
Deploy Rust packages to Crates.io

### ISSUE THREAD

**Issue by hawkw** [travis-ci/dpl#233]
Rust libraries are typically deployed to [crates.io](http://doc.crates.io/index.html). Deployment to crates.io is [pretty simple](http://doc.crates.io/crates-io.html) and isn't hard to do with a custom `after_success` script. With that said, it would be rad if Travis supported it out of the box.

**Comment by SirDoctors** [comment]
It seems that deploying rust packages with cargo involves using a API key from (crates.io)[http://crates.io] to login to the API, then publishing via. the API. I'm looking to see if it's easier to use Cargo to do this, or accessing the API directly.
