### ISSUE TITLE
github releases: pre-release support

### ISSUE THREAD

**Issue by liamstask** [travis-ci/dpl#234]
I'm not sure what the best way to provide support for this would be, but I would like to be able to mark releases as pre-releases on github.

Two options I can think of:
- ability to simply mark all releases deployed by dpl as pre-release. the user can update them later to full releases by some other mechanism
- ability to specify pre-release for a given set of branch names. any releases from these branches would be marked as pre-release, otherwise as release.

I would prefer some version of option 2, if possible.

**Comment by BanzaiMan** [comment]
It appears to me that it's a straightforward case of passing `prerelease: true` to the payload. https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by BanzaiMan** [comment]
Rule-based prerelease might be easier, since otherwise I suspect tweaking `.travis.yml` for each prerelease becomes a hassle.

**Comment by totalvoidness** [comment]
+1

**Comment by dkerwin** [comment]
+1

**Comment by orius123** [comment]
As @BanzaiMan mentioned just adding `prerelease: true` under the deploy section makes release to be marked as pre-release.
example:
```yaml
deploy:
  provider: releases
  prerelease: true
  api_key: ....
```
no support for conditional though..

**Comment by Daenyth** [comment]
@orius123 Does that work right now? It's not in the documentation. Or were you saying it should work like that? I'd like to have this..

**Comment by orius123** [comment]
Dunno.. haven't tried for a while now.. worked back than.

**Comment by hbons** [comment]
Just tried and it seems to work fine. Would be nice to see it in the docs.
