### ISSUE TITLE
S3 deploy fails with dpl 1.7.10 

### ISSUE THREAD

**Issue by oysteingr** [travis-ci/dpl#239]
Since last friday, travis has consequently been failing on deploys to s3.

[0Ktravis_fold:end:after_success
[0Ktravis_fold:start:dpl.0
[0Ktravis_time:start:04a24fb4
[0KFetching: dpl-1.7.10.gem
Fetching: dpl-1.7.10.gem ( 15%)
Fetching: dpl-1.7.10.gem ( 17%)
Fetching: dpl-1.7.10.gem ( 31%)
Fetching: dpl-1.7.10.gem ( 33%)
Fetching: dpl-1.7.10.gem ( 47%)
Fetching: dpl-1.7.10.gem ( 50%)
Fetching: dpl-1.7.10.gem ( 64%)
Fetching: dpl-1.7.10.gem ( 66%)
Fetching: dpl-1.7.10.gem ( 80%)
Fetching: dpl-1.7.10.gem ( 83%)
Fetching: dpl-1.7.10.gem ( 96%)
Fetching: dpl-1.7.10.gem ( 99%)
Fetching: dpl-1.7.10.gem (100%)
Fetching: dpl-1.7.10.gem (100%)
Successfully installed dpl-1.7.10
1 gem installed
travis_time:end:04a24fb4:start=1427116844362548850,finish=1427116846494089711,duration=2131540861
[0Ktravis_fold:end:dpl.0
[0Ktravis_time:start:246b4b1f
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m
Fetching: mini_portile-0.6.2.gem
Fetching: mini_portile-0.6.2.gem (100%)
Fetching: mini_portile-0.6.2.gem (100%)
Successfully installed mini_portile-0.6.2
Fetching: nokogiri-1.6.6.2.gem
Fetching: nokogiri-1.6.6.2.gem (  1%)
Fetching: nokogiri-1.6.6.2.gem (  2%)
Fetching: nokogiri-1.6.6.2.gem (  3%)
Fetching: nokogiri-1.6.6.2.gem (  4%)
Fetching: nokogiri-1.6.6.2.gem (  5%)
Fetching: nokogiri-1.6.6.2.gem (  6%)
Fetching: nokogiri-1.6.6.2.gem (  7%)
Fetching: nokogiri-1.6.6.2.gem (  8%)
Fetching: nokogiri-1.6.6.2.gem (  9%)
Fetching: nokogiri-1.6.6.2.gem ( 10%)
Fetching: nokogiri-1.6.6.2.gem ( 11%)
Fetching: nokogiri-1.6.6.2.gem ( 12%)
Fetching: nokogiri-1.6.6.2.gem ( 13%)
Fetching: nokogiri-1.6.6.2.gem ( 14%)
Fetching: nokogiri-1.6.6.2.gem ( 15%)
Fetching: nokogiri-1.6.6.2.gem ( 16%)
Fetching: nokogiri-1.6.6.2.gem ( 17%)
Fetching: nokogiri-1.6.6.2.gem ( 18%)
Fetching: nokogiri-1.6.6.2.gem ( 19%)
Fetching: nokogiri-1.6.6.2.gem ( 20%)
Fetching: nokogiri-1.6.6.2.gem ( 21%)
Fetching: nokogiri-1.6.6.2.gem ( 22%)
Fetching: nokogiri-1.6.6.2.gem ( 23%)
Fetching: nokogiri-1.6.6.2.gem ( 24%)
Fetching: nokogiri-1.6.6.2.gem ( 25%)
Fetching: nokogiri-1.6.6.2.gem ( 26%)
Fetching: nokogiri-1.6.6.2.gem ( 27%)
Fetching: nokogiri-1.6.6.2.gem ( 28%)
Fetching: nokogiri-1.6.6.2.gem ( 29%)
Fetching: nokogiri-1.6.6.2.gem ( 30%)
Fetching: nokogiri-1.6.6.2.gem ( 31%)
Fetching: nokogiri-1.6.6.2.gem ( 32%)
Fetching: nokogiri-1.6.6.2.gem ( 33%)
Fetching: nokogiri-1.6.6.2.gem ( 34%)
Fetching: nokogiri-1.6.6.2.gem ( 35%)
Fetching: nokogiri-1.6.6.2.gem ( 36%)
Fetching: nokogiri-1.6.6.2.gem ( 37%)
Fetching: nokogiri-1.6.6.2.gem ( 38%)
Fetching: nokogiri-1.6.6.2.gem ( 39%)
Fetching: nokogiri-1.6.6.2.gem ( 40%)
Fetching: nokogiri-1.6.6.2.gem ( 41%)
Fetching: nokogiri-1.6.6.2.gem ( 42%)
Fetching: nokogiri-1.6.6.2.gem ( 43%)
Fetching: nokogiri-1.6.6.2.gem ( 44%)
Fetching: nokogiri-1.6.6.2.gem ( 45%)
Fetching: nokogiri-1.6.6.2.gem ( 46%)
Fetching: nokogiri-1.6.6.2.gem ( 47%)
Fetching: nokogiri-1.6.6.2.gem ( 48%)
Fetching: nokogiri-1.6.6.2.gem ( 49%)
Fetching: nokogiri-1.6.6.2.gem ( 50%)
Fetching: nokogiri-1.6.6.2.gem ( 51%)
Fetching: nokogiri-1.6.6.2.gem ( 52%)
Fetching: nokogiri-1.6.6.2.gem ( 53%)
Fetching: nokogiri-1.6.6.2.gem ( 54%)
Fetching: nokogiri-1.6.6.2.gem ( 55%)
Fetching: nokogiri-1.6.6.2.gem ( 56%)
Fetching: nokogiri-1.6.6.2.gem ( 57%)
Fetching: nokogiri-1.6.6.2.gem ( 58%)
Fetching: nokogiri-1.6.6.2.gem ( 59%)
Fetching: nokogiri-1.6.6.2.gem ( 60%)
Fetching: nokogiri-1.6.6.2.gem ( 61%)
Fetching: nokogiri-1.6.6.2.gem ( 62%)
Fetching: nokogiri-1.6.6.2.gem ( 63%)
Fetching: nokogiri-1.6.6.2.gem ( 64%)
Fetching: nokogiri-1.6.6.2.gem ( 65%)
Fetching: nokogiri-1.6.6.2.gem ( 66%)
Fetching: nokogiri-1.6.6.2.gem ( 67%)
Fetching: nokogiri-1.6.6.2.gem ( 68%)
Fetching: nokogiri-1.6.6.2.gem ( 69%)
Fetching: nokogiri-1.6.6.2.gem ( 70%)
Fetching: nokogiri-1.6.6.2.gem ( 71%)
Fetching: nokogiri-1.6.6.2.gem ( 72%)
Fetching: nokogiri-1.6.6.2.gem ( 73%)
Fetching: nokogiri-1.6.6.2.gem ( 74%)
Fetching: nokogiri-1.6.6.2.gem ( 75%)
Fetching: nokogiri-1.6.6.2.gem ( 76%)
Fetching: nokogiri-1.6.6.2.gem ( 77%)
Fetching: nokogiri-1.6.6.2.gem ( 78%)
Fetching: nokogiri-1.6.6.2.gem ( 79%)
Fetching: nokogiri-1.6.6.2.gem ( 80%)
Fetching: nokogiri-1.6.6.2.gem ( 81%)
Fetching: nokogiri-1.6.6.2.gem ( 82%)
Fetching: nokogiri-1.6.6.2.gem ( 83%)
Fetching: nokogiri-1.6.6.2.gem ( 84%)
Fetching: nokogiri-1.6.6.2.gem ( 85%)
Fetching: nokogiri-1.6.6.2.gem ( 86%)
Fetching: nokogiri-1.6.6.2.gem ( 87%)
Fetching: nokogiri-1.6.6.2.gem ( 88%)
Fetching: nokogiri-1.6.6.2.gem ( 89%)
Fetching: nokogiri-1.6.6.2.gem ( 90%)
Fetching: nokogiri-1.6.6.2.gem ( 91%)
Fetching: nokogiri-1.6.6.2.gem ( 92%)
Fetching: nokogiri-1.6.6.2.gem ( 93%)
Fetching: nokogiri-1.6.6.2.gem ( 94%)
Fetching: nokogiri-1.6.6.2.gem ( 95%)
Fetching: nokogiri-1.6.6.2.gem ( 96%)
Fetching: nokogiri-1.6.6.2.gem ( 97%)
Fetching: nokogiri-1.6.6.2.gem ( 98%)
Fetching: nokogiri-1.6.6.2.gem ( 99%)
Fetching: nokogiri-1.6.6.2.gem (100%)
Fetching: nokogiri-1.6.6.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.6.2
Fetching: aws-sdk-v1-1.63.0.gem
Fetching: aws-sdk-v1-1.63.0.gem (  1%)
Fetching: aws-sdk-v1-1.63.0.gem (  2%)
Fetching: aws-sdk-v1-1.63.0.gem (  3%)
Fetching: aws-sdk-v1-1.63.0.gem (  4%)
Fetching: aws-sdk-v1-1.63.0.gem (  5%)
Fetching: aws-sdk-v1-1.63.0.gem (  6%)
Fetching: aws-sdk-v1-1.63.0.gem (  7%)
Fetching: aws-sdk-v1-1.63.0.gem (  8%)
Fetching: aws-sdk-v1-1.63.0.gem (  9%)
Fetching: aws-sdk-v1-1.63.0.gem ( 10%)
Fetching: aws-sdk-v1-1.63.0.gem ( 11%)
Fetching: aws-sdk-v1-1.63.0.gem ( 12%)
Fetching: aws-sdk-v1-1.63.0.gem ( 13%)
Fetching: aws-sdk-v1-1.63.0.gem ( 14%)
Fetching: aws-sdk-v1-1.63.0.gem ( 15%)
Fetching: aws-sdk-v1-1.63.0.gem ( 16%)
Fetching: aws-sdk-v1-1.63.0.gem ( 17%)
Fetching: aws-sdk-v1-1.63.0.gem ( 18%)
Fetching: aws-sdk-v1-1.63.0.gem ( 19%)
Fetching: aws-sdk-v1-1.63.0.gem ( 20%)
Fetching: aws-sdk-v1-1.63.0.gem ( 21%)
Fetching: aws-sdk-v1-1.63.0.gem ( 22%)
Fetching: aws-sdk-v1-1.63.0.gem ( 23%)
Fetching: aws-sdk-v1-1.63.0.gem ( 24%)
Fetching: aws-sdk-v1-1.63.0.gem ( 25%)
Fetching: aws-sdk-v1-1.63.0.gem ( 26%)
Fetching: aws-sdk-v1-1.63.0.gem ( 27%)
Fetching: aws-sdk-v1-1.63.0.gem ( 28%)
Fetching: aws-sdk-v1-1.63.0.gem ( 29%)
Fetching: aws-sdk-v1-1.63.0.gem ( 30%)
Fetching: aws-sdk-v1-1.63.0.gem ( 31%)
Fetching: aws-sdk-v1-1.63.0.gem ( 32%)
Fetching: aws-sdk-v1-1.63.0.gem ( 33%)
Fetching: aws-sdk-v1-1.63.0.gem ( 34%)
Fetching: aws-sdk-v1-1.63.0.gem ( 35%)
Fetching: aws-sdk-v1-1.63.0.gem ( 36%)
Fetching: aws-sdk-v1-1.63.0.gem ( 37%)
Fetching: aws-sdk-v1-1.63.0.gem ( 38%)
Fetching: aws-sdk-v1-1.63.0.gem ( 39%)
Fetching: aws-sdk-v1-1.63.0.gem ( 40%)
Fetching: aws-sdk-v1-1.63.0.gem ( 41%)
Fetching: aws-sdk-v1-1.63.0.gem ( 42%)
Fetching: aws-sdk-v1-1.63.0.gem ( 43%)
Fetching: aws-sdk-v1-1.63.0.gem ( 44%)
Fetching: aws-sdk-v1-1.63.0.gem ( 45%)
Fetching: aws-sdk-v1-1.63.0.gem ( 46%)
Fetching: aws-sdk-v1-1.63.0.gem ( 47%)
Fetching: aws-sdk-v1-1.63.0.gem ( 48%)
Fetching: aws-sdk-v1-1.63.0.gem ( 49%)
Fetching: aws-sdk-v1-1.63.0.gem ( 50%)
Fetching: aws-sdk-v1-1.63.0.gem ( 51%)
Fetching: aws-sdk-v1-1.63.0.gem ( 52%)
Fetching: aws-sdk-v1-1.63.0.gem ( 53%)
Fetching: aws-sdk-v1-1.63.0.gem ( 54%)
Fetching: aws-sdk-v1-1.63.0.gem ( 55%)
Fetching: aws-sdk-v1-1.63.0.gem ( 56%)
Fetching: aws-sdk-v1-1.63.0.gem ( 57%)
Fetching: aws-sdk-v1-1.63.0.gem ( 58%)
Fetching: aws-sdk-v1-1.63.0.gem ( 59%)
Fetching: aws-sdk-v1-1.63.0.gem ( 60%)
Fetching: aws-sdk-v1-1.63.0.gem ( 61%)
Fetching: aws-sdk-v1-1.63.0.gem ( 62%)
Fetching: aws-sdk-v1-1.63.0.gem ( 63%)
Fetching: aws-sdk-v1-1.63.0.gem ( 64%)
Fetching: aws-sdk-v1-1.63.0.gem ( 65%)
Fetching: aws-sdk-v1-1.63.0.gem ( 66%)
Fetching: aws-sdk-v1-1.63.0.gem ( 67%)
Fetching: aws-sdk-v1-1.63.0.gem ( 68%)
Fetching: aws-sdk-v1-1.63.0.gem ( 69%)
Fetching: aws-sdk-v1-1.63.0.gem ( 70%)
Fetching: aws-sdk-v1-1.63.0.gem ( 71%)
Fetching: aws-sdk-v1-1.63.0.gem ( 72%)
Fetching: aws-sdk-v1-1.63.0.gem ( 73%)
Fetching: aws-sdk-v1-1.63.0.gem ( 74%)
Fetching: aws-sdk-v1-1.63.0.gem ( 75%)
Fetching: aws-sdk-v1-1.63.0.gem ( 76%)
Fetching: aws-sdk-v1-1.63.0.gem ( 77%)
Fetching: aws-sdk-v1-1.63.0.gem ( 78%)
Fetching: aws-sdk-v1-1.63.0.gem ( 79%)
Fetching: aws-sdk-v1-1.63.0.gem ( 80%)
Fetching: aws-sdk-v1-1.63.0.gem ( 81%)
Fetching: aws-sdk-v1-1.63.0.gem ( 82%)
Fetching: aws-sdk-v1-1.63.0.gem ( 83%)
Fetching: aws-sdk-v1-1.63.0.gem ( 84%)
Fetching: aws-sdk-v1-1.63.0.gem ( 85%)
Fetching: aws-sdk-v1-1.63.0.gem ( 86%)
Fetching: aws-sdk-v1-1.63.0.gem ( 88%)
Fetching: aws-sdk-v1-1.63.0.gem ( 89%)
Fetching: aws-sdk-v1-1.63.0.gem ( 90%)
Fetching: aws-sdk-v1-1.63.0.gem ( 91%)
Fetching: aws-sdk-v1-1.63.0.gem ( 92%)
Fetching: aws-sdk-v1-1.63.0.gem ( 93%)
Fetching: aws-sdk-v1-1.63.0.gem ( 94%)
Fetching: aws-sdk-v1-1.63.0.gem ( 95%)
Fetching: aws-sdk-v1-1.63.0.gem ( 96%)
Fetching: aws-sdk-v1-1.63.0.gem ( 97%)
Fetching: aws-sdk-v1-1.63.0.gem ( 98%)
Fetching: aws-sdk-v1-1.63.0.gem ( 99%)
Fetching: aws-sdk-v1-1.63.0.gem (100%)
Fetching: aws-sdk-v1-1.63.0.gem (100%)
Successfully installed aws-sdk-v1-1.63.0
3 gems installed
Fetching: mime-types-2.4.3.gem
Fetching: mime-types-2.4.3.gem (  7%)
Fetching: mime-types-2.4.3.gem ( 13%)
Fetching: mime-types-2.4.3.gem ( 14%)
Fetching: mime-types-2.4.3.gem ( 20%)
Fetching: mime-types-2.4.3.gem ( 21%)
Fetching: mime-types-2.4.3.gem ( 27%)
Fetching: mime-types-2.4.3.gem ( 28%)
Fetching: mime-types-2.4.3.gem ( 34%)
Fetching: mime-types-2.4.3.gem ( 35%)
Fetching: mime-types-2.4.3.gem ( 40%)
Fetching: mime-types-2.4.3.gem ( 42%)
Fetching: mime-types-2.4.3.gem ( 47%)
Fetching: mime-types-2.4.3.gem ( 49%)
Fetching: mime-types-2.4.3.gem ( 54%)
Fetching: mime-types-2.4.3.gem ( 56%)
Fetching: mime-types-2.4.3.gem ( 61%)
Fetching: mime-types-2.4.3.gem ( 63%)
Fetching: mime-types-2.4.3.gem ( 68%)
Fetching: mime-types-2.4.3.gem ( 70%)
Fetching: mime-types-2.4.3.gem ( 74%)
Fetching: mime-types-2.4.3.gem ( 77%)
Fetching: mime-types-2.4.3.gem ( 81%)
Fetching: mime-types-2.4.3.gem ( 84%)
Fetching: mime-types-2.4.3.gem ( 88%)
Fetching: mime-types-2.4.3.gem ( 91%)
Fetching: mime-types-2.4.3.gem ( 95%)
Fetching: mime-types-2.4.3.gem ( 97%)
Fetching: mime-types-2.4.3.gem (100%)
Fetching: mime-types-2.4.3.gem (100%)
Successfully installed mime-types-2.4.3
1 gem installed

travis_fold:end:dpl.1
travis_fold:start:dpl.2
[33mPreparing deploy[0m
Logging in with Access Key: ****************5EXA

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m
uploading "latest.tar.gz"

travis_fold:end:dpl.3
travis_time:end:246b4b1f:start=1427116846503790996,finish=1427116972561790673,duration=126057999677
[0Ktravis_fold:start:dpl.0
[0Ktravis_time:start:140a8628
[0KSuccessfully installed dpl-1.7.10
1 gem installed
travis_time:end:140a8628:start=1427116972571133475,finish=1427116974187695481,duration=1616562006
[0Ktravis_fold:end:dpl.0
[0Ktravis_time:start:04c889ec
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m

travis_fold:end:dpl.1
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- aws-sdk (LoadError)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/provider.rb:65:in `requires'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/provider/code_deploy.rb:6:in `<class:CodeDeploy>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/provider/code_deploy.rb:5:in `<class:Provider>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/provider/code_deploy.rb:4:in `<module:DPL>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/provider/code_deploy.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/provider.rb:47:in `const_get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/provider.rb:47:in `block in new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/provider.rb:44:in `new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.10/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy

**Comment by BanzaiMan** [comment]
Sorry about the issue. We've just released 1.7.11, which sidesteps this check. Please test it.

**Comment by oysteingr** [comment]
Thanks, seems to work. Have not seen any similar failures on 1.7.11. closing issue
