### ISSUE TITLE
Login failed when deploying to deis

### ISSUE THREAD

**Issue by jorihardman** [travis-ci/dpl#240]
Hello,

I realize that the deis deploy code hasn't changed since the last issue I submitted, and yet I've lost the ability to deploy.

When trying to deploy I get the following messages:

```
No stash found.
Login failed.
failed to deploy
```

Typically, when travis deploys, I can see the login in my deis controller logs. A failed login will look like this:

```
Mar 24 15:59:31 deis-1 sh[2844]: 172.17.42.1 "POST /v1/auth/login/ HTTP/1.0" 400 68 "python-requests/2.5.1 CPython/2.7.5 Darwin/13.4.0"
```

However I get no logged auth attempts from travis. If I run the auth command manually from my machine:

```
deis login deis.myiphere.xip.io --username=travis --password=mypasswordhere
```

I can login successfully. Is there any other way to debug this situation? This started happening around 5 days ago without me changing my deis cluster in any way or changing my travis.yml.

**Comment by eMxyzptlk** [comment]
I'm currently having the same issue.

**Comment by eMxyzptlk** [comment]
Ok so I was able to debug this and workaround this issue (actually two issues):

- DPL is installing `deis` through `pip install --user`. Pip installs the `deis` script into `$HOME/.local/bin` which is not in the PATH. Fix: In your `before_install` section of your .travis.yml, add `export PATH="$PATH:$HOME/.local/bin"`
- I was also hitting deis/deis#3285 worked around it by making the deployer an admin (bad bad idea, this should be fixed soon!)

**Comment by eMxyzptlk** [comment]
Interesting, it seems that `self.class.pip` (called [here](https://github.com/travis-ci/dpl/blob/bacfb630ffc860a63551f5fc77acb2e7e4b6b45b/lib/dpl/provider/deis.rb#L7)) does actually [export the env variable](https://github.com/travis-ci/dpl/blob/a01c9e8d09a13bce7ab351bcaa7a0b6397ef381e/lib/dpl/provider.rb#L89).

**Comment by jorihardman** [comment]
@eMxyzptlk Thank you for looking into this! Your workaround is working for me, but it is odd that the script does attempt to set it already. Luckily, I haven't run into the deis 500 error yet. My most recent key was deleted just fine.

**Comment by philipz** [comment]
@eMxyzptlk , after add the `export PATH="$PATH:$HOME/.local/bin"` and import the ssh key of deis keys. Travic-CI can deploy to my Deis Server.
[My Travic-CI result](https://travis-ci.org/philipz/example-nodejs-express)

**Comment by eMxyzptlk** [comment]
@philipz FYI you're not supposed to call dpl directly in an after_success. Instead you should include a section in your `.travis.yml` as such:

```
deploy:
  # The prod application, deployed from the production branch.
  - provider: deis
    controller: deis....
    app: api
    username: dmx_deployer
    password:
      secure: ....
    on:
      repo: mycompany/api
      branch: production
      go: 1.4
```

See http://docs.travis-ci.com/user/deployment/deis/

**Comment by philipz** [comment]
@eMxyzptlk Yes, you are right!

**Comment by kalbasit** [comment]
This can probably be closed now that the workaround is no longer needed.
