### ISSUE TITLE
Cloud Foundry add skip-ssl-validation

### ISSUE THREAD

**Issue by MitchK** [travis-ci/dpl#244]
We are on a internal development Cloud Foundry PaaS and Travis CI Enterprise. 

The on-premise PaaS has not SSL certificate that is signed by a public authority. 
Is there the possibility to add the ```--skip-ssl-validation``` option here? https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/cloud_foundry.rb#L13

Another option would be to allow passing additional parameters to the cf command in general.

**Comment by Joshua-Anderson** [comment]
Added it in PR #245

**Comment by BanzaiMan** [comment]
Will be available via `edge: true` shortly.

**Comment by MitchK** [comment]
:+1:
