### ISSUE TITLE
PyPI provider should use twine for registering and upload

### ISSUE THREAD

**Issue by jezdez** [travis-ci/dpl#253]
Twine is a tool from the pip makers, see https://pypi.python.org/pypi/twine for why you should use it instead of `python setup.py register` and `python setup.py upload`.

**Comment by alex** [comment]
Without this fixed, passwords are being transmitted in cleartext, in addition to allowing the upload itself to be MITM.

**Comment by jezdez** [comment]
Ah, good point, I should have mentioned that. Some more info: https://packaging.python.org/en/latest/distributing.html#upload-your-distributions

**Comment by BanzaiMan** [comment]
Could anyone take a look at improving https://github.com/travis-ci/dpl/blob/56ab84ab9ccb901a8fedc2bfee6a91c8ab7dc0e1/lib/dpl/provider/pypi.rb?

**Comment by jezdez** [comment]
@alex @dstufft Mind taking a look at #288?

**Comment by jezdez** [comment]
#288 continues to use the setup.py register command which has it's own [issues](https://packaging.python.org/en/latest/distributing.html#register-your-project) but at least this should transmit the registration form data via TLS.

**Comment by alex** [comment]
@BanzaiMan this can be closed now :-)

**Comment by d0ugal** [comment]
Awesome. Thanks @jezdez!

**Comment by BanzaiMan** [comment]
I'll need to cut a dpl release before everyone can use it. :-D

**Comment by BanzaiMan** [comment]
That is, right now, it requires `edge: true`.

**Comment by BanzaiMan** [comment]
OK. dpl 1.7.17 is out with this.

**Comment by jezdez** [comment]
@BanzaiMan @alex I'm afraid that #295 is needed as well to make this bullet proof.

Also could you point me to the repo where the Travis-CI service docs are hosted so I can add a note about the fact that this change would also require to do a project registration on https://pypi.python.org/ once when using the PyPI feature?

**Comment by dstufft** [comment]
FWIW that documentation will only be required until PyPI 2.0 is done, at that point simply uploading a project for the first time will also register it.

**Comment by BanzaiMan** [comment]
1.7.18 is out as well.

**Comment by BanzaiMan** [comment]
@jezdez @dstufft Why can't twine be user-installed? (See the issue above)

**Comment by dstufft** [comment]
Because ``--user`` doesn't work inside of a virtual environment.
