### ISSUE TITLE
Consider adding "local_dir" for providers other than S3

### ISSUE THREAD

**Issue by drogus** [travis-ci/dpl#254]
It sometimes may be needed to deploy app located in a directory different than the root dir.

**Comment by luzfcb** [comment]
related: https://github.com/travis-ci/travis-ci/issues/3767

**Comment by montaro** [comment]
Upvote!

**Comment by ivanperez-keera** [comment]
It seems it is possible to do this by cd-ing in `before_deploy`. But how to do it if there are several packages to upload? With env-vars? (I'm uploading to Hackage).

**Comment by kenfehling** [comment]
If you zip the contents of the build folder and then specify `zip_file: archive.zip` it should help.
