### ISSUE TITLE
CloudFoundry deployment: Define name of manifest file

### ISSUE THREAD

**Issue by kingd0m** [travis-ci/dpl#261]
Hello,

we have more than one manifest.yml files in our project (one with the configuration for test and one for prod). We're missing the possibility to select a dedicated manifest.yml which should be used for the build. It would be nice if you could add an optional parameter to define the name of the manifest.yml to be used.

Best Regards,
Michael

**Comment by BanzaiMan** [comment]
Does the `cf` CLI tool accept different manifest files on the command line? If so, adding the feature would be straightforward to implement it in https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/cloud_foundry.rb. If not, probably the easiest way to achieve it is to move the file to `manifest.yml` in `after_success`.

**Comment by kingd0m** [comment]
The cf CLI tool supports it using the option "-f" followed by the defined manifest file name.
