### ISSUE TITLE
Tests failing a random because of timeout

### ISSUE THREAD

**Issue by jasny** [travis-ci/dpl#272]
A timeout is causing tests to fail:

```
Failures:
  1) DPL::Provider::TestFairy#push_app push_app with iOS app_file
     Failure/Error: provider.push_app
     Net::ReadTimeout:
       Net::ReadTimeout
     # ./lib/dpl/provider/testfairy.rb:110:in `block in post'
     # ./lib/dpl/provider/testfairy.rb:109:in `post'
     # ./lib/dpl/provider/testfairy.rb:89:in `upload_app'
     # ./lib/dpl/provider/testfairy.rb:32:in `push_app'
     # ./spec/provider/testfairy_spec.rb:77:in `block (3 levels) in <top (required)>'
```
Job [66844720](https://travis-ci.org/travis-ci/dpl/builds/66844720), while [66844874](https://travis-ci.org/travis-ci/dpl/jobs/66844874) fails. The only difference is a change in README.md.

**Comment by BanzaiMan** [comment]
This might have been a network issue with Test Fairy. (We shouldn't be making these calls, ideally, but for now, I'll leave it.)

Since this hasn't been issues recently, I'll close this.
