### ISSUE TITLE
Not supported lambda.upload_function

### ISSUE THREAD

**Issue by k-kinzal** [travis-ci/dpl#283]
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.12/lib/dpl/provider/lambda.rb:23:in `push_app': undefined method `upload_function' for #<Aws::Lambda::Client> (NoMethodError)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.12/lib/dpl/provider.rb:137:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.12/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.12/lib/dpl/provider.rb:137:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.12/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.12/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.12/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
```
Error occurs when using the lambda provider.

https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/lambda.rb#L23
Using the `lambda.upload_function`, but it does not already support .

http://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html
http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionCode.html
http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html
Now it has been to use the `lambda.create_function` or `lambda.update_function_code` + `lambda.update_function_configuration`.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows this problem?

**Comment by k-kinzal** [comment]
https://travis-ci.org/k-kinzal/lambda-sns-to-chatwork-function#L158
It will be here.

**Comment by BanzaiMan** [comment]
Do you have the corresponding `.travis.yml`? The repo is either deleted or private.

**Comment by k-kinzal** [comment]
Sorry, It had been deleted. Please look so revived.

https://github.com/k-kinzal/lambda-sns-to-chatwork-function/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
Hi, @wtcross, could you take a look at this recent change in Lambda API?

**Comment by wtcross** [comment]
@BanzaiMan No problem. I just submitted a PR that I hope will fix the issue. The AWS Lambda API was in preview when the provider was implemented. The Lambda API was updated to `2015-03-31` from `2014-11-11`.

**Comment by BanzaiMan** [comment]
@wtcross Thank you!!!

@k-kinzal Could you try it with:

```yaml
deploy:
  provider: lambda
  edge: true
  ⋮
```

**Comment by k-kinzal** [comment]
@BanzaiMan 
@wtcross 
Thanks! It was successful ! !

**Comment by BanzaiMan** [comment]
The new dpl has been released, so you don't need `edge: true` any more.

Closing this.

**Comment by wtcross** [comment]
@BanzaiMan Any time!
@k-kinzal Glad it's working :) Thank you for reporting the issue.

When I get some time I plan on enhancing this provider to take advantage of the new API.
