### ISSUE TITLE
Allow to select reduced redundancy storage option when deploying to S3

### ISSUE THREAD

**Issue by guw** [travis-ci/dpl#291]
Amazon allows to select reduced redundancy storage when uploading object. It would be great if the S3 deployer would allow that. Especially for build-artifacts which can easily regenerated this would be a nice-to-have option.

**Comment by BanzaiMan** [comment]
@guw Could you point to the documentation regarding this option?

**Comment by guw** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRRS.html


-Gunnar

-- 
Gunnar Wagenknecht
On the road. Please excuse briefness and typos. 

Am 18.08.2015 um 16:45 schrieb Hiro Asari <notifications@github.com>:

**Comment by BanzaiMan** [comment]
The S3 option to pass is `storage_class: "REDUCED_REDUNDANCY"`.
