### ISSUE TITLE
biicode deployment doesn't work on container based builds

### ISSUE THREAD

**Issue by smspillaz** [travis-ci/dpl#302]
The `biicode` provider [uses](https://github.com/travis-ci/dpl/blob/4c8fd4f6084174da11ee1962e004ba4951f1f14b/lib/dpl/provider/biicode.rb#L11) the biicode APT installation script, but this assumes that `sudo` is available in the VM.

The result is that the installation fails.

**Comment by BanzaiMan** [comment]
We are using the official installation script from biicode, which requires `sudo`. Unless biicode can provide a way without (and neither http://docs.biicode.com/c++/installation.html#alternative-install-debian nor https://www.biicode.com/downloads shows a way), I am afraid there is not much we can do.

I've documented the requirement in https://github.com/travis-ci/dpl#biicode and http://docs.travis-ci.com/user/deployment/biicode/

**Comment by smspillaz** [comment]
For the record, I've worked around this in my own scripts with (this)[https://github.com/polysquare/polysquare-ci-scripts/blob/master/ciscripts/deploy/bii/deploy.py]. It is possible to install biicode as user - you just need to get the git tarball and put the `bii` script in `PATH`.

**Comment by BanzaiMan** [comment]
@smspillaz Interesting! If you are interested, we can put that in the provider.

**Comment by smspillaz** [comment]
@BanzaiMan hmm, I suppose the approach I've taken is more specific to my own projects. That said, its a matter of just downloading the biicode repositories, using `git submodule` to fetch the submodules, using `pip` to install dependencies and configuring the `bii` executable to point to the downloaded `biicode` installation.

I'm not sure if that really belongs in `dpl` or if it needs to be put in the builder images.

It should also be possible to just grab the [deb](https://s3.amazonaws.com/biibinaries/release/3.3/bii-ubuntu-64_3_3.deb) and extract it somewhere.

**Comment by LB--** [comment]
> It should also be possible to just grab the [deb](https://s3.amazonaws.com/biibinaries/release/3.3/bii-ubuntu-64_3_3.deb) and extract it somewhere.

I managed to do just that:
```sh
mkdir -p ".travis/biicode" && cd ".travis"
wget https://s3.amazonaws.com/biibinaries/release/3.3/bii-ubuntu-64_3_3.deb
dpkg -x bii-ubuntu-64_3_3.deb ./biicode/
cd biicode/opt/biicode
BIIPATH=$(pwd)
export PATH="$BIIPATH:$PATH"
```
Hope this helps anyone with this issue.
