### ISSUE TITLE
Customize Timeout for connecting to Heroku

### ISSUE THREAD

**Issue by danishkhan** [travis-ci/dpl#306]
Being behind a slow proxy means connections can take longer so it be great if [the timeout](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/heroku/generic.rb#L49) could be changed.

**Comment by BanzaiMan** [comment]
How is this behaving right now? What I can read from the code, the current behavior seem to be to wait for the command to finish as long as it takes. The option is not passed to Rendezvous. So we have [Rendezvous's default behavior](https://github.com/heroku/rendezvous.rb/blob/d6f824c2b158f4e38b1f94c3e63de553e28c0c95/lib/rendezvous.rb#L55-L66), which is to pass `nil` to [`IO.select`](http://ruby-doc.org/core-2.2.1/IO.html#method-c-select), which should block IO indefinitely.

**Comment by smholloway** [comment]
I experience a timeout when trying to deploy to Heroku and update the database. I've found [another example with the same error](https://travis-ci.org/moemake/moe_make/builds/49331805). Here's a Travis log dump that might be relevant:

```
travis_fold:end:dpl.3
travis_fold:start:dpl.4
[33mRunning "npm run dropdb"[0m

travis_fold:end:dpl.4
Already up-to-date!
# Not currently on any branch.
nothing to commit (working directory clean)
Dropped refs/stash@{0} (a6404d8bf3a33777b9f2ebe2b4e9e54c056a3eab)
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rendezvous-0.1.2/lib/rendezvous.rb:120:in `rescue in socket': Rendezvous::Errors::ConnectionTimeout (Rendezvous::Errors::ConnectionTimeout)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rendezvous-0.1.2/lib/rendezvous.rb:87:in `socket'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rendezvous-0.1.2/lib/rendezvous.rb:52:in `start'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rendezvous-0.1.2/lib/rendezvous.rb:28:in `start'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider/heroku/generic.rb:49:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider.rb:138:in `block (2 levels) in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider.rb:138:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider.rb:134:in `each'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider.rb:134:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider/heroku/generic.rb:57:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

I interpret the stacktrace as Travis running a command like `heroku run npm run dropdb` (except through a gem rather than command line), which times out after 120 seconds. I'm new to the codebases so I could be missing something -- @BanzaiMan what do you make of it?

Strangely, it seems that in the project I've linked their builds later worked, as in https://travis-ci.org/moemake/moe_make/builds/49332026.

**Comment by danishkhan** [comment]
@BanzaiMan what are your thoughts on Wes's [reply](https://github.com/heroku/rendezvous.rb/issues/8#issuecomment-148400024)?
