### ISSUE TITLE
Check for cloud foundry

### ISSUE THREAD

**Issue by jcscottiii** [travis-ci/dpl#308]
#294 fixed #261 however it assumes you must have a manifest file named manifest.yml in this line:
https://github.com/travis-ci/dpl/blob/3a2cce39305c531cfbbf0274f29809699bd91f16/lib/dpl/provider/cloud_foundry.rb#L17

If a travis.yml file specifies a "manifest" file, regardless of it's name, the repository must have a manifest.yml or travis will fail. A quick fix would be to have a empty file.

A patch fix should check for the manifest variable instead of the hardcoded manifest.yml

**Comment by BanzaiMan** [comment]
Please test the fix with `edge: true`:

```yaml
deploy:
  provider: cloudfoundry
  edge: true
  ⋮
```
