### ISSUE TITLE
Cannot use encrypted password with pypi provider

### ISSUE THREAD

**Issue by cotsog** [travis-ci/dpl#310]
A customer reported he could not use an encrypted password with `dpl --provider=pypi`.

He mentioned:
> However, I have to use an unencrypted password.
I’ve run “travis setup pypi” and if I say encrypted=yes, I get authorization error on my PyPI server.

[Reference](https://secure.helpscout.net/conversation/111728724/18927/)

**Comment by BanzaiMan** [comment]
I don't think this is an issue with dpl. Either the credentials were incorrectly encrypted, or the provided password is incorrect.
