### ISSUE TITLE
Release already_exists error kills deploy [releases (Github Releases)]

### ISSUE THREAD

**Issue by ZJ** [travis-ci/dpl#312]
When using the releases deployment via travis.org, I got an error raised from Octokit about the release already existsing. I had set up three parallel jobs each trying to deploy to the tag, so I suspect this was a race condition between them (two trying to create a release simultaneously).

Is it necessary to let this particular error kill the deployment?  It seems like if you try to create the release and it turns out it is there, you should go on your way, only stopping if pushing a file also fails.

Line 99 of [releases.rb](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/releases.rb) seems to be the spot to do something, if anything.

Relevant part of the build log:

    No stash found.
    /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.0.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/ZJ/arbWaveCom/releases: 422 - Validation Failed (Octokit::UnprocessableEntity)
    Error summary:
      resource: Release
      code: already_exists
      field: tag_name // See: https://developer.github.com/v3/repos/releases/#create-a-release
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.0.1/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.0.1/lib/octokit/middleware/follow_redirects.rb:61:in `call'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.0.1/lib/octokit/connection.rb:154:in `request'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.0.1/lib/octokit/connection.rb:28:in `post'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.0.1/lib/octokit/client/releases.rb:32:in `create_release'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.18/lib/dpl/provider/releases.rb:99:in `push_app'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.18/lib/dpl/provider.rb:141:in `block in deploy'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.18/lib/dpl/cli.rb:41:in `fold'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.18/lib/dpl/provider.rb:141:in `deploy'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.18/lib/dpl/cli.rb:32:in `run'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.18/lib/dpl/cli.rb:7:in `run'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.18/bin/dpl:5:in `<top (required)>'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
    	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
    failed to deploy

**Comment by BanzaiMan** [comment]
Since you have 3 deployments happening from the same build, the race condition is a very plausible explanation. Please add `on` condition (http://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A) to have exactly one job run the deployment.

I'm closing this for now.
