### ISSUE TITLE
Issue deploying to cloud foundry

### ISSUE THREAD

**Issue by jsloyer** [travis-ci/dpl#320]
Hello,  I am trying to deploy my app to Cloud Foundry with travis and the job is exiting immediately with the following.

Fetching: dpl-1.7.21.travis.970.4.gem (100%)
Successfully installed dpl-1.7.21.travis.970.4
1 gem installed
0.52s
dpl.1
Installing deploy dependencies
dpl.2
Preparing deploy
sudo: must be setuid root
dpl.3
Deploying application
Done. Your build exited with 0.

The travis job is here https://travis-ci.org/IBM-Bluemix/cf-deployment-tracker-service

My .travis.yml file is here https://github.com/IBM-Bluemix/cf-deployment-tracker-service/blob/master/.travis.yml.

Any ideas?

**Comment by BanzaiMan** [comment]
https://travis-ci.org/IBM-Bluemix/cf-deployment-tracker-service/builds/77517701#L170 shows that the provider assumes the availability of `sudo`. Try adding `sudo: required` to the top level of your `.travis.yml`.

**Comment by jsloyer** [comment]
That fixed it, marking this as closed.
