### ISSUE TITLE
 uninitialized constant Aws (NameError)

### ISSUE THREAD

**Issue by tiborhencz** [travis-ci/dpl#325]
getting this on deploy:
```/Users/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.0/lib/dpl/provider/s3.rb:74:in `rescue in deploy': uninitialized constant Aws (NameError)
	from /Users/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.0/lib/dpl/provider/s3.rb:73:in `deploy'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.0/lib/dpl/cli.rb:32:in `run'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.0/lib/dpl/cli.rb:7:in `run'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.0/bin/dpl:5:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /Users/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'```

probably related to #246

**Comment by orktes** [comment]
Some extra information:

```
os: osx
osx_image: beta-xcode6.3
```

Thanks!

**Comment by BanzaiMan** [comment]
Thanks for the reports. I've reproduced the problem and identified the cause. A fix will be out shortly.
