### ISSUE TITLE
pypi deployment error: invalid option "--password="

### ISSUE THREAD

**Issue by drivard** [travis-ci/dpl#327]
I am trying to setup the deployment to pypi but I get an error after the test is build.
My travis-ci file is here:

https://github.com/EnlightNS/enlightns-cli/blob/master/.travis.yml

I used the setup pypi command line which generated the section in my ```.travis.yml``` file.

```travis setup pypi```

The build failure is here:

https://travis-ci.org/EnlightNS/enlightns-cli/jobs/78112477

The error is this one here:

	Fetching: dpl-1.7.21.gem (100%)
	Successfully installed dpl-1.7.21
	1 gem installed
	invalid option "--password="
	failed to deploy

I can't figure out what I am doing wrong.

Regards

**Comment by drivard** [comment]
latest build tried with ```all_branches: true```

https://travis-ci.org/EnlightNS/enlightns-cli/jobs/78682258

**Comment by BanzaiMan** [comment]
This indicates that we passed an empty string to `--password=`, probably because there was a problem with the encrypted password.

**Comment by BanzaiMan** [comment]
Could you try `travis encrypt -r EnlightNS/enlightns-cli`?

**Comment by drivard** [comment]
I tried it here: https://travis-ci.org/EnlightNS/enlightns-cli/jobs/78692440

the updated travis file: https://github.com/EnlightNS/enlightns-cli/blob/master/.travis.yml

but again: 

```The command "make test" exited with 0.
dpl.0
Fetching: dpl-1.8.1.gem (100%)
Successfully installed dpl-1.8.1
1 gem installed
invalid option "--password="
failed to deploy```

**Comment by drivard** [comment]
Tell me when we encrypt the password it tells to do CTRL+D which never work until I do an ENTER first.
So I have to enter the password then press ENTER then do CTRL+D

is it the right behavior?

**Comment by BanzaiMan** [comment]
Does your password have special characters? If so, bash might be interpreting it in an unexpected way. http://docs.travis-ci.com/user/encryption-keys/#Note-on-escaping-certain-symbols

**Comment by drivard** [comment]
you saw right, I changed the password I have another error but first I have to understand it.

thanks
