### ISSUE TITLE
Update docs for deploying on Bintray - no mention about 'override' switch

### ISSUE THREAD

**Issue by RippeR37** [travis-ci/dpl#330]
There is no mention on your [docs](http://docs.travis-ci.com/user/deployment/bintray/) on how to set 'override' switch when deploying files on [Bintray](https://bintray.com/). It took me some considerable amount of time to read though [bintray provider script](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/bintray.rb) to find out that what i need is something like that:

```
{
    "package": { /* ... */ },
    "version": { /* ... */ },
    "files": 
    [
        { 
            /* ... */
            "matrixParams": { "override": 1 } /* those files will overwrite already existing ones */
        },
        { 
            /* ... */
            "matrixParams": { "override": 0 } /* default, those files will not (their upload will fail, job will not) */
        }
    ],
    "publish": true
}
```

It might be good idea to update your docs and add info about that switch, as it's rather useful feature.

**Comment by chrisdembia** [comment]
+1

**Comment by barend** [comment]
Thanks @RippeR37, you've saved me a lot of time figuring that one out. I've included this information in https://github.com/travis-ci/docs-travis-ci-com/pull/481/.

**Comment by BanzaiMan** [comment]
Thanks for the information. We welcome your PR!

**Comment by barend** [comment]
@BanzaiMan https://github.com/travis-ci/docs-travis-ci-com/pull/481/
