### ISSUE TITLE
pypi provider should only optionally upload docs to pypi

### ISSUE THREAD

**Issue by cjw296** [travis-ci/dpl#334]
Taking https://travis-ci.org/Simplistix/testfixtures/jobs/80458606 as an example, my project, like many others, has its documentation hosted on readthedocs.org.

Having moved to Travis for building releases, I find that broken versions of the project docs now appears on pythonhosted.org. I'll have to try and work around this, but please can you provide an option for upload_docs to be disabled?

```
upload_docs: true
```

...defaulting to false, perhaps?

**Comment by cjw296** [comment]
@dstufft - out of curiousity, does "python setup.py upload_docs" have the same security problems that "python setup.py register" does?

**Comment by dstufft** [comment]
Yes-ish.

It's security depends on whether or not ``httplib.HTTPSConnection`` validates TLS, which it only does in 2.7.10 and 3.4+, however unlike ``setup.py upload`` it doesn't force you to sometimes upload with Python's less than that, so you can ensure that you only ever use it with a new enough Python (but it's unlikely that everyone will do this). It's default repository url uses the same scheme as ``upload`` and ``register`` so it wouldn't have switched from http to https until those did either.

In addition, it's likely the ability to upload docs is going to go away at some point in the near-ish future (months, not years or weeks).

**Comment by yoavram** [comment]
+1

**Comment by jacobbridges** [comment]
@cjw296 Did you manage to get travis-ci to deploy to PyPi? I've been trying all day and I keep getting stuck on the following error:

```
error: no files found in upload directory 'build/docs'
```

https://travis-ci.org/jacobbridges/daybreak-py/jobs/85973571

**Comment by cjw296** [comment]
@jacobbridges - actually, you'll see if you look more closely in your log that your tarball has been deployed to PyPI just fine and it's only the messy log messages that are a remaining problem.

**Comment by cjw296** [comment]
Actually, your problem is this:

HTTPError: 403 Client Error: You are not allowed to edit 'daybreak' package information for url: https://pypi.python.org/pypi

**Comment by jacobbridges** [comment]
Thank you for the response. I don't know how to solve this error just yet--but at least it is not the documentation issue.

**Comment by codingjoe** [comment]
I'm seeing this on all my repos now:
```
error: no files found in upload directory 'build/docs'
```
:/

**Comment by jezdez** [comment]
FWIW, there is #334 that just needs another pass

**Comment by lukeyeager** [comment]
> FWIW, there is #334 that just needs another pass

Make that https://github.com/travis-ci/dpl/pull/349
