### ISSUE TITLE
GitHub Enterprise support

### ISSUE THREAD

**Issue by ole-lilienthal** [travis-ci/dpl#344]
Hi Guys,

I would love to use your tool in our corporate environment. However, we are running our own github enterprise installation. This seems not to be supported right now if I see that right: https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/releases.rb#L87

I already set the GITHUB_API env in the travis config which could be used to determine which github api should be used.

Keep up the good work!

**Comment by joshk** [comment]
That is a great idea!

@BanzaiMan could you look at adding this?

@ole-lilienthal if you email enterprise@travis-ci.com we can give you information on Travis CI Enterprise

**Comment by ole-lilienthal** [comment]
Actually we are already using Travis CI Enterprise. Quick google on my name will help you with the company ;)

**Comment by geekflyer** [comment]
@joshk  What is the status on this issue? Basically we want to publish releases to Github Enterprise via Travis Enterprise. After a bit of try and error it seems Travis Enterprise always attempts to connect to the public Github instead of it's linked GH Enterprise instance.

**Comment by joshk** [comment]
It is being actively worked on at the moment. There is a PR which
@BanzaiMan is tweaking and perfecting as I type.

**Comment by BanzaiMan** [comment]
Hello! It is true that I'm working on a PR.

@ole-lilienthal @geekflyer There are two possible ways to go forward.

1. The first is using `$OCTOKIT_API_ENDPOINT`. https://github.com/octokit/octokit.rb#using-env-variables indicates that you can point this env var to your GE installation to get the releases working. (Our current code should be able to cope with this.)
1. The second is my testing branch. To use this, set up the deployment as follows:
```yaml
deploy:
  provider: releases
  edge:
    branch: releases-enterprise
  ⋮ # the rest
```
be sure to **not** set `$OCTOKIT_API_ENDPOINT` in this case.

If the first option is viable, I think it is preferable.

**Comment by geekflyer** [comment]
@BanzaiMan The first solution of setting `$OCTOKIT_API_ENDPOINT` seems to have the desired effect. However release upload still fails since our gh enterprise uses a self signed cert and the gh release provider doesn't trust it. Actually our gh enterprise and travis enterprise instance are both signed by the same (self issued) root cert. So the releases provider should ideally extract the public key from the *global* travis enterprise trust store and copy it to the trust store of the build container.

Is there meanwhile a workaround to add the public key to the build container truststore (via env vars or before_install in `.travis.yml`) ?

Here's the error log:

```sh
Preparing deploy
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:800:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:800:in `block in connect'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:800:in `connect'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:745:in `start'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1285:in `request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1027:in `get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/connection.rb:19:in `get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/client/users.rb:34:in `user'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider/releases.rb:43:in `user'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider/releases.rb:68:in `setup_auth'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider/releases.rb:72:in `check_auth'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider.rb:133:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider.rb:132:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by BanzaiMan** [comment]
Perhaps we can turn off certificate check if `$OCTOKIT_API_ENDPOINT` is set (or under some other trustworthy circumstances).

**Comment by BanzaiMan** [comment]
@geekflyer https://github.com/octokit/octokit.rb/issues/718#issuecomment-180891859

> You can install the single self signed certificate on the client machine as trusted root certificate.
> 
> Or you can create your own certificate authority, you would then need to install the single Root CA certificate on the machine(s), and going forward any certificates signed by your CA would be accepted.

**Comment by BanzaiMan** [comment]
This has been documented. https://docs.travis-ci.com/user/deployment/releases#Deploying-to-GitHub-Enterprise

I think we can close this now.
