### ISSUE TITLE
Bintray provider assumes regex contains `(`

### ISSUE THREAD

**Issue by dnephin** [travis-ci/dpl#345]
https://github.com/travis-ci/dpl/blob/365d9f85df1f2730fd7bd6cd75fd69af9fa2c1f6/lib/dpl/provider/bintray.rb#L366-L377

Using `"includePattern": "/dist/.*"` it will raise a warning about the path not existing, even if the path does exist.

**Comment by EvanKrall** [comment]
The docs mention "Note: Regular expressions defined as part of the includePattern and excludePattern properties must be wrapped with brackets."
