### ISSUE TITLE
Public key permission denied on deploy to Deis

### ISSUE THREAD

**Issue by daanemanz** [travis-ci/dpl#352]
When deploying an application to Deis, the Deis platform rejects the key that's generated by `dpl` during the deploy phase.

Running Deis 1.11.1, please see the deploy log below:

```
Installing deploy dependencies
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1800k  100 1800k    0     0  80349      0  0:00:22  0:00:22 --:--:-- 69365
Verifying archive integrity... All good.
Uncompressing Deis CLI  100%  
deis is in the current directory. Please
move deis to a directory in your search PATH.
See http://docs.deis.io/ for documentation.

Preparing deploy
Logged in as ci
=== example-api Application
updated:  2015-10-16T15:29:32UTC
uuid:     3713968d-2fa7-4372-99ed-c64301150683
created:  2015-10-16T14:53:08UTC
url:      example-api.example.com
owner:    ci
id:       example-api
=== example-api Processes
--- web:
web.1 up (v4)
=== example-api Domains
Generating public/private rsa key pair.
Your identification has been saved in .dpl/id_rsa.
Your public key has been saved in .dpl/id_rsa.pub.
The key fingerprint is:
a8:41:46:ee:82:67:8d:50:76:eb:d9:44:1a:bb:91:bb testing-worker-linux-docker-9a70e625-3370-linux-1
The key's randomart image is:
+--[ RSA 2048]----+
|  o + .          |
| o + B           |
|.   X .          |
| o B B .         |
|. = O o S        |
| o . +           |
|    E            |
|                 |
|                 |
+-----------------+
Uploading id_rsa.pub to deis... done
Git remote deis added
Saved working directory and index state WIP on (no branch): <commit>
HEAD is now at <commit>

Deploying application
Warning: Permanently added '[deis.example.com]:2222' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Removing testing-worker-linux-docker-9a70e625-3370-linux-1 SSH Key... done
Already up-to-date!
# HEAD detached at <commit>
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#   .dpl/
#   deis
#
nothing added to commit but untracked files present (use "git add" to track)
Dropped refs/stash@{0} (<commit>)
Deploying application failed.
failed to deploy
```

Any thoughts?

**Comment by daanemanz** [comment]
One more thing to add: this does work when I run `dpl` from a local command line.

**Comment by glogiotatidis** [comment]
I'm facing the same issue.

@daanemanz do you have a workaround you can share?

**Comment by BanzaiMan** [comment]
Does this happen consistently?

I am quite unsure how this is happening. The series of `./deis` commands we run are returning zero exit status, so I think they are successful. If the problem is consistent, I can inject some debug flags to see what might be happening.

**Comment by glogiotatidis** [comment]
@BanzaiMan yes, it happens consistently for me. I never managed to deploy using deis dpl provider.

**Comment by BanzaiMan** [comment]
@glogiotatidis Can you deploy your app from your development machine?

The ssh key that we generate and use are RSA. Does the remote host accept that? @daanemanz's output has:

```
Warning: Permanently added '[deis.example.com]:2222' (ECDSA) to the list of known hosts.
```

Is it possible that we need to generate ECDSA key instead? (Which is a bit curious, because this key type is not currently supported on OS X.)

**Comment by BanzaiMan** [comment]
For the record, `git` will be run with this script:

```shell
#!/bin/sh
exec ssh -o StrictHostKeychecking=no -o CheckHostIP=no -o UserKnownHostsFile=/dev/null -i .dpl/id_rsa \"$@\"
```

**Comment by benhorowitz** [comment]
I'm working through this with @BanzaiMan, commenting here so I get updates.

**Comment by BanzaiMan** [comment]
I've pushed a debug branch that adds the verbose flag to `git push` in question. I am not sure how useful that is, but you can try it with:

```yaml
deploy:
  provider: deis
  edge:
    branch: debug-deis
  verbose: true
  ⋮
```

**Comment by benhorowitz** [comment]
I just tried to run that on travis and got:

`Skipping a deployment with the deis provider because this branch is not permitted`

**Comment by BanzaiMan** [comment]
@benhorowitz Oh, that's right. I think `branch` gets confused. Let's try:

```yaml
deploy:
  provider: deis
  edge: true
  verbose: true
  ⋮
```

instead.

**Comment by benhorowitz** [comment]
Same result :(

`Generating public/private rsa key pair.
Your identification has been saved in .dpl/id_rsa.
Your public key has been saved in .dpl/id_rsa.pub.
The key fingerprint is:
6f:cc:f9:04:dd:26:9b:95:a1:98:b7:da:c2:a9:f1:d8 testing-gce-d89858d3-915c-4b8a-9034-1d94d809ee82
The key's randomart image is:
+--[ RSA 2048]----+
|                 |
|                 |
|              .  |
|           + o o |
|        S + = =  |
|         + + B   |
|        ..*.=    |
|         *+=     |
|        o.E.o    |
+-----------------+
Uploading id_rsa.pub to deis... done
Git remote deis added
Saved working directory and index state WIP on (no branch): 3a58da6 Debugging travis
HEAD is now at 3a58da6 Debugging travis

Deploying application
Pushing to ssh://git@deis.ngra.ps.nginxlab.com:2222/album-manager.git
Warning: Permanently added '[deis.ngra.ps.nginxlab.com]:2222' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Removing testing-gce-d89858d3-915c-4b8a-9034-1d94d809ee82 SSH Key... done
Already up-to-date!
HEAD detached at 3a58da6
nothing to commit, working directory clean
Dropped refs/stash@{0} (4d43017cbf0ac8f9fdce2ea689c84bf03154eb55)
Deploying application failed.
failed to deploy`

**Comment by BanzaiMan** [comment]
Thanks for testing. I will try setting up an account, and try more debugging for a shorter feedback loop.

**Comment by BanzaiMan** [comment]
I've updated the `edge` version again. It works as before. This time, `GIT_SSH` script is updated to include `exec ssh -v …` (as opposed to `exec ssh …`). Do bear in mind that this has a potential to leak sensitive information.

**Comment by mattk42** [comment]
I was running into this issue yesterday and ended up just moving to a script for now.

Initially I just used a key that was already set up, but then moved to the same method that dpl uses where I log in and set up a new ket. I hit the same issue in my script as mentioned here. It turned out that it just takes a few seconds for the key to get completely setup in deis, so I had to add a sleep for now just to give that time to happen.

**Comment by groovecoder** [comment]
:+1: for this issue - is there any updated on #402 yet? I'd love to use the built-in deis deploy without having to do a custom script.

**Comment by glogiotatidis** [comment]
> :+1: for this issue - is there any updated on #402 yet? I'd love to use the built-in deis deploy without having to do a custom script.

@groovecoder just fyi we worked around this problem using scripts in [basket](https://github.com/mozilla/basket/blob/master/bin/deploy.sh) and [lumbergh](https://github.com/mozilla/lumbergh/blob/master/bin/deploy-travis.sh) which work without problems. We added NR notifications to make it even better.
