### ISSUE TITLE
Windows newlines cause the deploy script to fail 

### ISSUE THREAD

**Issue by yoavram** [travis-ci/dpl#353]
I had a deploy script written as a bash script.
I'm working on Windows.
I got an error with status 127.
I moved the script code to the after_success section and everything worked.
Then I moved the script call to after_success and I got a proper error message about the newlines.
Finally I ran the script file through dos2unix and then the deploy succeeded.

So there are two problems:
- windows newlines cause the deploy to fail - can travis output a warning or at least add a note about this in the docs? 
- error generated by the script were hidden behind a cryptic "status 127" error message. any way to print the actual error messages to the travis log?

**Comment by BanzaiMan** [comment]
Thanks for opening this issue. I'm not sure how we can mitigate the problem, but it is probably a good idea to deal with newlines on your development machine: https://help.github.com/articles/dealing-with-line-endings/#platform-windows

**Comment by yoavram** [comment]
I think that part of the problem is that the script provider gives very little output on what caused an error, beyond the status code. Even if you don't change the code to give more output, you could change the docs to add a note like this: "in case of an error during the script provider deploy, you should run your script from the after_success section in order to see a more detailed description of the error". Also, you could add a warning in the docs (if not in the code itself) about "\r" in scripts that are uploaded from windows. And give the link you just gave me as "further instructions". 
That could have saved me ~4 hours 2 days ago...
