### ISSUE TITLE
Travis CloudFoundry Deployment with setting secret env variables

### ISSUE THREAD

**Issue by gosua** [travis-ci/dpl#359]
I can't find the possibility to set some (encrypted) environment variables for the Cloud Foundry deployment option of Travis. 

The current workaround I follow is posted here: http://stackoverflow.com/questions/33283769/deploy-with-travis-to-cf-with-secret-environment-variables.

**Comment by BanzaiMan** [comment]
Could you show what you've tried (and relevant build log URLs)?

**Comment by gosua** [comment]
My issue is more like an enhancement request for the Cloud Foundry deployment.

It would be neat to have the possibility to define and encrypt environment variables that will be set later on by your Cloud Foundry deployment functionality.

Maybe an example helps clarifying that:

    deploy:
        edge: true
        provider: cloudfoundry
        username: hulk_hogan@example.com
        password: supersecretpassword
        api: https://api.run.pivotal.io
        organization: myawesomeorganization
        space: staging
        env:
        - secure: djsakldjsadlk213jlkjs= #env variable that will be set within the DEA
