### ISSUE TITLE
Having difficulty with Azure deployment

### ISSUE THREAD

**Issue by jenyayel** [travis-ci/dpl#360]
[Here is](https://github.com/Enttoi/enttoi-ui-web/blob/master/.travis.yml) my yml file. I spent quit a lot time on it - it seems that the parameter skip_cleanup in deploy section is ignored, as result all artifacts produced during build are not deployed. 

I tried deploying via script by pushing to remote and it is working (/dist presented in source and destination).

**Comment by BanzaiMan** [comment]
I don't see any cleanup happening in https://travis-ci.org/Enttoi/enttoi-ui-web/builds/91365052.

**Comment by jenyayel** [comment]
You are right, but on another hand artifacts don't pushed in deploy. So may be I was misleading with the title of issue, and the problem is in deploy itself. I just hoping I miss-configured something, but ,man, I tried every possible way.

**Comment by BanzaiMan** [comment]
I'm sorry to say, but I don't know how to troubleshoot this. Perhaps @felixrieseberg, who implemented Azure support, may have insight.

**Comment by felixrieseberg** [comment]
Yup, that seems to be a solid bug (I simply forgot to add to respect `skip_cleanup`). Fix incoming.

**Comment by jenyayel** [comment]
Thanks @felixrieseberg!
