### ISSUE TITLE
"Installing deploy dependencies" fails

### ISSUE THREAD

**Issue by nripendra** [travis-ci/dpl#366]
I'm trying to deploy nodejs project to github release but it fails when executing "installing deploy dependencies" step.

The exact reason for error is this:

```
Fetching: mime-types-data-3.2015.1120.gem (100%)
ERROR:  Error installing mime-types:
	mime-types-data requires Ruby version >= 2.0.
```
I even tried to install ruby 2.0.0 at before_install, as suggested [here](http://stackoverflow.com/a/30261239/605113). It seems to be installing the desired ruby (according to the build log) but the error still persists.

build log [here](https://travis-ci.org/nripendra/fb-messenger/builds/92508910#L1625)

**Comment by justinhilles** [comment]
+1 

Installing deploy dependencies
Fetching: jmespath-1.1.3.gem (100%)
Successfully installed jmespath-1.1.3
Fetching: aws-sdk-core-2.2.1.gem (100%)
Successfully installed aws-sdk-core-2.2.1
Fetching: aws-sdk-resources-2.2.1.gem (100%)
Successfully installed aws-sdk-resources-2.2.1
Fetching: aws-sdk-2.2.1.gem (100%)
Successfully installed aws-sdk-2.2.1
4 gems installed
Fetching: mime-types-data-3.2015.1120.gem (100%)
ERROR:  Error installing mime-types:
	mime-types-data requires Ruby version >= 2.0.

**Comment by neoascetic** [comment]
+1

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. Please use https://github.com/travis-ci/travis-ci/issues/5145 for further discussion.
