### ISSUE TITLE
CloudFiles provider missing gem

### ISSUE THREAD

**Issue by rgbkrk** [travis-ci/dpl#369]
```
Deploying application
[fog][WARNING] 'mime-types' missing, please install and try again.
failed to deploy
```

**Comment by BanzaiMan** [comment]
Could you point to a build log URL that shows this problem?

**Comment by rgbkrk** [comment]
https://travis-ci.org/getcarina/dvm/builds/92976248

**Comment by BanzaiMan** [comment]
Thanks. I'll close this as a duplicate of https://github.com/travis-ci/travis-ci/issues/5165 (in the main issues repo).
