### ISSUE TITLE
AWS Access Key / Secret on Elastic Beanstalk

### ISSUE THREAD

**Issue by geovanisouza92** [travis-ci/dpl#376]
Hi,

I noticed that both [AWS CodeDeploy](https://github.com/travis-ci/dpl#aws-codedeploy) and [AWS OpsWorks](https://github.com/travis-ci/dpl#opsworks) support the environment variables ```AWS_ACCESS_KEY_ID``` and ```AWS_SECRET_ACCESS_KEY```, but [Elastic Beanstalk](https://github.com/travis-ci/dpl#elastic-beanstalk) (at least on documentation) doesn't have that support.

Is this just a documentation issue or the EB isn't supported yet?

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/dpl/blob/7ad055003cf1ffaf09ce5302dd55d29eb4643b11/lib/dpl/provider/elastic_beanstalk.rb#L15-L25 It is just documentation.

**Comment by geovanisouza92** [comment]
Nice!
