### ISSUE TITLE
Add support for Atom Package Manager?

### ISSUE THREAD

**Issue by keplersj** [travis-ci/dpl#378]
Would it be feasible to add support for the [Atom](https://atom.io) Package Manager? It seems to be fairly similar to Node Package Manager, in fact under the hood APM uses NPM for dependency management.

There are a lot of Atom packages using Travis for testing right now, I think it'd be awesome to use Travis to deploy new versions as well.

**Comment by SpainTrain** [comment]
@kepler0 Can you set the env var `ATOM_ACCESS_TOKEN` to your access token via web ui for the project, then create a deploy step in the `.travis.yml` that runs `apm publish <bumptype>? (https://docs.travis-ci.com/user/deployment/)

**Comment by SpainTrain** [comment]
Agree that native support like with npm would be fantastic!

**Comment by joshk** [comment]
I'd love to have native support be built into Travis. We would be happy to provide advice on how this can be done if someone wants to help contribute?

**Comment by kepler0** [comment]
I'm familiar with Ruby. Could you give me some pointers on this API, and how to test it?

**Comment by BanzaiMan** [comment]
@kepler0 Look inside `lib/dpl/provider` directory for examples.

**Comment by kepler0** [comment]
There is working code for this. Implemented with #401 and demoed in [linter-clang](https://github.com/AtomLinter/linter-clang/blob/master/.travis.yml#L33-L41).

**Comment by trevordmiller** [comment]
I agree that native support would be useful. I don't have time at the moment to take this on but if someone else does or could merge the efforts already completed in the referenced forks that would be awesome :)

**Comment by keplersj** [comment]
For Google Searchers from the future, I was able to implement this sort of functionality outside of `dpl` using [`semantic-release`](https://github.com/semantic-release/semantic-release) and [`@semantic-release/apm-config`](https://github.com/semantic-release/apm-config). I recommend going this route if you're looking for Continuous Deployment with APM.

[![Relevant xkcd](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)](https://xkcd.com/979/)
