### ISSUE TITLE
Rubygems deploying without erroring

### ISSUE THREAD

**Issue by BrianBerzins** [travis-ci/dpl#387]
The rubygems provider is returning a successful exit code `0` when using the rubygems provider when the gem upload is actually failing.

It isn't clear to me that is a problem with `dpl` or if it's actually a problem with the underlying `gem push` command.

My setup includes using an internal rubygems repository (hosted in artifactory). Artifactory is returning a 4xx block HTTP status code (correctly failing in this case), so either dpl or the underlying gem push command is swallowing the error and propagating a successful exit code.

**Comment by BanzaiMan** [comment]
This is probably a variation of https://github.com/travis-ci/travis-ci/issues/1574. Currently there is no check about whether or not deployment was a success. Please subscribe to the issue above.
