### ISSUE TITLE
RVM warning about PATH

### ISSUE THREAD

**Issue by zer0main** [travis-ci/dpl#388]
When Travis reaches the deploy stage of build, the following warning is printed:

```
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
```

I don't change PATH so the problem seems to be on your side.
Link to build log: https://travis-ci.org/zer0main/battleship/jobs/101417059

**Comment by BanzaiMan** [comment]
This is not an issue with dpl. (I understand that this is not obvious at first.) Please open a new one in https://github.com/travis-ci/travis-ci/issues/new if you can't find an existing one.
