### ISSUE TITLE
Tag flag support for NPM

### ISSUE THREAD

**Issue by Etzos** [travis-ci/dpl#415]
The `npm publish` command supports a flag, `--tag` which allows the published package to have a specific tag. This is incredibly useful for automatically deploying development builds to npm without forcing a testing version on people. If there was some way to specify a value for this tag in the deployment that would be helpful.

**Comment by mamont** [comment]
Submitted a pull request which is trying to resolve that: https://github.com/travis-ci/dpl/pull/535

**Comment by astorije** [comment]
This is now available (see https://docs.travis-ci.com/user/deployment/npm/#Tagging-releases) so I think this can be closed.

@BanzaiMan, is it possible to give it a conditional name? What I am essentially trying to achieve is:

```yml
tag: ("next" if tag is pre-release (i.e. contains "pre" or "rc" in our case); "latest" otherwise
```

(Most npm package publish with the `next` dist-tag when publishing a pre-release)

**Comment by BanzaiMan** [comment]
Indeed, this can be closed. Thanks for the ping.

@astorije For what you are describing, I think it can be computed. For example, you can define a bash function `npm_tag`:

```yaml
before_deploy: |
  function npm_tag() {
    : # DO STUFF
  }

deploy:
  provider: npm
  tag: $(npm_tag)
  ⋮
```

I have not tested this, though, so please keep that in mind.

**Comment by astorije** [comment]
Thanks @BanzaiMan, I'm giving a shot at this in https://github.com/thelounge/lounge/pull/2080, we'll see how things go!

**Comment by jonnyreeves** [comment]
Sorry to raise this from the dead, but it would be awesome if the [relevant documentation](https://docs.travis-ci.com/user/deployment/npm/) could be updated to reference this new option as it took me a little bit of googling to find.

Thanks!

**Comment by BanzaiMan** [comment]
@jonnyreeves I'm sorry to hear that you had to spend some time to figure this out, but your suggestions are welcome! Please use the "Improve this page on GitHub" link at the upper right corner of the page to open a PR. Thank you!

**Comment by bendog** [comment]
So I'm brand new to Travis, but have used other CI tools, it would be really helpful for people like me if @BanzaiMan 's example code could be confirmed and fleshed out, i'm pretty sure this isn't a edge case, and there'll be more people like me around who don't understand the Travis way of doing things enough to infer what was meant by that example code
