### ISSUE TITLE
Only sync changed files to S3, not reupload everything

### ISSUE THREAD

**Issue by palewire** [travis-ci/dpl#422]
Hello. I'm a Travis subscriber. As part of my pre_deploy routine, a static site is built as flat HTML files and then synced by Travis' provider to an S3 bucket.

What I've noticed that the 100% of the files are reuploaded with every build, despite the fact that only one or two have changed since the previous build.

Is there a way to have it only upload those that have changed? This would greatly increase the speed of my builds and make Travis a better service for me.

**Comment by alma-socar** [comment]
I am actually having same issue. Any plan to develop this issue? Or maybe I simply don't know how to do so.

**Comment by yanxianghuang** [comment]
Same problem here, any suggestion?

**Comment by palewire** [comment]
I solved this but giving up on dpl and using other tools to sync.

**Comment by yanxianghuang** [comment]
@palewire I also solved it by using directly 'aws s3 sync'. Is that what you did?

**Comment by palewire** [comment]
I'm using the s3 syncing options of the boto library included django-bakery
http://django-bakery.readthedocs.io/en/latest/

**Comment by yanxianghuang** [comment]
@palewire Thanks for your reply. I will take a lot on that!
