### ISSUE TITLE
Feature Request: Run CLI commands for heroku app

### ISSUE THREAD

**Issue by yashmehrotra** [travis-ci/dpl#429]
An option to execute commands like `heroku run rake db:migrate` etc. would be nice.

Ref: https://devcenter.heroku.com/articles/rake

**Comment by BanzaiMan** [comment]
See https://docs.travis-ci.com/user/deployment/heroku#Running-Commands

**Comment by yashmehrotra** [comment]
@BanzaiMan Hi, I use `dpl` for GitLab CI. So for deployiung my code I use the following command
`dpl --provider=heroku --app=samoza --api-key=$HEROKU_PRODUCTION_API_KEY`

Is there any way I can use dpl for running rake commands or similar? The link you posted is for Travis-CI

**Comment by louim** [comment]
Leaving this here if anyone come googling the same question. To run commands, you would add them like that:

```
dpl --provider=heroku --app=myapp --run='rake db:migrate' --api-key=$HEROKU_PRODUCTION_API_KEY
```
You can run multiple commands by repeating the `--run` flag multiple times

**Comment by yashmehrotra** [comment]
@crazyhalls Have you tried `--run='rake db:create && rake db:migrate && rake db:seed'`

**Comment by crazyhalls** [comment]
@yashmehrotra 

> Running "rake db:create && rake db:migrate && rake db:seed"
> No stash found.
> API request failed.
> Message: Cannot run one-off process at this time. Please try again later.
> Reference: 
> ERROR: Job failed: exit code 1

didn't work either

**Comment by anuj9196** [comment]
`- dpl --provider=heroku --app=koober-production --api-key=$HEROKU_PRODUCTION_API_KEY --run='python src/manage.py migrate && python src/manage.py create_initial_users'`

This is how my `script` command in `.gitlab-ci.yml` file.

`migrate` and `create_initial_users` command is running fine but there is no output on the terminal.

**How can I print the output for the command executed?**
