### ISSUE TITLE
Cloud Foundry Deployment exits with status code 0 even if cf push fails

### ISSUE THREAD

**Issue by amblock** [travis-ci/dpl#441]
If the `cf push` step fails, the exit code should be 1. Currently, this is causing my builds to be marked a success, even if the application fails to deploy.

**Comment by tonydiaz** [comment]
+1

**Comment by jossy** [comment]
+1

**Comment by shawnzhu** [comment]
welcome comment emoji my fix! https://github.com/travis-ci/dpl/issues/591

**Comment by baob** [comment]
We're waiting on a fix for this is there any chance someone can review the PR and merge ?

Or explain what's wrong with the PR so someone could fix ?

Or something   :)

**Comment by jwickens** [comment]
Hi this would be a great fix thanks
