### ISSUE TITLE
OpenShift v2: exits successfully even if deployment has failed

### ISSUE THREAD

**Issue by jpic** [travis-ci/dpl#450]
Hi \o/

I wonder why builds are green when deployment failed. Typical example:
https://travis-ci.org/political-memory/political_memory/builds/124050425#L564

Thanks in advance for answering

Best

**Comment by BanzaiMan** [comment]
Deployment relies on exit status code to determine whether it passed for failed. OpenShift deployment is based on `git`, and if it doesn't differentiate the results, it is not possible to indicate it.

It might be possible to parse the `git` output and deal with failures appropriately.

**Comment by jpic** [comment]
Thanks for your feedback, do you think such output parsing logic should be implemented in every project, or rather in dpl's openshift adapter ?

**Comment by BanzaiMan** [comment]
There is no uniform logic to tell if the deployment succeeded or not, so having it on all provider is not possible.

Also, parsing output makes the provider *very* brittle and couple it to the other end's whim, so I am not going to advocate that route unless it is really the only possible solution.

**Comment by jpic** [comment]
Do you mean that checking for "remote: Deployment completed with status:
failure" or at least even "remote: postreceive failed" in the output would
not be considerable as uniform logic ?

I just checked and indeed git push exits with 0 even if deployment failed
with an output like mentioned above, ending with:

```
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 56e8957f2d5271514600007c (Error activating gear: CLIENT_ERROR:
Failed to execute action hook 'deploy' for 56e8957f2d5271514600007c
application django
remote: #<IO:0x00000002179380>
remote: #<IO:0x00000002179308>
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
```

I'd say at least 4 of these lines here are generic, don't you think ?

The other problem is that travis calls dpl, and users do not have access to
the output in a variable in .travis.yml. Otherwise, i'd be happy to just
grep for "Deployment completed with status: failure" in the output, as you
mentioned.
