### ISSUE TITLE
Update the cloudfoundry tool

### ISSUE THREAD

**Issue by germanattanasio** [travis-ci/dpl#461]
Travis is currently using `cf 6.12.4` which is from Sep 18, 2015. 
Please update it to `cf 6.19.0` which is from Jun 8, 2016.

There are several bug fixes that will be great to have, especially:  https://github.com/cloudfoundry/cli/issues/800 which was fixed in `cf 6.17.0`

**Comment by BanzaiMan** [comment]
We've been using the `latest` release since April 2014. If the versions diverged, I am guessing that it was due to changes in URL upstream.

I'm closing this now, but if this is still a problem, do let us know.
