### ISSUE TITLE
node_modules dir ignored when deploying to Elastic Beanstalk

### ISSUE THREAD

**Issue by nazieb** [travis-ci/dpl#467]
When deploying a nodejs app to AWS Elastic Beanstalk, the `node_modules` directory is always ignored and not uploaded into the zip file. Adding `skip_cleanup` won't work either.

Note that I didn't provide the `zip_file` option and want to upload the contents of the directory as is while also add the `node_modules` directory in the `.gitignore` file.

And when I look at the source code, it turns out the [`files_to_pack` method](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/elastic_beanstalk.rb#L105) which provides the list of files to be included in the zip file is using `git ls-files` command. And the command will only list the files tracked by git, therefore the `node_modules` will always be ignored.

Is there any reason why use that method instead of using `ls` or the one that's used in the [S3 provider](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/s3.rb#L44)? Sorry I'm still noob at Ruby.

**Comment by mediafreakch** [comment]
You could do something like that in your `.travis.yml`:
```
before_deploy:
  - sed -i 's/node_modules//g' .gitignore
  - git add node_modules/
```

This will remove `node_modules` from your .gitignore and add them to the staging area, where it should be picked up by `git ls-files`

**Comment by kauppvi** [comment]
With `eb deploy` you also have to use the `--staged` option (in addition with `git add` mentioned above):
```
eb deploy --staged
```
