### ISSUE TITLE
Twine not installed, PyPI publishing fails.

### ISSUE THREAD

**Issue by bergwerf** [travis-ci/dpl#470]
There is an error while installing python packages: https://travis-ci.org/hermanbergwerf/bashbeautify/builds/141048289#L202. This breaks PyPI uploading: https://travis-ci.org/hermanbergwerf/bashbeautify/builds/141048289#L245. Could it be an issue with root on the container infrastucture?

**Comment by hermanbergwerf** [comment]
https://travis-ci.org/hermanbergwerf/bashbeautify/builds/141854081#L186 Aaaaand fails again. Can you please fix this?

**Comment by BanzaiMan** [comment]
I think there are a couple of issues.

1. You are using Ruby build. This is causing some assumptions that the PyPI providers makes to be violated.
1. PyPI does not appear to be designed for use by any language other than Python when running on containers.

For the former,  please try adding `language: python` to the top level of your `.travis.yml`.

For the latter, you could try adding `sudo: required`. Either way, this needs to be documented.

**Comment by hermanbergwerf** [comment]
Hmm, curious that Travis autodetects Ruby when there are no ruby files in my repo. But I'll add the `language: python` line and try again.

**Comment by BanzaiMan** [comment]
It is not detecting. It is the default in the absence of the `language:` key.
