### ISSUE TITLE
Deploy script provider should redirect stderr and stdout

### ISSUE THREAD

**Issue by destijl** [travis-ci/dpl#477]
I'm using the experimental deploy script provider:
https://docs.travis-ci.com/user/deployment/script

as a workaround for cloud storage deployer problems:
https://github.com/travis-ci/dpl/issues/476

It would be great if it redirected stderr and stdout. I currently have echo statements that never make it to the travis log. So the only result I get is basically success or fail with a fairly meaningless return code. To do any sort of debugging I need to move the script into the main "script" section to see what is happening.

**Comment by BanzaiMan** [comment]
Do you have a build log that shows the problem you are describing here?

**Comment by frank-carnovale** [comment]
I also get this problem.  My 'before_deploy' commands echo no stdout; although if they have a syntax error, I do see the stderr.
The result is as described by destijl above.. Empty log output for that section despite lots of "echo" statements.

**Comment by xunnanxu** [comment]
I believe stdout does work but stderr does not. So right now it just requires the `2&>1` trick.
