### ISSUE TITLE
json-pure causing gem to fail installation

### ISSUE THREAD

**Issue by mattk42** [travis-ci/dpl#480]
> ERROR:  Could not find a valid gem 'json_pure' (>= 0) in any repository
> 
> The command "rvm 1.9.3 --fuzzy do ruby -S gem install dpl-*.gem --local --pre" failed and exited with 2 during .

After merging master in to my custom DPL branch all of my projects are seeing the above error during DPL installation. I had to remove the runtime dependency and the require line in provider.rb to get past this.

**Comment by BanzaiMan** [comment]
Sorry for the troubles. I removed `json_pure` from the list of runtime dependencies with https://github.com/travis-ci/dpl/pull/482. Could you try a new version (1.8.18.travis.1518.4 or later)?

**Comment by mediafreakch** [comment]
I still have the problem with `dpl-1.8.18.travis.1518.4.gem`. It worked 2 days ago.

Working build log:
```
Fetching: json_pure-2.0.1.gem (100%)
Successfully installed json_pure-2.0.1
Fetching: dpl-1.8.18.travis.1496.4.gem (100%)
Successfully installed dpl-1.8.18.travis.1496.4
2 gems installed
``` 

Failing build log:
```
Fetching: dpl-1.8.18.travis.1518.4.gem (100%)
Successfully installed dpl-1.8.18.travis.1518.4
1 gem installed
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- json/pure (LoadError)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18.travis.1518.4/lib/dpl/provider.rb:4:in `<top (required)>'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18.travis.1518.4/lib/dpl/cli.rb:2:in `<top (required)>'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18.travis.1518.4/bin/dpl:4:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
```

**Comment by nilaratna** [comment]
I am seeing this too. CC @icco

**Comment by jsh2134** [comment]
I am also having this issue, starting about 12 hours ago

**Comment by icco** [comment]
The reason @nilaratna and my builds were breaking was due to having `edge: true` in our travis builds, removing that and using the released version and everything worked.

**Comment by BanzaiMan** [comment]
Hmm. I want to get `edge: true` moving. We need this, because without it, the specs fail on Ruby 2.2 and up due to [`TypeError`](https://travis-ci.org/travis-ci/dpl/jobs/139825481#L394). This is important when we move our default Ruby version to something (much) newer than the current 1.9.3.

I'll try other things. Thanks for your patience.

**Comment by icco** [comment]
right, our builds are on a box that uses 1.9.3 no matter what apparently.

**Comment by BanzaiMan** [comment]
OK. Another try at https://travis-ci.org/travis-ci/dpl/builds/146545227. Please try 1.8.18.travis.1527.4 and later.

**Comment by BanzaiMan** [comment]
Has anyone tested this?

**Comment by BanzaiMan** [comment]
I'm closing this optimistically, having run a few "edge" deployments of my own. If you continue to see problems, let me know.
