### ISSUE TITLE
GAE: Update gcloud scripts

### ISSUE THREAD

**Issue by m-messiah** [travis-ci/dpl#498]
Each time I deploy my app into GAE, dpl uses gcloud preview app aommand, and log says
`WARNING: The`gcloud preview app`command group is deprecated; please use the`gcloud app`commands instead.`

Are you planning to update your scripts to correct command/version?

While this warning can be ignored, I get another problem with it, which prevent using deploy at all:

In Go environment, `gcloud preview app` does not use correct `goapp get`, so when I use any external Go imports - they all denied. And compilation fails, while If I run `goapp deploy` in my machine - deploy succeeds.

**Comment by flowlo** [comment]
Just found out about this from #94. I'll take a look soon.
