### ISSUE TITLE
Bintray: misleading documentation about regular expressions

### ISSUE THREAD

**Issue by larsrh** [travis-ci/dpl#507]
The documentation states:

> Note: Regular expressions defined as part of the `includePattern` and `excludePattern` properties must be wrapped with brackets.

One of the examples contains:

> `build/bin(.*)*/(.*\\.gem)`

However, I doubt that this works. The relevant code snippet looks like it just cuts off everything after the first `(` and treats everything before as the path prefix. For the above example, it would look for files below `build/bin`, which may or may not exist (I would expect that it would also look below e.g. `build/bin0`).

``` ruby
def root_path(str)
  index = str.index('(')
  path = nil
  if index.nil? || str.start_with?('(')
    path = str
  else
    ### here ###
    path = str[0, index]
  end

  if !test_mode && !File.exist?(path)
    log "Warning: Path: #{path} does not exist."
    return nil
  end
  return path
end
```

This corroborates my experience with my own deployment setup where I had to fiddle until I arrived at the pattern `modules/cli/target/scala-2.11/(isabellectl-assembly-.*)`.

**Comment by Minikloon** [comment]
I think this is more than the documentation being wrong.

You can't use *only* the version as a capture group for the uploadPattern.
