### ISSUE TITLE
The deprecated heroku-api gem will be shut down on April 15, 2017

### ISSUE THREAD

**Issue by dmcinnes** [travis-ci/dpl#508]
Hello,

I've noticed that this library uses a deprecated version of Heroku's `heroku-api` gem. This gem works against our deprecated version of our API, slated to be shut down on April 15, 2017:
https://devcenter.heroku.com/changelog-items/862

There is a new gem that works against our v3 platform API: 
https://github.com/heroku/platform-api
Or alternatively these calls could be reused without the gem:
https://github.com/travis-ci/dpl/blob/424c7a61c341f184b8aa66df178d4aca31455a6f/lib/dpl/provider/heroku/api.rb#L71-L96
See our platform docs for more information:
https://devcenter.heroku.com/articles/platform-api-reference

**Comment by dmcinnes** [comment]
Just as an additional reminder, the v2 Heroku API will be shut down in less than two months.

**Comment by mvanduijker** [comment]
Deploying to heroku still works for me. Did shutdown of v2 happen? Is dpl compatibel with v3 by accident?

**Comment by afolson** [comment]
I just received a notification about this while trying to do a deploy just now. Looks like it's part of a scheduled brownout with a final sunsetting in June. I don't think it's compatible with v3, I think we all just got lucky with the postponement :P

```
body: "{\"id\":\"gone\",\"error\":\"This version of the API has been Sunset.\\nPlease see https://devcenter.heroku.com/changelog-items/1147 for more information.\\n\"}"
```

**Comment by BanzaiMan** [comment]
1.8.34 has been released. I'm closing this now. For further discussion on this topic, see #640.
