### ISSUE TITLE
S3 upload should not set an empty content-type

### ISSUE THREAD

**Issue by stof** [travis-ci/dpl#519]
When the mime type is not known by the `mime-types` gem, it would be better to set a `application/octet-stream` mime type than an empty string.

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. What are effects of not setting the `Content-Type` header?

**Comment by stof** [comment]
if you don't set it when uploading, I think S3 automatically sets it to ``application/octet-stream`` (which means that browsers will download the file, while an empty content-type gets treated like a text content at least in Firefox and so displayed on screen even when it is not textual)

**Comment by BanzaiMan** [comment]
Please test it with:

```yaml
deploy:
  provider: s3
  edge:
    branch: 's3-content-type'
  ⋮ # rest
```

**Comment by stof** [comment]
Actually, it does not set it to ``application/octet-stream`` (this may be a feature of s3cmd for unknown types).

But omitting the content-type makes the file be downloaded by Firefox instead of being displayed as text as previously (which was very confusing when the file was not a text file). So I would vote +1 on your fix.

**Comment by BanzaiMan** [comment]
@stof @sylveon @peternewman You all have expressed interest in resolving this issue. Could you test the PR one last time, so that we can merge and release the fix?

Thanks.

**Comment by peternewman** [comment]
Not guilty sorry @BanzaiMan aside from pointing out it's a duplicate to try and keep the issue list clean.

**Comment by BanzaiMan** [comment]
@peternewman Sorry for the noise!
