### ISSUE TITLE
ERROR:  Gemspec file not found

### ISSUE THREAD

**Issue by rnelson0** [travis-ci/dpl#523]
We are attempting to set up rubygems autodeploy on [metadata-json-lint](https://github.com/voxpupuli/metadata-json-lint/). When travis runs, it fails to deploy with the error `ERROR:  Gemspec file not found: metadata-json-lint.gemspec`. This file clearly [exists](https://github.com/voxpupuli/metadata-json-lint/blob/6df610045516f48930484eeed698a13396362305/metadata-json-lint.gemspec) and is specified in the [.travis.yml](https://github.com/voxpupuli/metadata-json-lint/blob/6df610045516f48930484eeed698a13396362305/.travis.yml).

Is there a way to test this interactively, so we can determine why it believes the .gemspec does not exist, rather than continuing to create tags on the project? Thanks!

**Comment by BanzaiMan** [comment]
You are changing build directory to `test` (https://github.com/voxpupuli/metadata-json-lint/blob/6df610045516f48930484eeed698a13396362305/.travis.yml#L6), so `metadata-json-lint.gemspec` is not found.

**Comment by rnelson0** [comment]
Haha, whoops. Thanks for the additional pair of eyes!

**Comment by nibalizer** [comment]
Thanks @BanzaiMan :)
