### ISSUE TITLE
Provider: Lambda - Publish a new version

### ISSUE THREAD

**Issue by quiqua** [travis-ci/dpl#531]
At the moment the function code is uploaded to the corresponding AWS Lambda function, but 
a new version is not published.

Issue of the problem: [AWS::LambdaPreview::Client](https://docs.aws.amazon.com/sdkforruby/api/Aws/LambdaPreview/Client.html) is used which doesn't support the `publish` parameter compared to [AWS::Lambda::Client](https://docs.aws.amazon.com/sdkforruby/api/Aws/Lambda/Client.html#update_function_code-instance_method)

**Comment by BanzaiMan** [comment]
I think this is what #530 aims to resolve. I'm closing this in favor of the PR. If you think otherwise, do let us know.

**Comment by quiqua** [comment]
The mentioned PR doesn't solve the issue, the `publish` parameter is set to `false` by default and there is no way one can specify this with the PR.

SDK Reference: https://docs.aws.amazon.com/sdkforruby/api/Aws/Lambda/Client.html#update_function_code-instance_method

Missing paramter in PR:
https://github.com/travis-ci/dpl/pull/530/commits/b5cbdd5728023211d10383667c3f801f0af266f1#diff-2855ca09f56476a1d80480e0d29d20a1R54

**Comment by BanzaiMan** [comment]
Thanks for the explanation.

**Comment by vvondra** [comment]
#530 however updates to the SDK version that supports publish

 - I can either add the feature in the current PR 
 - or I'm planning to add this as soon as it's merged to make the changeset smaller

**Comment by vvondra** [comment]
The change is actually much smaller than I though, I added it to #530, could you test on the branch if it works for you fine?

**Comment by quiqua** [comment]
Looks good to me, but didn't test this so far.

**Comment by vvondra** [comment]
instructions here: https://github.com/travis-ci/dpl/blob/master/TESTING.md#testing-dpl-in-the-context-of-travis-ci-builds, just specify my fork and branch

I'll test as well with my build

**Comment by quiqua** [comment]
Works like a charm :)
Thanks!
