### ISSUE TITLE
ElasticBeanStalk provider not working

### ISSUE THREAD

**Issue by olivierlesnicki** [travis-ci/dpl#533]
Get the following error:
```
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. 
```

**Comment by briananderson1222** [comment]
Well that error message is not very precise.. but your issue is even less descriptive.. how about some details?

**Comment by olivierlesnicki** [comment]
Found the root cause, my S3 and Elastic BeanStalk instances were in two different regions.
