### ISSUE TITLE
Update octokit to 4.4.0+

### ISSUE THREAD

**Issue by jirutka** [travis-ci/dpl#542]
Version 4.3.x (defined in Gemfile) is quite old and not supported by upstream anymore. It contains bug that causes:

```
/home/travis/.rvm/gems/ruby-2.2.5/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `initialize':
Permission denied @ rb_sysopen - build/foo.tar.gz (Errno::EACCES)
```

when build/foo.tar.gz is not **writable** for travis user (e.g. it’s owned by root). This has been fixed in 4.4.0 by https://github.com/octokit/octokit.rb/commit/8873632ef6b8ce02a73b8b84a7ad9500ba96b4de.

**Comment by BanzaiMan** [comment]
Thanks for the report, but we can't use it yet, since Octokit 4.4 requires Ruby 2.

**Comment by waghanza** [comment]
why not using latest `octokit`, but only on ruby 2 as of #554
