### ISSUE TITLE
Provider Lambda - Create event source mapping in deployment 

### ISSUE THREAD

**Issue by DaMaillard** [travis-ci/dpl#543]
When deploying a lambda with travis, it seems we have to set the trigger in a script in after_deploy, using the AWS CLI `create-event-source-mapping`.

It should great to create it in the deploy lambda.

**Comment by carlthome** [comment]
ETA on this? I'd expect at least some support for event triggers directly in the provider. https://github.com/travis-ci/dpl#lambda

**Comment by tdmalone** [comment]
Just to clarify, this applies when using `publish: true`, correct? If a new version is not published, then the original event source mappings will stay in place on the `$LATEST` version?

@DaMaillard It might be handy for others coming across this issue to include your `after_deploy` script, if you have a common one you use. I imagine you'd need to detect what the latest version is first, and then create the mapping directly on that version?

**Comment by tdmalone** [comment]
:wave:

**Comment by svenfuchs** [comment]
@DaMaillard @carlthome @tdmalone I'd like to take a shot at this in dpl v2. however, i could use some guidance on how exactly this feature needs to work. could you elaborate on when the mapping would need to be created and/or updated?
