### ISSUE TITLE
Feasability of Supporting AWS AssumeRole

### ISSUE THREAD

**Issue by davidski** [travis-ci/dpl#547]
I recently discovered the `dpl` tool and am loving the Travis-AWS integration. One sticking point is the current dependency on hard coded access keys in the `.travis.yml` file. Encryption helps for protecting the confidentiality of the keys, yet still leaves the problem of long lived keys potentially in many repositories. It would be wonderful if this could support assuming an AWS IAM role in the destination account, allowing users to remove the keys from their yaml files.

The tricky part is this would require having a Travis IAM user to to which assume role permissions could be granted. Has there been any thought to potentially supporting such a scenario? Much appreciate it!

**Comment by erikerikson** [comment]
I have been asking why this doesn't exist and will be looking for an offering that has it.

Ideally, a role would be created by the CI subsystem for each new repository (I'll call that `rH` [role of hoster]).  Perhaps only generated upon checking a box or whatnot.  The ARN for that role, controlled by the CI hoster/provider, could be provided such that we could establish our own IAM role (`rO` [role of owner]) with which to establish a trust relationship to `rH` and assign the rights required to take the actions that the CI host will take on our behalf (i.e. as specified within `.travis.yml`).  The agents running under some broad rights and with some secret or another, would assume the `rH` associated with the repository and this would give it the right to assume `rO` and to offer those credentials in the environment while executing any necessary privileged actions using them.

This would make a lot of people sleep better at night while providing a strictly superior developer experience and a more secure means of rights management.

**Comment by hirenshah005** [comment]
We really need this feature.
