### ISSUE TITLE
Deploy our custom host

### ISSUE THREAD

**Issue by waghanza** [travis-ci/dpl#553]
Hello,

Has `dpl` any feature to **deploy** on a private host ?

I think of a `capistrano` like `deployment` (through **ssh**).

Regards,

**Comment by BanzaiMan** [comment]
What does it mean to "deploy on a private host"? There is no standard way to do such a thing.

If you are using `ssh` to run a command, you can do this with [the `script` provider](https://docs.travis-ci.com/user/deployment/script) or [the `after_success` phase](https://docs.travis-ci.com/user/deployment/custom/).

**Comment by waghanza** [comment]
It could be standardized ... as `heroku` has `Procfile` standard ...

**Comment by BanzaiMan** [comment]
What standard are you talking about?

**Comment by waghanza** [comment]
https://ddollar.github.io/foreman/

**Comment by BanzaiMan** [comment]
In what way is Foreman a standard? If you would like support for deployment with Foreman, you are welcome to open a separate issue.
