### ISSUE TITLE
Rackspace Cloud Files Deploy Fails with: fog/rackspace (LoadError)

### ISSUE THREAD

**Issue by carolynvs** [travis-ci/dpl#561]
See https://travis-ci.org/getcarina/dvm/builds/188601935#L317 for the failed deployment. I am using a [nearly identical deployment for another project](https://github.com/getcarina/carina/blob/release/2.0.0/.travis.yml), and the [deploy worked just fine this morning](https://travis-ci.org/getcarina/carina/builds/188590126). Both deploys are using `dpl-1.8.29`.

Here's the meat of the error:
```
ERROR:  Error installing fog-rackspace:
	nokogiri requires Ruby version >= 2.1.0.
```

Looks like a dependency of fog-rackspace (nokogiri) [started requiring ruby 2+ recently](https://rubygems.org/gems/nokogiri/versions/1.7.0-x64-mingw32).

Here's the full log from the deployment:
```
Installing deploy dependencies
Fetching: net-ssh-2.9.4.gem (100%)
Successfully installed net-ssh-2.9.4
1 gem installed
Fetching: mime-types-2.6.2.gem (100%)
Successfully installed mime-types-2.6.2
1 gem installed

Fetching: ipaddress-0.8.3.gem (100%)
Successfully installed ipaddress-0.8.3
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: nokogiri-1.7.0.gem (100%)
ERROR:  Error installing fog-rackspace:
	nokogiri requires Ruby version >= 2.1.0.
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fog/rackspace (LoadError)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/provider.rb:76:in `requires'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/provider/cloud_files.rb:8:in `<class:CloudFiles>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/provider/cloud_files.rb:5:in `<class:Provider>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/provider/cloud_files.rb:4:in `<module:DPL>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/provider/cloud_files.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/provider.rb:58:in `const_get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/provider.rb:58:in `block in new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/provider.rb:55:in `new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.29/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

This is my deploy configuration:

```yaml
deploy:
  - provider: cloudfiles
    username: ***
    api-key:
      secure: ***
    region: IAD
    container: carina-downloads
    skip_cleanup: true
    on:
      repo: getcarina/carina
      tags: true
```

**Comment by carolynvs** [comment]
I have verified that running with `sudo: required` fixes the deploy, but I don't really know why and I didn't need sudo access to run my build. Is there a difference in what's installed or available on the PATH in a sudo vs. regular build?

**Comment by BanzaiMan** [comment]
The dependency on `nokogiri` comes from `fog-xml`. I don't think any other does, so pinning `nokogiri` to `~> 1.6.8.1` should do the job.

**Comment by carolynvs** [comment]
@ BanzaiMan Is that something that I should be altering in my `.travis.yaml` file?

**Comment by BanzaiMan** [comment]
@carolynvs It is not. We'll have to have a release for it.

**Comment by BanzaiMan** [comment]
@carolynvs Could you try the following configuration, please?

```yaml
deploy:
  provider: cloud_files
  edge:
    branch: bug-cloud_files
  ⋮ # rest
```

**Comment by carolynvs** [comment]
@BanzaiMan Here's the failed build with `bug-cloud_files`: https://travis-ci.org/getcarina/dvm/jobs/188916457

**Comment by BanzaiMan** [comment]
@carolynvs Is `cd bin` in `before_deploy` necessary?

**Comment by carolynvs** [comment]
That is straight out of the Travis documentation for how to deploy the contents of a single directory. https://docs.travis-ci.com/user/deployment/cloudfiles/#Deploy-To-Only-One-Folder 😄

**Comment by BanzaiMan** [comment]
Hmm. I see. That means we can't test this without additional modification. :-/

**Comment by carolynvs** [comment]
If it's just to test this fix, I can remove that line from my branch and deploy to a dummy container. I'll try that now.

**Comment by BanzaiMan** [comment]
@carolynvs That'll be great. Thank you!

**Comment by carolynvs** [comment]
It worked! 😄 https://travis-ci.org/getcarina/dvm/jobs/188954409

**Comment by carolynvs** [comment]
I just tried to use this and it looks like a new release is needed (1.8.30) before I can use it. Anyone up for doing a release on a Friday afternoon? 😀
