### ISSUE TITLE
Lambda: Stop requiring certain configuration values

### ISSUE THREAD

**Issue by kubek2k** [travis-ci/dpl#566]
With introduction of updating the function (code and configuration): https://github.com/travis-ci/dpl/pull/530, it doesn't always make sense to require those values:
  * handler name
  * role
  * runtime 

since those values are already set in case of update.

**Comment by tdmalone** [comment]
I'd also like to add `description` to this, as I don't particularly want to change/replace my function's description with each deployment.

And probably `timeout` and `memory_size` too. If I haven't set them in `.travis.yml`, I don't particularly want what I _have_ set in the Lambda web console to be overridden by [dpl's defaults](https://github.com/travis-ci/dpl#lambda). :)

**Comment by tdmalone** [comment]
unstale

**Comment by tdmalone** [comment]
unstale

**Comment by BanzaiMan** [comment]
`runtime` and `description` do not appear to be required arguments to me. The former should default to `nodejs`, and the latter to `"Deploy build #{context.env['TRAVIS_BUILD_NUMBER']} to AWS Lambda via Travis CI"` if it is not given.

**Comment by BanzaiMan** [comment]
Neither `timeout` nor `memory_size` is required.

**Comment by tdmalone** [comment]
unstale

**Comment by tdmalone** [comment]
> runtime and description do not appear to be required arguments to me. The former should default to nodejs, and the latter to "Deploy build #{context.env['TRAVIS_BUILD_NUMBER']} to AWS Lambda via Travis CI" if it is not given.

My preference would be that these _don’t_ default to anything. Or, if they’re required by the AWS API when updating function code (I don’t believe they are), the current values are used.

By defaulting to a value for description, for example, it will override whatever the user has previously set in the AWS console.

**Comment by BanzaiMan** [comment]
@tdmalone #884 does not set any default. Could you test it?

**Comment by tdmalone** [comment]
Sorry I haven’t had a chance to test this yet. I’m not actively working on a project which is deploying with Travis, but I’m still very interested in this as I’ll be coming back to a few said projects as soon as I have time. If no-one has tested then, I’d be happy to do so.

**Comment by svenfuchs** [comment]
I believe this issues is now addressed in `master` (dpl v2). The lambda provider now only requires credentials and the function name when updating functions: https://github.com/travis-ci/dpl/blob/master/spec/dpl/providers/lambda_spec.rb#L119

I am going to close this issue here. Please feel free to re-open.
