### ISSUE TITLE
How to configure GCS deploy timeout in travis_ci

### ISSUE THREAD

**Issue by CaptainJojo** [travis-ci/dpl#568]
I use deploy gcs option in travis-ci, you can see documentation here https://docs.travis-ci.com/user/deployment/gcs/. But my deployement take more than 10 minutes.

```
No output has been received in the last 10m0s, 
this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: 
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

But I don't find option to change timeout ? How it's possible ?

http://stackoverflow.com/questions/41636656/how-to-configure-gcs-deploy-timeout-in-travis-ci

**Comment by BanzaiMan** [comment]
There is no configuration tweak for deployment timeout, but you could add a background process that writes something to STDOUT before the deployment starts. This will prevent your deployment to not be killed when 10 minutes is up.

For the least visual infractions, one can write visual bells (`\a`):

```yaml
before_deploy: |
  function keep_alive() {
    while true; do
      echo -en "\a"
      sleep 5
    done
  }
  keep_alive &
```

**Comment by CaptainJojo** [comment]
Thank is very good, is not beautiful but it works

**Comment by BanzaiMan** [comment]
Great. I'm closing this now.

**Comment by CaptainJojo** [comment]
A better solution is possible ? For example add option directly in travis build to disabled timeout.

**Comment by BanzaiMan** [comment]
I don't think deployment can use `travis_wait` (which is explained in the document mentioned in the logs), so I am afraid there is not.
