### ISSUE TITLE
[Provider: Deis] missing cli_version error

### ISSUE THREAD

**Issue by davidguttman** [travis-ci/dpl#570]
Breaks on travis-ci.com and on command-line with:
```
⚡ dpl --provider=deis --controller=deis.domain.com --username=travis --password=swordfish --app=app-name
Installing deploy dependencies
missing cli_version
```

Works if `--cli_version=v2.10.0` is added to the command-line though

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/dpl/blob/98bdba701d4c69f238d245048577eb9067afa1d9/lib/dpl/provider/deis.rb#L7

I am guessing that the install script now requires it.

**Comment by davidguttman** [comment]
https://travis-ci.com/Interlincx/feed-proxy/builds/38069482

**Comment by BanzaiMan** [comment]
Ah. It's a bug. I'll take a deeper look next week.
