### ISSUE TITLE
Deplyoment with serverless framework

### ISSUE THREAD

**Issue by NeoLegends** [travis-ci/dpl#572]
Would be great for AWS Lambda functions. I know that AWS lambda is already supported, but with serverless support we could use our existing serverless.yml files for deployment.

**Comment by troyswanson** [comment]
@NeoLegends Why'd you close this? I came here for this too :)

**Comment by NeoLegends** [comment]
Thats a good question, I don't really remember anymore. But maybe because it's already possible via post build script.

**Comment by troyswanson** [comment]
I mean, it seems like it would be pretty easy to `npm install serverless -g` and then `serverless deploy`, as long as you include AWS credentials as encrypted environment variables...

But it also be really cool just to have this as a provider. 😄

**Comment by NeoLegends** [comment]
Exactly

**Comment by iriberri** [comment]
I just got a new request for this, so I'm reopening this issue :)

**Comment by revmischa** [comment]
Would be nice to just ask to deploy on serverless. The deploy target should come with serverless installed from npm and allow you to specify a stage. Setting up encrypted aws creds could be made simpler or better documented.
