### ISSUE TITLE
Silence curl output for heroku deployments

### ISSUE THREAD

**Issue by fabn** [travis-ci/dpl#576]
It would be very nice to provide an option to silence curl output when uploading application to avoid all this noise in CI logs

![image](https://cloud.githubusercontent.com/assets/324213/22484489/e8f2af7a-e801-11e6-8bba-ec13e129de15.png)

Maybe default value can be based on `$stdout.isatty` value, in this way typical user does not need to configure anything.

**Comment by fabn** [comment]
Any feedback on this?

**Comment by BanzaiMan** [comment]
Will be closed by #888.
