### ISSUE TITLE
MAJOR BUG: Lambda deploy not working when function is on the second page of list_functions

### ISSUE THREAD

**Issue by mboudreau** [travis-ci/dpl#578]
I'll try to keep a level head about this, but I am seriously facepalming so hard about the person who overlooked this major use case, and I cannot believe this hasn't been flagged before, or that the method that is being used to find if a lambda exist is extremely wrong on its surface.  It's making me reconsider the viability, security and competence of the Travis team based on the code I'm seeing and, I can only speculate, the complete lack of any code reviewing process within the company.  Anyone that's ever coded on AWS would first of all know that everything's paginated on listing APIs and that you should never use listing APIs if you just want to know if the function exists or not, use the get_function api for that.

This is all [because of a merge that happened 21 days ago](https://github.com/travis-ci/dpl/pull/530) with complete disregard of common sense and thorough testing.

At my work, we're using Lambdas more and more, and as such, we're getting a long list of them.  A few days ago, our deployment process was ground to a halt when an error kept popping up around permissions needed for lambda:list_functions.  Weird, never seen that before, I figured that AWS might of changed something with permissions, but I didn't hear anything.  I tried adding permissions one by one, but it still kept breaking.  Out of frustration, I just added the permission of lambda:* to be done with it, which worked, but now my lambdas wouldn't deploy at all and would return this error:

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.3/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Function already exist: search-full-backfill (Aws::Lambda::Errors::ResourceConflictException)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.3/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.3/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32.travis.141.1/lib/dpl/provider/lambda.rb:64:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32.travis.141.1/lib/dpl/provider.rb:146:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32.travis.141.1/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32.travis.141.1/lib/dpl/provider.rb:146:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32.travis.141.1/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32.travis.141.1/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32.travis.141.1/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

I know that my function currently exists, hence the error, but the Lambda deploy should check to see if the lambda exists before deciding if it should simply update or create a new function.  So what was going on?  Using the aws-sdk directly from my terminal, I could see the function come up without issue.

Then I delved into the code.  I'm no Ruby expert; quite frankly, I'm really not a fan of the processes on Ruby and 9 times out of 10, works like crap on anything but Mac systems, but I digress.  That's where I see this nice little gem: 

```
response = lambda.list_functions

if response.functions.any? { |function| function.function_name == function_name }
```

...say what?  You'd think since it would go through all function names, it would find the one that's already available and go down the proper conditional, however, it seems that someone [forgot to even read the AWS SDK documentation around list functions](http://docs.aws.amazon.com/sdkforruby/api/Aws/Lambda/Client.html#list_functions-instance_method) and never set a `max_items` or even trying to loop through the markers to get all functions.  This means that only the default amount is returned, which I believe is 10.  Most of the functions that I've written are on the second page.  See the issue?

Please revert that pull request that was merged until someone creates good tests and doesn't release a breaking change to the wider community.

_PS.  Who the hell does acceptance testing based upon log output?! Are you completely mad?_

**Comment by BanzaiMan** [comment]
@mboudreau Hello. Could you confirm that the workaround I suggested in https://github.com/travis-ci/dpl/pull/530#issuecomment-276868681 is working for you at the moment?

**Comment by mboudreau** [comment]
@BanzaiMan Yeah, it's working.

**Comment by carlthome** [comment]
Is this solved?

**Comment by BanzaiMan** [comment]
Not yet. Could you test the experimental fix with:

```yaml
deploy:
  provider: lambda
  edge:
    branch: many-lambdas
  ⋮ # rest
```

and report the result?

I looked at the [documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/Lambda/Client.html#list_functions-instance_method) but it does not make it clear that there is a finite limit when the limit is not set.

> `:max_items` (Integer) — Optional integer. Specifies the maximum number of AWS Lambda functions to return in response. This parameter value must be greater than 0.

How many do you have to have in order for this bug to manifest?

**Comment by brad-sobie** [comment]
This is causing me issues as well.

**Comment by BanzaiMan** [comment]
@brad-sobie Did you try the potential fix I indicated above? If so, could you point me to the build log that shows the result? If not, please try it, and report the results.

**Comment by mboudreau** [comment]
@BanzaiMan Have you tried reverting the commit that broke the functionality of Lambda deployments?  It's almost been 6 months man, jebus...

**Comment by BanzaiMan** [comment]
@mboudreau The same question to you. Have you had a chance to test the proposed fix? Thanks.

**Comment by mboudreau** [comment]
@BanzaiMan as already [commented here, yes](https://github.com/travis-ci/dpl/issues/578#issuecomment-277667437), but that doesn't mean you can just go about and not fix the latest version, which should be stable and remove any known bugs that are very simple to fix, in this case, a single git command will fix it.  It also means that any new development on the Lambda provider won't be available for my team and I.

Your strange lack of ownership of this issue that you introduced into your own codebase is extremely vexing.

**Comment by BanzaiMan** [comment]
@mboudreau I think you misunderstood my previous comment. I was asking if you tried 

```yaml
deploy:
  provider: lambda
  edge:
    branch: many-lambdas
  ⋮
```

**Comment by mboudreau** [comment]
@BanzaiMan That's ludicrous.  Why would Travis need to make several calls to AWS just to see if a function exists?  That's badly designed on purpose.  What if the account has thousands of pages? Millions?  This solution simply doesn't scale and you should know better than this.

I also don't understand why you seem to be allergic to using Rescue, is there a particular problem with using it in Travis?

And finally, if you really don't want to use Ruby's own error handling, you're more than welcome to use the API directly without the SDK, or simply use another language that works for your situation since clearly, Ruby doesn't seem to.  

I cannot consciously accept your proposed solution because I believe it's extremely shortsighted and willfully ignorant, considering that the proposed changes seems to be based on a matter of  preference to not use rescue.  The previous version of this provider was working perfectly well, in the way that AWS themselves recommend.

**Comment by brad-sobie** [comment]
Using the branch was working yesterday, today it's not unless I specify `dist: precise`

https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default

**Comment by BanzaiMan** [comment]
@mboudreau Would you like to open a PR? I do see your frustration, and am happy to approve the `rescue` version. (I can do that, of course, but I figure you might want to as well.)

@brad-sobie Could you point to a build log URL that shows the problem you are having?

**Comment by mboudreau** [comment]
@BanzaiMan started a PR, still not finished since I'm adding all other SDK options that Travis seems to ignore.  I need to test these further with my projects. https://github.com/travis-ci/dpl/pull/676

**Comment by mboudreau** [comment]
@BanzaiMan Also needed to do a PR for travis-yml because apparently, you guys like to make things overly convoluted for no reason just to add deployment options: https://github.com/travis-ci/travis-yml/pull/7

**Comment by DaMaillard** [comment]
As other clients, I now get the problem with the branch `many-lambdas`. 

When will this bug be solved @BanzaiMan ? It seems to be several months that we use not maintained patches, in order not to block our continuous integration even in production. (But still, mine is now stuck)

Could we have a durable solution ? Or at least a feedback about this bug in your roadmap !

**Comment by BanzaiMan** [comment]
We have just released 1.8.43, which includes @mboudreau's fix for this issue.

**Comment by DaMaillard** [comment]
Yes indeed, this release seems to fix the issue. 

Thank you @mboudreau !

**Comment by mboudreau** [comment]
@DaMaillard No problem buddy :)

@BanzaiMan Someone should probably update the Lambda deployment README.  I don't think I put it in my PR :/

**Comment by BanzaiMan** [comment]
@mboudreau You mean https://docs.travis-ci.com/user/deployment/lambda? That's a different repo. I'll look into it tomorrow.

**Comment by mboudreau** [comment]
@BanzaiMan Yes, but also, the README in the dpl repo.

**Comment by BanzaiMan** [comment]
@mboudreau Did it miss https://github.com/travis-ci/dpl#lambda?

**Comment by BanzaiMan** [comment]
docs points to the dpl page for additional config options, so I think it is OK.

I'm closing this now. If there are other tasks to complete, do open a new ticket.

Thank you!

**Comment by mboudreau** [comment]
@BanzaiMan seems like I'm more organized than I remember and did in fact add the README updates :P
