### ISSUE TITLE
Github provider messes up tags

### ISSUE THREAD

**Issue by isage** [travis-ci/dpl#585]
Here's my https://github.com/isage/nxengine-evo/blob/master/.travis.yml
Workflow:
```
git tag -a v2.3
git push origin --tags
```
github creates release for this tag
appveyor (because it's faster than travis) updates this release with files. at this point tag is still right.
travis updates release with files.
Now, tag in release draft changes from actual tag to untagged-[commit]

I can, ofcourse, change it back to real tag, but i think i'm doing something wrong.

**Comment by isage** [comment]
Oh, it's not even commit hash.
Here's buildjob https://travis-ci.org/isage/nxengine-evo/jobs/226550872
Now, after travis pushed release, tag in release draft changed to "untagged-b063cc2fb78d811f7f45", 
and that's some completely random hash.

I'm not sure if that happens only with osx builder, or with linux too, as i'm pushing release from osx builder only.

**Comment by abitrolly** [comment]
From
https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/releases.rb 
http://octokit.github.io/octokit.rb/Octokit/Client/Releases.html#create_release-instance_method
https://developer.github.com/v3/repos/releases/#create-a-release
it looks like `untagged-` name is created automatically by GitHub if tag name is an empty string.

**Comment by isage** [comment]
I'm guessing somehow --exact-match fails and we are getting empty string. But why?
Checking out locally seems to work fine
```
$ git clone --depth=50 --branch=v2.4.1 https://github.com/isage/nxengine-evo.git isage/nxengine-evo
Cloning into 'isage/nxengine-evo'...
remote: Counting objects: 903, done.
remote: Compressing objects: 100% (524/524), done.
remote: Total 903 (delta 392), reused 837 (delta 375), pack-reused 0
Receiving objects: 100% (903/903), 3.11 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (392/392), done.
Checking connectivity... done.
Note: checking out '78e392e237cb7c1bc6f819d228e2d381d86edf23'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

$ cd isage/nxengine-evo
$ git describe --tags --exact-match
v2.4.1
```

**Comment by isage** [comment]
Moreover, it doesn't create a new release, it indeed updating existing one.
But, looking at update_release method in github and oktokit it looks like latter misses tag_name parameter. Maybe that's the problem?

**Comment by abitrolly** [comment]
The build job in first comment says `Current tag is: v2.4.1` so the tag is found successfully. Also, it looks like tag is embedded into `release_url` for update_release. There might be a conflict with `draft` flag or with merged options. Maybe it is possible to run dpl standalone to get more debug info..

**Comment by isage** [comment]
Yeah, it's still an issue.

**Comment by isage** [comment]
Also,
`dpl --provider=releases --api_key=<snip> --repo=nxengine/nxengine-evo --file=README.md --draft=true --overwrite=true --skip_cleanup=true`
works fine. So i'm not sure what's going on.

**Comment by isage** [comment]
That's still an issue, dear bot.
It looks like no one cares, thought.
