### ISSUE TITLE
provider: bintray, travis says 'missing provider, fail to deploy'

### ISSUE THREAD

**Issue by NickolasHu** [travis-ci/dpl#607]
Hi ,

I am trying to use bintray to deploy our production. I configed bintray and write yml according to travis docs. But still get error which says _missing provider, fail to deploy_

Any reason for this? How can I get specific information about this error?

build result. https://travis-ci.org/alibaba/Thera/builds/215819360
yml  https://github.com/alibaba/Thera/blob/master/.travis.yml

Thx.

**Comment by BanzaiMan** [comment]
You have [an intermediate `key`](https://github.com/alibaba/Thera/blob/e118bff71bec197ea65bbf3dcc474abdbfeb1099/.travis.yml#L28) that invalidates your deployment configuration.
