### ISSUE TITLE
Using custom_json option

### ISSUE THREAD

**Issue by altherlex** [travis-ci/dpl#608]
How can I use custom_json if source just convert to_json and I can not send a JSON on bash command

`$ dpl --provider=opsworks --app-id=$ID_APP --custom_json="{'deploy':{'api':{'scm':{'revision':'master' }}}}"`

am I right how I call custom_json or the gem is wrong when convert a string to json (https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/ops_works.rb#L87)???

**Comment by BanzaiMan** [comment]
JSON requires double quotes for strings, I believe, so you need to pass `--custom_json='{"deploy":{"api":{"scm":{"revision":"master"}}}}'`.

**Comment by BanzaiMan** [comment]
Closing now. Please let us know if you still have problems.
