### ISSUE TITLE
Cannot use environment variable to set deploy.prerelease in .travis.yml

### ISSUE THREAD

**Issue by Librazy** [travis-ci/dpl#613]
I tried to automate my github prerelease/release deploy. I wish I could ship a release when my commit message start with some magic chars. So I wrote some bash script in before_deploy to set up a environment variable GHTHUB_DEPLOY_PRERELEASE, and set deploy.prerelease to 
```
  prerelease: $GHTHUB_DEPLOY_PRERELEASE
```
everything works fine when preparing deploy.
But it says 
```
For 'properties/prerelease', "false" is not a boolean. // See: https://developer.github.com/v3
```
when deploying application.

full log:
https://travis-ci.org/Librazy/TooltipFilter/builds/222308618

.travis.yml:
https://github.com/Librazy/TooltipFilter/blob/d767b946acd87a701e886c9d282032558e001917/.travis.yml

……Seems that environment variables are always strings?

**Comment by BanzaiMan** [comment]
Boolean values need to be handled in Releases options.

**Comment by Librazy** [comment]
Any workaround now？ 
Can I call dpl directly then pass `--prerelease=$GHTHUB_DEPLOY_PRERELEASE` to it？

**Comment by BanzaiMan** [comment]
Arguments need to be processed by `dpl` into booleans, so that the GitHub API payload has correct data type (`false` vs `"false"`).

**Comment by tovrstra** [comment]
I'm hitting the same issue. Is there a workaround?

**Comment by mjackson** [comment]
One workaround would be to use `deploy.on.condition` to just skip the whole deploy. You need to duplicate all the other deploy config for each case, but since `prerelease` is a boolean there will only be 2.

I'm doing it [here](https://github.com/ReactTraining/react-stdio/blob/47f87399ba54c4ad876b1e1991775f4a5d6b7869/.travis.yml#L15-L41).

**Comment by XaF** [comment]
Following that issue. Same problem here.

**Comment by BanzaiMan** [comment]
Hello there. I've pushed a potential fix for this issue. Please test and report the results. Thank you.

```yaml
provider: releases
edge:
  branch: releases-booleanize
⋮ # rest
```

(If you have multiple deployment providers, please adjust the definition accordingly.)

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/dpl/pull/784

**Comment by BanzaiMan** [comment]
The code doesn't work on Ruby 2.3 and below. :-/

**Comment by Librazy** [comment]
It works !

**Comment by BanzaiMan** [comment]
1.9.2 is out.
