### ISSUE TITLE
Support deploying to multiple elasticbeanstalk environments

### ISSUE THREAD

**Issue by jakubholynet** [travis-ci/dpl#615]
Currently the `elasticbeanstalk` deployer doesn't support well deploying to multiple app environments - it creates and uploads three separate ZIP files and deploys them as separate versions. We currently need to deploy to 3 environments. It would be nice if we could specify multiple environments dpl deployed to them all.

**Comment by jakubholynet** [comment]
Here is my `elasticbeanstalk-multi-env.rb` that I can run with `ruby elasticbeanstalk-multi-env.rb` (provided DPL and all dependencies are installed and the AWS access env variables set). It supports multiple `--env` but `--wait_until_deployed` waits only for the first one.

```

require 'dpl/cli'
require 'dpl/provider'
require 'dpl/provider/elastic_beanstalk'

require 'time'

module DPL
  class Provider
    class ElasticBeanstalkMulti < DPL::Provider::ElasticBeanstalk
      experimental 'AWS Elastic Beanstalk Multi'

      def env_names
        Array(options[:env]) || raise(Error, "missing env")
      end

      def env_name
        raise(Error, "Deprecated: env_name has been replaced with env_names (plural)")
      end

      # Wait until EB environment update finishes
      # FIXME Currently this only waits for the first environment (modified by replacing `env_name` with `env_names.first`)
      def wait_until_deployed
        puts "wait_until_deployed ..."
        errorEvents = 0 # errors counter, should remain 0 for successful deployment
        events = []

        loop do
          environment = eb.describe_environments({
            :application_name  => app_name,
            :environment_names => [env_names.first]
          })[:environments].first

          eb.describe_events({
            :environment_name  => env_names.first,
            :start_time        => @start_time.utc.iso8601,
          })[:events].reverse.each do |event|
            message = "#{event[:event_date]} [#{event[:severity]}] #{event[:message]}"
            unless events.include?(message)
              events.push(message)
              if event[:severity] == "ERROR"
                errorEvents += 1
                warn(message)
              else
                log(message)
              end
            end
          end

          break if environment[:status] == "Ready"
          sleep 5
        end

        if errorEvents > 0 then error("Deployment failed.") end
      end

      def update_app(version)
        env_names.each do |env_name|
            puts "Updating env #{env_name} to #{version[:application_version][:version_label]}"
            options = {
              :environment_name  => env_name,
              :version_label     => version[:application_version][:version_label]
            }
            eb.update_environment(options)
        end
      end
    end
  end
end

DPL::CLI.run([
    "--provider=elasticbeanstalkmulti",
    "--region=eu-west-1",
    "--bucket_name=elasticbeanstalk-eu-west-1-ACCOUNT_ID",
    "--app=my-eb-app",
    "--env=my-app-env",    "--wait_until_deployed=true"])
```

**Comment by BanzaiMan** [comment]
You can define multiple deployment targets. Does that suffice?

```yaml
deploy:
  - provider: elasticbeanstalk
    # configuration 1
  - provider: elasticbeanstalk
    # configuration 2
  - provider: elasticbeanstalk
    # configuration 3
```

**Comment by jakubholynet** [comment]
That is what we do now. But it builds and uploads 3 times and creates 3
separate versions in EB.
fre. 21. apr. 2017 kl. 17.53 skrev Hiro Asari <notifications@github.com>:

**Comment by tzaitsev** [comment]
I would also appreciate a way to do the following to deploy the same artifact to multiple environments.

e.g.

env: 
      - 'development-worker-latest'
      - 'development-web-latest'

**Comment by BanzaiMan** [comment]
@jakubholynet do you have an example of such a build?

**Comment by jakubholynet** [comment]
I do, @BanzaiMan: https://travis-ci.com/TeliaSoneraNorge/rapidshop-data/builds/44398262

**Comment by BanzaiMan** [comment]
Great. OK, so I think it would make sense to accept an array for `env`/`envs` and deploy them accordingly:

```yaml
deploy:
  provider: elasticbeanstalk
  env:
    - env1
    - env2
  ⋮ # rest
```

**Comment by jakubholynet** [comment]
That is exactly what I do in my modified version.

**Comment by rajkumaranuk** [comment]
I tried this and it works

# Auto deploy un-tagged master commits to dev
  - provider:                elasticbeanstalk
    script:       	         echo "Deploy master (SpringbootconfigAPI-dev)"
    on:
      branch:                master
      condition:             -z $TRAVIS_TAG
    app:                     " Springbootconfig API"
    bucket_path:             " Springbootconfig API"
    skip_cleanup:            true
    bucket_name:             "elasticbeanstalk-eu-west-1-829070902612"
    env:                     SpringbootconfigAPI-dev
    region:                  eu-west-1

  # Delete the the zip artifactory
  - provider:     script
    script:       find . -type f -name "*.zip" -exec rm -f {} +
    skip_cleanup: true
    on:
      branch:     master

  # Auto deploy un-tagged master commits to dev
  - provider:                elasticbeanstalk
    script:       	         echo "Deploy customer-dev (APICustomerConfigService-deva)"
    on:
      branch:                master
      condition:             -z $TRAVIS_TAG
    app:                     "APICustomerConfigService"
    bucket_path:             "APICustomerConfigService"
    skip_cleanup:            true
    bucket_name:             "elasticbeanstalk-eu-west-1-829070902612"
    env:                     APICustomerConfigService-deva
    region:                  eu-west-1

**Comment by julien51** [comment]
The change proposed above by @BanzaiMan and @tzaitsev  would be fantastic ;)
