### ISSUE TITLE
Problem deploying to Heroku API V3

### ISSUE THREAD

**Issue by mrbongiolo** [travis-ci/dpl#640]
I've just updated dpl to 1.8.33 and it's giving this error:
```ssh
$ dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY
Installing deploy dependencies
Successfully installed excon-0.55.0
Successfully installed multi_json-1.12.1
Successfully installed heroku-api-0.4.2
3 gems installed
Successfully installed rendezvous-0.1.2
1 gem installed
Preparing deploy
No stash found.
Expected(200) <=> Actual(404 Not Found)

body: "{\"id\":\"not_found\",\"message\":\"The requested API endpoint was not found. Are you using the right HTTP verb (i.e. `GET` vs. `POST`), and did you specify your intended version with the `Accept` header?\"}"
```

It was working earlier today, then Heroku started to throw some errors telling that the v2 will be shutdown, I thought that the latest updates on the `1.8.33` version would work on the V3 API.

**Comment by BanzaiMan** [comment]
Sorry for the troubles. Do you have a build log URL that shows the problem?

**Comment by mvanduijker** [comment]
Warning was given in #508

**Comment by mrbongiolo** [comment]
But shouldn't the this update make it compatible with v3 or not?

**Comment by BanzaiMan** [comment]
Sorry about the troubles. I've yanked 1.8.33. Since the brownout is over, the deployment should resume with 1.8.32. We'll have further tests to fix the problem correctly.

**Comment by mrbongiolo** [comment]
@BanzaiMan the only error I got was this: `body: "{\"id\":\"not_found\",\"message\":\"The requested API endpoint was not found. Are you using the right HTTP verb (i.e. `GET` vs. `POST`), and did you specify your intended version with the `Accept` header?\"}"`, based on #508 it seems like it need to use their new `platform-api` gem.

**Comment by mvanduijker** [comment]
> But shouldn't this update make it compatible with v3 or not?

Ah I missed there was an update

**Comment by Donaldo** [comment]
Hi,

I found this gem very useful for my CI but at the moment I am stuck with the new Heroku v3 API ... 
Somebody know when this gem will be updated with v3 API support ?

**Comment by BanzaiMan** [comment]
Hi, everyone. I've pushed a new code to check API authorization more directly (that is, with `heroku-api` gem, but using the correct endpoint). To test it, you'd have to either build it yourself:

```
git clone https://github.com/travis-ci/dpl.git
cd dpl
git checkout heroku-v3
gem build dpl.gemspec
gem install ./dpl-*.gem
```

or deploy it [using Travis CI](https://github.com/travis-ci/dpl/blob/master/TESTING.md).

```yaml
deploy:
  provider: heroku
  api_key:
    secure: ****************************************
  app: docs-travis-ci-com
  edge:
    branch: heroku-v3
  # ⋮ rest
```

https://travis-ci.org/travis-ci/docs-travis-ci-com/builds/237716231#L228 shows a successful deployment using the new method.

I'd appreciate it if you could test it, too.

**Comment by mrbongiolo** [comment]
@BanzaiMan I've tested it locally and it seems to work, I was able to deploy my current branch to the staging env.

**Comment by Donaldo** [comment]
It's also working for me locally.
@BanzaiMan When do you plan to publish a new release with this fix ? 

Thanks !!

**Comment by BanzaiMan** [comment]
Still needs support for the `run` options.

**Comment by andjosh** [comment]
For anyone needing a simple deployment/build to Heroku, I built this yesterday to do the same thing I was using `dpl` to do: https://github.com/andjosh/heropush

It's just a shell script to use the Heroku V3 API to create a build, stream the output, and verify it.

**Comment by BanzaiMan** [comment]
I'm planning on releasing `dpl` 1.8.34 that makes all API calls to the V3 endpoints. We should be ready for the brownout on Monday at [16:00 UTC](https://status.heroku.com/incidents/1164).

**Comment by BanzaiMan** [comment]
We have released `dpl` 1.8.34. Heroku API deployment now uses V3 API endpoint exclusively, and supports `run` and `restart` commands as before.

I'm going to keep this issue open until Monday's next brownout, at which time we should know if it **_really_** works.

**Comment by BanzaiMan** [comment]
I will delete the `heroku-v3` branch around 21:00 UTC Monday, so if you are using that branch, please remove the `edge.branch` workaround by then. The release should now work, so if you see the problem now, please let us know.

**Comment by BanzaiMan** [comment]
1.8.35 is out with fixes for the 2 remaining `curl` calls.

**Comment by BanzaiMan** [comment]
Hello, everyone!

`dpl` 1.8.37 is out with some code changes (but no functional changes). You should not see any differences in terms of deployment, but the `git-ssh` and `git-deploy-key` strategies will get a deprecation warning (as they are shut down with the legacy API; needless to day, these will fail during the scheduled brownout periods).

Do let us know if you see problems with `api` (which is the default) or `git` strategies.

The next two scheduled brownouts are

* Heroku V2 API Brownout on Monday, June 5th at 16:00 UTC (12:00 EDT)
* Heroku V2 API Brownout on Friday, June 9th at 18:00 UTC (14:00 EDT)

Thanks.

**Comment by BanzaiMan** [comment]
https://status.heroku.com/incidents/1174

> On Thursday, June 8, 2017, starting at 18:00 UTC (14:00 EDT), and continuing until 19:00 UTC (1 hour), Heroku will be performing a service update to our API.

**Comment by raldred** [comment]
Our deployments are failing as of 22 June 16:00 UTC 
Not sure if related but I'm getting issues using dpl 1.8.37
```
➜  dpl --provider=heroku --api-key=$HEROKU_API_KEY --app=$app 
Installing deploy dependencies
Successfully installed rendezvous-0.1.2
1 gem installed
~/ruby-2.4.0/gems/dpl-1.8.37/lib/dpl/provider.rb:85:in `require': cannot load such file -- rendezvous (LoadError)
```

**Comment by BanzaiMan** [comment]
@raldred 
Do you have a build log URL that shows the problem you are describing here?

**Comment by cbrzn** [comment]
Im trying to build the gem dpl.gemspec and i get this error 

> ERROR:  Gemspec file not found: dpl.gemspec

**Comment by BanzaiMan** [comment]
@cbrzn That is unrelated to this issue.

I'm closing this now, in the absence of clear indications that there is still something amiss.

If you see problems, do open a separate issue with details.

Thanks.
