### ISSUE TITLE
npm provider: add support of multiple packages publishing

### ISSUE THREAD

**Issue by Guria** [travis-ci/dpl#646]
[Monorepo setup](https://medium.com/@bebraw/the-case-for-monorepos-907c1361708a) for multiple packages became very popular due to simplifying maintenance.
Could we add support to provide `glob` that would be resolved to list of packages to be published?

**Comment by Joshua-Anderson** [comment]
You can use multiple deployment providers, which may make sense so you can customize each packages deployment conditions individually.

**Comment by Guria** [comment]
Hmm. Interesting solution. How can I define path to package then? Haven't found it in documentation

**Comment by Joshua-Anderson** [comment]
Ah, you're right! There is currently no option to specify the package directory. That would be an easy feature to add though.
