### ISSUE TITLE
Elasticbeanstalk deploy to an existing bucket error

### ISSUE THREAD

**Issue by abualy** [travis-ci/dpl#647]
hello! 
I used travis elasticbeanstalk provider to deploy an app to an existing EB stack:
it shows on travis that the deployment is done successfully, but on the stack i get:

![eb-error](https://cloud.githubusercontent.com/assets/2552664/26760838/89bbba10-4922-11e7-95ee-b58d96efdb8c.png)

when digging in CloudTrail errors, i see the detailed error:

![travis-error](https://cloud.githubusercontent.com/assets/2552664/26760890/9b9ccf8e-4923-11e7-800a-b318b923a82a.png)

i have already int he policy attached to that user:  buckets listing and creation for the bucket, and full access for objects in that bucket
the weird thing, is that it worked for previous updates in the same pipeline, but that specific commit had .ebextensions config added.

the error `bucket already owned by you` , when i looked it up, has to do sometimes with sending request to a region bucket is in an other region, but i have the bucket and the request both in `eu-west-1`

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by abualy** [comment]
actually, the log doesn't show any problem, that's the issue...
https://travis-ci.org/schibsted/sdk-example/builds/239037411
