### ISSUE TITLE
Deploying certain files to S3

### ISSUE THREAD

**Issue by zedevs** [travis-ci/dpl#648]
I am trying to selectively deploy a number of files to S3. I've tried listing them in my `travis.yml` file like so: 
```yml
file_glob: true
file: "file1.txt file2.txt"
```
also listing them as a list of files: 

```yml
file:
  - "file1.txt"
  - "file2.txt"
```

Can't find anything else like  that in the docs. What am I missing?

**Comment by BanzaiMan** [comment]
Create a directory that will contain all the files you want to upload, move your files there, and set `local_dir`: https://docs.travis-ci.com/user/deployment/s3#Deploy-From-Only-One-Folder
