### ISSUE TITLE
GitHub releases - support per repository deploy keys

### ISSUE THREAD

**Issue by abitrolly** [travis-ci/dpl#650]
`releases` deployment works only with OAuth or username/password, which is less secure than [per-repository deploy keys](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys).

https://docs.travis-ci.com/user/deployment/releases/
https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/releases.rb

**Comment by Joshua-Anderson** [comment]
Deploy keys can only be used for ssh git access to the repository. The releases provider needs api access in order to upload artifacts. GitHub recommends using a locked down bot user for this situation.

**Comment by abitrolly** [comment]
My fault. I though that one can push binaries to tags to make releases, but that's [doesn't work this way](https://developer.github.com/v3/repos/releases/#create-a-release). User needs `push` access to repository, but mechanism to push releases is through REST API, not through `git`.
