### ISSUE TITLE
GitHub releases - use existing Travis OAuth privileges

### ISSUE THREAD

**Issue by abitrolly** [travis-ci/dpl#652]
Continuation of #650 to limit scope of OAuth token used to releases only to repositories where Travis is enabled.

Travis CI already has access to repositories, so `release` addon could use Travis key to make releases though some internal API.

**Comment by BanzaiMan** [comment]
The OAuth token does not have the privilege to create releases for public repositories.

![authorize_application](https://user-images.githubusercontent.com/25666/26912554-463394ac-4be3-11e7-98e0-592f0aeccbf8.png)

**Comment by abitrolly** [comment]
@BanzaiMan it is possible to add public_repo per project? For example, on Travis CI site, which will then redirect to GitHub with new OAuth scope?

Just a comment - `Deployments` in above screenshot are surely confusing.

**Comment by abitrolly** [comment]
Added https://github.com/travis-ci/travis-ci/issues/7881
