### ISSUE TITLE
PyPI deployments fail - twine not found.

### ISSUE THREAD

**Issue by jaraco** [travis-ci/dpl#654]
Seen in #299 and #453, it seems that PyPI deployments are no longer working ([example](https://travis-ci.org/jaraco/jaraco.mongodb/jobs/245629950)) on projects where they've worked in the past.

**Comment by lmazuel** [comment]
Same issue here, but it seems it started after the move I made today to trusty container (I'm trying to go back while writing this message).

**Comment by jaraco** [comment]
Indeed, I see it in the Trusty container builds but not in [a standard build](https://travis-ci.org/jaraco/irc/jobs/246431845). What's a little odd is that presumably the dpl code is the same for both environments, and that's what's responsible for installing twine.

**Comment by jaraco** [comment]
I had thought that many of my projects used the same Travis config, but now looking at it, few of them specify the beta trusty container, and it was one that did that had the issue, so that does seem to be a factor.

Though as recently as May 1, the [deploy step completed without issue](https://travis-ci.org/jaraco/jaraco.mongodb/jobs/227716747), then also on Trusty containers.

**Comment by BanzaiMan** [comment]
I'm closing this in favor of https://github.com/travis-ci/travis-ci/issues/7735#issuecomment-301869479. Please test the proposed fix.
