### ISSUE TITLE
S3 deploy option to delete files not present in current deployment (sync)

### ISSUE THREAD

**Issue by abeMedia** [travis-ci/dpl#661]
We are using travis to build & deploy a static site from a private repo to s3, however rather than simply uploading all files we'd like to sync instead i.e. only uploading changed files and deleting files from the bucket which aren't present in the new build (like `aws s3 sync  . s3://bucket-name/ --delete`).

I'm thinking the addition of a `sync` or `delete` option which, if true, will make travis deploy behave as stated above would be great.

This would also fix https://github.com/travis-ci/docs-travis-ci-com/issues/519 and #422 

Just seen there is already a PR for this: #472

**Comment by gebn** [comment]
+1 to this. I'd like to use Travis to deploy a static website, and there is no case where I *would* want to keep around old files - they're in Git after all!

**Comment by gebn** [comment]
As this issue hasn't received any attention for some months, for the benefit of @kpfromer and any others looking: I eventually created a [utility](https://github.com/gebn/wood#demo) that syncs a local directory with S3, making the fewest changes possible (to save on PUT costs) based on the ETag of files. As Git does not store file modified times, a fresh clone's files (such as those checked out by Travis during a build) have recent timestamps, causes `aws s3 sync` to transfer absolutely everything, which was slow and expensive.
