### ISSUE TITLE
Are you planning to create a provider Netlify?

### ISSUE THREAD

**Issue by Leko** [travis-ci/dpl#663]
Hi there.
[Netlify](https://www.netlify.com/) is a hosting service mainly hosting static files.
It can deploy via [API](https://www.netlify.com/docs/api/#netlify-rest-api)

Deploy with these methods are supported:

1. [Sending a digest of all files in your deploy, and then uploading any files netlify doesn’t already have on its storage servers](https://www.netlify.com/docs/api/#deploying-via-files-digest)
1. [Sending a zipped website and let netlify unzip and deploy](https://www.netlify.com/docs/api/#deploying-via-zip-file)

Have you planning to create deploy provider ?

**Comment by tchak** [comment]
It would be also be nice to be able to trigger netlify builds once tests are passed on travis
