### ISSUE TITLE
Heroku provider: auth success log messages include the email 

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/dpl#666]
We log a message `authenticated as [email address from heroku]` which can be considered exposing private data. The email address comes from `https://api.heroku.com/account`, if I understand this correctly:

https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/heroku/generic.rb#L46-L48

Would it be better to log the user name instead?

**Comment by BanzaiMan** [comment]
Or, perhaps not showing is info at all. Just show that authentication was successful. (In general, `dpl` needs different levels of log, so that users can fine tune these sorts of things.)

**Comment by simonsmiley** [comment]
+1 on no info.  
If you want to show anything, I would suggest only showing the first couple of chars (ab******). But "authentication successful" should be enough.
