### ISSUE TITLE
Python wheels not being deployed 

### ISSUE THREAD

**Issue by nicoddemus** [travis-ci/dpl#678]
Hello,

Our [configuration for PyPI deployment](https://github.com/pytest-dev/pytest-xdist/blob/master/.travis.yml#L48) specifies that it should also upload wheels:

```yaml
        on:
          tags: true
          distributions: sdist bdist_wheel
          repo: pytest-dev/pytest-xdist
```

But unfortunately it does [not work](https://travis-ci.org/pytest-dev/pytest-xdist/jobs/265928272#L576):

```
creating dist
Creating tar archive
removing 'pytest-xdist-1.20.0' (and everything under it)
Uploading distributions to https://upload.pypi.org/legacy/
Uploading pytest-xdist-1.20.0.tar.gz
                                           
No stash found.
Done. Your build exited with 0.
```

The documentation says:

```
If you specify bdist_wheel in the distributions, the wheel package will automatically be installed.
```

But looking at [the logs](https://travis-ci.org/pytest-dev/pytest-xdist/jobs/265928272#L488) that doesn't seem to be the case:

```
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 idna-2.6 pkginfo-1.4.1 requests-2.18.4 requests-toolbelt-0.8.0 tqdm-4.15.0 twine-1.9.1 urllib3-1.22
```

Perhaps the fact that it is not installing the `wheels` package is the source of the problem?

cc @RonnyPfannschmidt

**Comment by RonnyPfannschmidt** [comment]
interestingly based on the code on master it should do the installation 
https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/pypi.rb#L46

however the code looks as if it uses an no longer existing api as other parts shell out to pip

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i found our mistake, the distributions key should be one level above (beside the trigger key)

**Comment by RonnyPfannschmidt** [comment]
if i'm correct, pytest_dev/pytest-xdist#225 should elevate the issue

**Comment by nicoddemus** [comment]
Hah, didn't notice as well. Thanks @RonnyPfannschmidt and sorry for the noise.
