### ISSUE TITLE
Lambda: publish conditions

### ISSUE THREAD

**Issue by gebn** [travis-ci/dpl#682]
It would be great if it were possible to do something like:

    deploy:
      provider: lambda
      ...
      publish:
        tags: true

Or something similar - essentially exactly the same flexibility as for `on`, but for the `publish` parameter. I've currently worked around this by duplicating the entire `deploy` sub-tree in the yml file, but that seems suboptimal.

**Comment by BanzaiMan** [comment]
I am not quite familiar with Lambda to understand what this option is meant to do. Do you have links for more documentation?

**Comment by gebn** [comment]
Hi @BanzaiMan. ["Publishing"](http://docs.aws.amazon.com/lambda/latest/dg/versioning-aliases.html) a Lambda function creates a new immutable version of it which can be referenced to always execute that code and configuration. However, that is largely irrelevant here - the feature I am requesting would not allow Travis to do anything it cannot already do, but it would remove the current need to nearly duplicate provider blocks in `.travis.yml`.

In my case, I would like to set an option (`publish`) on this provider to `true` if and only if a tag is being built. This is not currently possible without something like the following:

    deploy:
    - provider: lambda
      <many, many properties>
      on:
        branch: latest
    - provider: lambda
      <exactly the same properties>
      publish: true
      on:
        tags: true

The first provider will deploy and not publish (the default) if the `latest` branch is built. The second will deploy and publish if a tag is built. Both are needed because the provider's configuration is static - it is either executed by Travis (when its `on` condition(s) match the build), or ignored. There is no scope for dynamically changing the configuration (for example, the value of `publish`) according to conditions. Ideally, I'd be able to write something like this, which is equivalent to snippet above:

    deploy:
    - provider: lambda
      <many, many properties>
      publish:
        tags: true
      on:
        branch: latest

Here, the `publish` boolean is not statically set, but is derived in the same way as Travis decides whether to execute a provider by evaluating the `on` conditions. The `publish` boolean will be set to `true` if a tag is being built, or `false` otherwise.

Hopefully this clarifies - do let me know.

**Comment by tdmalone** [comment]
unstale

**Comment by tdmalone** [comment]
unstale

**Comment by tdmalone** [comment]
@banzaiman Could you please open this again?

I think we might need a longer timeout for stalebot...

**Comment by BanzaiMan** [comment]
I understand the use case here, but crowding deployment options this way does not seem right to me. Whether or not the current commit is tagged is not a concern of the deployment utility, but one of the thing that calls the deployment utility (in our case, the build script).

Conditional deployment is possible, for use cases like this.

**Comment by gebn** [comment]
I see your point. This is effectively syntactic sugar, so the pre-processing could take place outside dpl. As noted in January, it does not add anything that can't already be done - it's just a shorter way of writing the `deploy` section of `.travis.yml`.
