### ISSUE TITLE
Support multiple-buildpacks

### ISSUE THREAD

**Issue by francipvb** [travis-ci/dpl#683]
Hello,

I want to publish an app using two buildpacks, the nodejs ones and my custom buildpack to build server stuff.

I can't find how to do this from `.travis.yml`.

Cheers,

**Comment by BanzaiMan** [comment]
What's a "buildpack" in this context?

**Comment by francipvb** [comment]
Check [this](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app) link from Heroku.

Cheers,

**Comment by BanzaiMan** [comment]
OK. A Heroku deployment, then.

Have you tried deploying your app, or are you just asking?

I have not personally tested it, but as far as our deployment provider is concerned, this should not make a difference. We use API to deploy your app, and as long as the app can be deployed with a single API call, the number and the order of your buildpacks should not matter.

**Comment by francipvb** [comment]
Hello,

I posted this after I've tried this. For example, in the travis official documentation there are a snippet like this:
```
deploy:
  provider: heroku
  buildpack: ruby
```yaml

This works, but if it is possible, there are any instructions of how to use multiple buildpacks. I've tried some ways:

```
deploy:
  provider: heroku
  buildpack: buildpack1,buildpack2
```yaml

And this

```
deploy:
  provider: heroku
  buildpack:
    - buildpack1
    - buildpack2
```yaml

None of these ways work as expected. The two forms only takes the first buildpack and ignores the second or are just ignored.

However, there are a third form that I didn't:

```
deploy:
  provider: heroku
  buildpack: buildpack1
  buildpack: buildpack2
```yaml

And a fourth ones:

```
deploy:
  provider: heroku
  buildpacks:
    - buildpack1
    - buildpack2
```yaml

Cheers,

**Comment by BanzaiMan** [comment]
Hmm. This is strange. The `buildpacks` option was used only for the `anvil` strategy, which was deprecated and removed a few months ago. If anything, I expect this key to be a no-op. Do you have a build log URL to share what you mean by "it works"?

**Comment by BanzaiMan** [comment]
I've removed the reference to the `buildpack` key from the documentation, which we missed earlier when we removed references to the deprecated strategies.

**Comment by francipvb** [comment]
I don't have it right now. Then the correct way is to add an `application.json` file to the source code and simply let Travis to deploy to Heroku?

If I'm correct, you can close this.
