### ISSUE TITLE
Deis Deploy v1 Fails Attempts to Push Twice

### ISSUE THREAD

**Issue by bliles** [travis-ci/dpl#688]
As shown in this gist: https://gist.github.com/bliles/7c66ad4dce09f5eac8c2007afe28b14e
dpl tries to push the same branch twice. The second push fails, which travis ci interprets as failure. I don't see a way to prevent the second push so the job can succeed.

From .travis.yml:
  provider: deis
  controller: https://xxx.xxxx.xxx
  username: xxxxxxx
  password:
    secure: ...
  cli_version: 1.13.4
  app: xxx

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

We do not explicitly show the `dpl` command as you showed in the logs, so I am not sure how you are seeing this problem.

**Comment by bliles** [comment]
Absolutely: https://gist.github.com/bliles/d4a4275eaeb8326846a3f19818276f3a

I just tried running dpl locally to see if that helped me to understand the problem.

**Comment by BanzaiMan** [comment]
What is happening on your Deis instance *_after_* the initial [`git push`](https://gist.github.com/bliles/d4a4275eaeb8326846a3f19818276f3a#file-travis-build-log-L843)? It seems that your Deis instance is running a second `git push` (https://gist.github.com/bliles/d4a4275eaeb8326846a3f19818276f3a#file-travis-build-log-L989).

**Comment by bliles** [comment]
It does seem that way. The way our deis environment is configured, after the docker image is built and pushed to the private repo, the new release is automatically deployed. This seems to be the default behavior with docker (although I'm a bit new to deis).

**Comment by Joshua-Anderson** [comment]
This looks like a dpl issue of some sort, since the git output has to be coming from the git cli called by dpl. That being said, Deis V1 has been EOL for some time now, so YMMV. I'd personally  recommend taking a look at Deis V2 if possible, which is at least still in the maintenance period.
