### ISSUE TITLE
Bintray provider fails (HTTP version not supported)

### ISSUE THREAD

**Issue by Kogoro** [travis-ci/dpl#692]
I recently started to use travis to build and test my commits and now I'm aiming to use bintray for automatic deployment of my artifacts, but bintray fails every time with a 505 error:
```
Installing deploy dependencies
[Bintray Upload] Reading descriptor file: descriptor.json
Unexpected HTTP response code 505 returned from Bintray while checking if package 'VariantSync' exists. Response message: HTTP Version Not Supported
failed to deploy
```

The travis config looks like:
```
deploy:
  provider: bintray
  file: "descriptor.json"
  user: "username"
  key:
    secure: encrypted_apikey
  on:
    tags: true 
```
Did I configure something wrong or does this bug break the whole integration?

**Comment by hataror1999** [comment]
****

**Comment by hataror1999** [comment]
Good!

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by Kogoro** [comment]
Thanks for your response.
A build log is available under: https://travis-ci.org/Kogoro/VariantSync/builds/277528403
