### ISSUE TITLE
Allow github pages deployments to retain history

### ISSUE THREAD

**Issue by jyasskin** [travis-ci/dpl#704]
The [W3C deployment scripts](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) that I'm trying to replace retain the history of the gh-pages branch.

If this is a change you'd accept, would you rather an option to retain history, or just unconditionally do it?

**Comment by BanzaiMan** [comment]
If retaining history is possible, then we should.

**Comment by jyasskin** [comment]
It's totally possible. I assume you mean we should do it unconditionally.

The change will conflict with #695, so I'd appreciate you merging (or reviewing) that one, and I'll work on this one on top of it when I get back from vacation next week.

**Comment by polyzen** [comment]
See also travis-ci/travis-ci/issues/7562
