### ISSUE TITLE
Openshift v2 has reached End of Life. 

### ISSUE THREAD

**Issue by rhnvrm** [travis-ci/dpl#705]
travis.yml deploy>provider:openshift fails.

From the console of travis: [link](https://travis-ci.org/planetGSoC/planetGSoC.github.io/builds/289454391)

```
/home/travis/.rvm/gems/ruby-2.2.7/gems/rhc-1.38.7/lib/rhc/rest/client.rb:757:in 'handle_error!': The OpenShift Online (Next Gen) Developer Preview is here! We will not be accepting new users onto the OpenShift Online (v2) platform. (RHC::Rest::RequestDeniedException)
```

Also, according to my reading, rhc needs to be replaced here (https://github.com/travis-ci/dpl/blob/8f8034ff2f236b30ddf5a05c4ff2e2470356e7e1/lib/dpl/provider/openshift.rb) by oc (https://github.com/openshift/origin)

**Comment by BanzaiMan** [comment]
Would anyone like to take a look at the v3 support?

Until we can, we should just warn the users of `openshift` deployment and stop.

**Comment by rhnvrm** [comment]
@BanzaiMan I'll be up for it if someone can mentor me

**Comment by BanzaiMan** [comment]
Looks like OpenShift has shifted to provide interface with a Go binary, so the current use of the old Ruby API would not work.

I haven't looked at the documentation too closely, but if all that's needed is downloading the binary and executing commands in certain order, a similar pattern found in Cloud Foundry https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/cloud_foundry.rb should guide you.

**Comment by rhnvrm** [comment]
@BanzaiMan I could not figure out how to even use the go binary to deploy to the new version locally onto openshift from the documentation. The only way I could figure out how to deploy was with setting up a webhook. https://docs.openshift.com/online/dev_guide/builds/triggering_builds.html#webhook-triggers

**Comment by rhnvrm** [comment]
And that is also the only thing mentioned in the migration docs. https://docs.openshift.org/latest/dev_guide/migrating_applications/index.html

**Comment by abs51295** [comment]
@rhnvrm Why don't you create the same issue on [Open Shift](https://github.com/openshiftio/openshift.io/issues) ? I am sure somebody can help.
