### ISSUE TITLE
DigitalOcean Spaces support

### ISSUE THREAD

**Issue by fallafeljan** [travis-ci/dpl#711]
I'd love to see support for [DigitalOcean Spaces](https://blog.digitalocean.com/introducing-spaces-object-storage/), their new object storage service with an S3-compatible API.

As far as I've seen, the `s3` target only works for AWS S3 and there is no support for providing custom endpoints. However, Spaces [seems to be compatible with `aws-sdk`](https://www.digitalocean.com/community/questions/has-anyone-used-aws-sdk-to-operate-on-do-spaces-how-to-do-it).

**Comment by BanzaiMan** [comment]
I don't have a DO account to test it, but if the linked code example is something to be trusted, it should be as straightforward as adding the `endpoint` option to pass on to the S3 client we create.

**Comment by fallafeljan** [comment]
That's correct. There [once has been support for `endpoint`](https://github.com/travis-ci/dpl/pull/96), but it obviously got removed.

Adding that option would also possibly enable other storage services with S3-compatible APIs. [Minio](https://minio.io/), for example, also [seems to be compatible with `aws-sdk`](https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-ruby-with-minio.md). Maybe that should be kept in mind, although I don't know how the `region` parameter behaves when using non-AWS solutions.

**Comment by BanzaiMan** [comment]
@fallafeljan If you have a DO account to test, try this experimental branch:

```yaml
deploy:
  provider: X
  edge:
    branch: ha-s3-endpoint
⋮ # rest
```

**Comment by fallafeljan** [comment]
Thanks, I tried and got an `Aws::Errors::MissingRegionError` error:

```
Deploying application
uploading "foo" with {:content_type=>"bar", :acl=>"public-read"}
/home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.10.69/lib/aws-sdk-core/plugins/regional_endpoint.rb:34:in `after_initialize': missing region; use :region option or export region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.10.69/lib/seahorse/client/base.rb:84:in `block in after_initialize'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.10.69/lib/seahorse/client/base.rb:83:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.10.69/lib/seahorse/client/base.rb:83:in `after_initialize'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.10.69/lib/seahorse/client/base.rb:21:in `initialize'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.10.69/lib/seahorse/client/base.rb:105:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-resources-2.10.69/lib/aws-sdk-resources/resource.rb:169:in `extract_client'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-resources-2.10.69/lib/aws-sdk-resources/resource.rb:15:in `initialize'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/provider/s3.rb:10:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/provider/s3.rb:10:in `api'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/provider/s3.rb:58:in `block (2 levels) in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/provider/s3.rb:49:in `glob'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/provider/s3.rb:49:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/provider/s3.rb:48:in `chdir'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/provider/s3.rb:48:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/provider.rb:154:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/provider.rb:154:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/provider/s3.rb:76:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.44.travis.33.1/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

I think this is related to https://github.com/travis-ci/dpl/commit/7074b84ace804eb0242ff6395dd164a3c27aefb6, where `s3_options` now returns `defaults[:endpoint]` instead of `defaults`. I'm not a ruby expert, but adding `return defaults` after that fixed it for me, working fine with Spaces!

**Comment by BanzaiMan** [comment]
Oh, yes! You are right about `#s3_options` returning `nil`. Could you try again? I pushed 313ec80.

**Comment by BanzaiMan** [comment]
Hmm. That is strange. The return value should have `:region` defaulting to `us-east-1` when it is not set. https://github.com/travis-ci/dpl/blob/313ec80cbdb099cf50c6198e35f3a5463908b8ff/lib/dpl/provider/s3.rb#L30

**Comment by fallafeljan** [comment]
My bad, I confused it before. You're right, it works without `--region`.
