### ISSUE TITLE
Error in firebase deploy stage incorrectly results in build passing

### ISSUE THREAD

**Issue by miguel-orange** [travis-ci/dpl#728]
My .travis.yml is deploying to firebase provider. It looks like in the deploying application stage we received two informational messages and one error. I'd expect since this didn't deploy that the build would be flagged as errored.
![screen shot 2017-12-14 at 11 47 29 am](https://user-images.githubusercontent.com/13228659/34011358-9d3f04c2-e0c4-11e7-8613-fe46aae1c294.png)

**Comment by miguel-orange** [comment]
This is still an issue. This time I'm using firebase-functions@1.0.0, and deploying functions for the first time.
<img width="999" alt="screen shot 2018-04-03 at 10 56 18 pm" src="https://user-images.githubusercontent.com/13228659/38290914-4afc5820-3792-11e8-8bd5-f75697c5e381.png">

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by Andersos** [comment]
This is a URL that shows the problem https://travis-ci.com/webrebels/web-rebels-2018/builds/72482715

**Comment by gregorypratt** [comment]
https://travis-ci.org/BlazeUI/blaze/jobs/414500846

This still seems to be an issue. You think it has worked but it hasn’t deployed successfully...

**Comment by Andersos** [comment]
@BanzaiMan we have provided two links now with examples
