### ISSUE TITLE
[possible bug] `&>` syntax is not recognised by the underlying shell in Travis boxes

### ISSUE THREAD

**Issue by webknjaz** [travis-ci/dpl#730]
During the mysterious behavior investigation of Pages provider (https://github.com/travis-ci/dpl/pull/719#issuecomment-354507181) I've found out that execution of shell commands result in an unexpected behavior if they contain `&>/dev/null` for suppression of stderr and stdout.
It also looked like those commands return 0 (POSIX return code for success) early and produce output asynchronously with the main control flow in the Ruby script. And it was flakily reproducible in other envs.

That said, it became obvious for me that `&` is recognised as control operator for putting the command into subshell and execute it in background (returning code 0 immediately). I couldn't find anything on the web explaining this behavior and I couldn't find any of popular shells not recognising this `&>` sequence.
I guess that it might be that underlying shell in Travis is different or maybe it's smth related to how Ruby pre-processes commands before running them in shell.

I've found out that the solution is to use other more verbose syntax: `> /dev/null 2>&1`.

So I've `git grep`ped this repo and found this one provider using the syntax, which looks breaking the flow:
```
lib/dpl/provider/atlas.rb:10:        if ! command -v atlas-upload &>/dev/null ; then
lib/dpl/provider/atlas.rb:14:          if ! command -v gimme &>/dev/null ; then
lib/dpl/provider/atlas.rb:24:          eval "$(gimme 1.6)" &> /dev/null
```

P.S. I'm creating this issue to document my findings, but won't send a PR, because I'm not familiar with that Atlas provider.

**Comment by remyabel** [comment]
Don't think it's related to Travis. `context.shell` uses `system`, which like C, invokes a `/bin/sh` (aka POSIX) subshell. It's possible that POSIX doesn't like the abbreviated syntax.

**Comment by webknjaz** [comment]
@remyabel I understand this and I've checked POSIX sh as well. Anyway, it's solved in Pages provider.
I've filed this ticket just to document possible issue within Atlas provider.

**Comment by remyabel** [comment]
Yeah, regardless of whether or not it's valid POSIX syntax, you are correct it's possibly an issue. It seems to be assuming the use of Bash (i.e, `command` is a Bash built-in). Since `/bin/sh` is symlinked to bash on some systems, you won't see it break all the time. So a fix would be to explicitly invoke it with Bash.

**Comment by webknjaz** [comment]
Fair enough
