### ISSUE TITLE
AWS: Use `session_token` from env vars if available to support "assume role"

### ISSUE THREAD

**Issue by jakubholynet** [travis-ci/dpl#731]
We don't access our AWS account directly, but through a jump account. We therefore need to run `aws sts assume-role` for the target account, which produces temporary access_key_id, secret_access_key, session_token that can be used to access it.

So in theory I could manually run `aws sts assume-role` in `before-install:` and use its response to set the env variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN.

However that does not work because dpl ignores the AWS_SESSION_TOKEN variable - [it only passes the former two to Aws.Credentials](https://github.com/travis-ci/dpl/blob/faa940805231f876e4aba9798a5a39e1faa20249/lib/dpl/provider/code_deploy.rb#L15) ([Aws.Credentials](https://docs.aws.amazon.com/sdkforruby/api/Aws/Credentials.html#session_token-instance_method) also supports an optional third param, the session token).

=> pass AWS_SESSION_TOKEN on to the constructor if defined, otherwise nil.

(Or consider supporting also https://docs.aws.amazon.com/sdkforruby/api/Aws/AssumeRoleCredentials.html as an alternative to the key+secret authorization).

Thank you!

**Comment by gislainh** [comment]
Issue still there
