### ISSUE TITLE
Deployment to Bluemix (Node.js SDK) started breaking recently

### ISSUE THREAD

**Issue by MichaelOrtho** [travis-ci/dpl#734]
We are using Enterprise Github + Travis and I started seeing an issue with deployment with `cloudfoundry` and `bluemixcloudfoundry` deployment providers. 

Resolution attempts:
- I tried to redeploy previously successful builds/deployments and they fail, too. 
- I tried to redeploy other applications that were SUCCESS and that fails, too
- I did CLI application push from my local computer to Bluemix, it passed
- I tried to use trusty and precise, both fail

Based on what I tried, something is wrong in Travis provider that pushes application to Bluemix.

What happens is that after authentication to `cloudfoundry`, this happens:

```
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 13.83 MiB / 13.83 MiB [============================================] 100.00% 4s

Waiting for API to complete processing files...
Job (d3e16a23-769a-451d-8d6f-4e6131e660c3) failed: The app upload is invalid: Symlink(s) point outside of root folder
FAILED
Logging out...
OK

Failed to push app
failed to deploy
```

Any suggestions?

**Comment by MichaelOrtho** [comment]
I created same scenario in public GitHub and TravisCI.org and I see the same problem. This problem doesn't happen with native client or when you use custom deploy with script instead so it must be something with deploy `cloudfoundry` and `bluemixcloudfoundry` providers (or version of CLI). Locally I used last version.

**Github**:
https://github.com/MichaelOrtho/bluemix-test

**TravisCI**:
https://travis-ci.org/MichaelOrtho/bluemix-test/builds/329486522

**Workaround `deploy.sh` file**:
```
#!/bin/bash

curl -fsSL https://clis.ng.bluemix.net/install/linux | sh
bluemix api https://api.ng.bluemix.net
bluemix login -u $BLUEMIX_USER -p $BLUEMIX_PASS -o $BLUEMIX_ORGANIZATION -s $BLUEMIX_SPACE_PROD
bluemix app push
```
This worked properly...

P.S> I can give you access to my test repo and deployment if you send me your GitHub username

**Comment by BanzaiMan** [comment]
@MichaelOrtho Hello, there. Thanks for taking time to open this issue.

From what you describe, it sounds to me like Bluemix has diverged from CloudFoundry in its deployment configuration. (Sorry, I haven't looked this up fully; perhaps you have a better idea than I do.) The [current implementation](https://github.com/travis-ci/dpl/blob/cdab1c388ade3e49d823b9fb94038799910e927a/lib/dpl/provider/bluemix_cloud_foundry.rb) is basically [CloudFoundry](https://github.com/travis-ci/dpl/blob/cdab1c388ade3e49d823b9fb94038799910e927a/lib/dpl/provider/cloud_foundry.rb) with different defaults.

If you can improve the Bluemix provider to cope with this new frontier, we are more than happy to take a look!

Thanks!

**Comment by jchamber904** [comment]
@BanzaiMan So are you saying this is really a Bluemix issue?

**Comment by BanzaiMan** [comment]
@jchamber904 Not sure if I would put it that way. I am saying that the current implementation with simply calling `cf` is no longer adequate. I have not looked into it yet, but the future proof implementation is to download and use the `bluemix` executable (as @MichaelOrtho indicated), then `dpl` would have to adopt that workflow.

**Comment by MichaelOrtho** [comment]
@BanzaiMan You are not right. CloudFoundry provider has same issue...

https://travis-ci.org/MichaelOrtho/bluemix-test/builds/330563446

```
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 1.96 MiB / 1.96 MiB  100.00% 1s
Waiting for API to complete processing files...
Job (8e92472c-7b18-4104-ac5d-4aade303ad7c) failed: The app upload is invalid: Symlink(s) point outside of root folder
FAILED
Logging out...
OK
Failed to push app
failed to deploy
```
This is repo url:
https://github.com/MichaelOrtho/bluemix-test/tree/085216e497c3c3b14b7b8eca623597d9416ab4ae

**Comment by MichaelOrtho** [comment]
But @BanzaiMan why both CLIs: `cf` and `bluemix` are working properly from local computer?

**Comment by BanzaiMan** [comment]
@MichaelOrtho I'm not sure if I follow. That build is going to the same endpoint: https://github.com/MichaelOrtho/bluemix-test/blob/085216e497c3c3b14b7b8eca623597d9416ab4ae/.travis.yml#L21, no? If it fails with the `bluemix` provider, I expect it to fail with the `cloudfoundry` provider as well.

How are you invoking `cf` on your local machine when it succeeds?

**Comment by MichaelOrtho** [comment]
@BanzaiMan I am using same settings, same url and it passes both with `cf` and `bluemix` CLI. It must be something in Travis provider.

**Comment by MichaelOrtho** [comment]
@BanzaiMan Also, if you use a script provider (check above) it works from inside Travis. Maybe there is an issue in CLI version or something. But all repos that were working before started failing last week and something without any change to `.travis.yml`

**Comment by BanzaiMan** [comment]
> I am using same settings, same url and it passes both with cf and bluemix CLI.

How do you do this, exactly?

As for how the changes manifested…

Bluemix provider hasn't changed in 9 months, and CloudFoundry in 4. The `script` implementation you indicated above is quite different from what the current implementation of the Bluemix provider, so I expect different results.

**Comment by MichaelOrtho** [comment]
I both CLIs, I login, select API and do
   - for Bluemix CLI: `bluemix app push`
   - for CF CLI: `cf push` 
and it deploys. I do not understand your question. 

I am just saying that something changed around 10 days ago that started failing deployments even if you want to redeploy already passed ones.

**Comment by MichaelOrtho** [comment]
@BanzaiMan Are Bluemix and CF providers using `bluemix` and `cf` CLIs in Travis or they are deploying some other, custom way?

**Comment by MichaelOrtho** [comment]
This is how `cf` looks locally:
```
$cf -v
cf version 6.22.2+a95e24c-2016-10-27

$ cf push
Using manifest file /Users/mihovils/bluemix-test/manifest.yml

Updating app bluemix-travis-test in org PhytelDevelopment / space dev as mihovil.strujic@ibm.com...
OK

Uploading bluemix-travis-test...
Uploading app files from: /Users/mihovils/bluemix-test
Uploading 2M, 2382 files
Done uploading               
OK

Stopping app bluemix-travis-test in org PhytelDevelopment / space dev as mihovil.strujic@ibm.com...
OK

Starting app bluemix-travis-test in org PhytelDevelopment / space dev as mihovil.strujic@ibm.com...
Downloading sdk-for-nodejs_v3_16_1-20171207-1520...
Downloading liberty-for-java...
Downloading sdk-for-nodejs...
Downloading dotnet-core...
Downloading swift_buildpack...
Downloaded sdk-for-nodejs_v3_16_1-20171207-1520
Downloading noop-buildpack...
Downloaded dotnet-core
Downloaded sdk-for-nodejs
Downloading nodejs_buildpack...
Downloaded swift_buildpack
Downloading java_buildpack...
Downloading ruby_buildpack...
Downloaded liberty-for-java
Downloading go_buildpack...
Downloaded nodejs_buildpack
Downloading python_buildpack...
Downloading xpages_buildpack...
Downloaded ruby_buildpack
Downloading php_buildpack...
Downloaded go_buildpack
Downloading staticfile_buildpack...
Downloaded xpages_buildpack
Downloaded java_buildpack
Downloading binary_buildpack...
Downloaded noop-buildpack
Downloading swift_buildpack_v2_0_9-20171112-1715...
Downloaded python_buildpack
Downloading liberty-for-java_v3_14-20171013-1023...
Downloaded php_buildpack
Downloaded binary_buildpack
Downloaded liberty-for-java_v3_14-20171013-1023
Creating container
Downloaded staticfile_buildpack
Downloaded swift_buildpack_v2_0_9-20171112-1715
Successfully created container
Downloading app package...
Downloaded app package (2.4M)
Downloading build artifacts cache...
Downloaded build artifacts cache (482.9K)
Staging...
-----> IBM SDK for Node.js Buildpack v3.17-20180105-1100
       Based on Cloud Foundry Node.js Buildpack v1.5.24
-----> Creating runtime environment
       
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version (latest stable) via 'node-version-resolver'
       Installing IBM SDK for Node.js (6.12.2) from cache
       Using default npm version: 3.10.10
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules (exists - skipping)
       - bower_components (not cached - skipping)
-----> Building dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules
       body-parser@1.18.2 /tmp/app/node_modules/body-parser
       bytes@3.0.0 /tmp/app/node_modules/bytes
       content-type@1.0.4 /tmp/app/node_modules/content-type
       debug@2.6.9 /tmp/app/node_modules/debug
       ms@2.0.0 /tmp/app/node_modules/ms
       http-errors@1.6.2 /tmp/app/node_modules/http-errors
       depd@1.1.1 /tmp/app/node_modules/http-errors/node_modules/depd
       inherits@2.0.3 /tmp/app/node_modules/inherits
       setprototypeof@1.0.3 /tmp/app/node_modules/setprototypeof
       ee-first@1.1.1 /tmp/app/node_modules/ee-first
       qs@6.5.1 /tmp/app/node_modules/qs
       unpipe@1.0.0 /tmp/app/node_modules/unpipe
       type-is@1.6.15 /tmp/app/node_modules/type-is
       media-typer@0.3.0 /tmp/app/node_modules/media-typer
       cookie-parser@1.4.3 /tmp/app/node_modules/cookie-parser
       cookie-signature@1.0.6 /tmp/app/node_modules/cookie-signature
       accepts@1.3.4 /tmp/app/node_modules/accepts
       depd@1.1.2 /tmp/app/node_modules/depd
       statuses@1.4.0 /tmp/app/node_modules/statuses
       iconv-lite@0.4.19 /tmp/app/node_modules/iconv-lite
       on-finished@2.3.0 /tmp/app/node_modules/on-finished
       raw-body@2.3.2 /tmp/app/node_modules/raw-body
       mime-types@2.1.17 /tmp/app/node_modules/mime-types
       mime-db@1.30.0 /tmp/app/node_modules/mime-db
       cookie@0.3.1 /tmp/app/node_modules/cookie
       express@4.15.5 /tmp/app/node_modules/express
       negotiator@0.6.1 /tmp/app/node_modules/negotiator
       array-flatten@1.1.1 /tmp/app/node_modules/array-flatten
       content-disposition@0.5.2 /tmp/app/node_modules/content-disposition
       encodeurl@1.0.1 /tmp/app/node_modules/encodeurl
       escape-html@1.0.3 /tmp/app/node_modules/escape-html
       etag@1.8.1 /tmp/app/node_modules/etag
       finalhandler@1.0.6 /tmp/app/node_modules/finalhandler
       parseurl@1.3.2 /tmp/app/node_modules/parseurl
       statuses@1.3.1 /tmp/app/node_modules/finalhandler/node_modules/statuses
       fresh@0.5.2 /tmp/app/node_modules/fresh
       merge-descriptors@1.0.1 /tmp/app/node_modules/merge-descriptors
       methods@1.1.2 /tmp/app/node_modules/methods
       path-to-regexp@0.1.7 /tmp/app/node_modules/path-to-regexp
       proxy-addr@1.1.5 /tmp/app/node_modules/proxy-addr
       forwarded@0.1.2 /tmp/app/node_modules/forwarded
       ipaddr.js@1.4.0 /tmp/app/node_modules/ipaddr.js
       qs@6.5.0 /tmp/app/node_modules/express/node_modules/qs
       range-parser@1.2.0 /tmp/app/node_modules/range-parser
       send@0.15.6 /tmp/app/node_modules/send
       destroy@1.0.4 /tmp/app/node_modules/destroy
       mime@1.3.4 /tmp/app/node_modules/mime
       statuses@1.3.1 /tmp/app/node_modules/send/node_modules/statuses
       serve-static@1.12.6 /tmp/app/node_modules/serve-static
       statuses@1.3.1 /tmp/app/node_modules/express/node_modules/statuses
       utils-merge@1.0.0 /tmp/app/node_modules/utils-merge
       vary@1.1.2 /tmp/app/node_modules/vary
       morgan@1.9.0 /tmp/app/node_modules/morgan
       basic-auth@2.0.0 /tmp/app/node_modules/basic-auth
       safe-buffer@5.1.1 /tmp/app/node_modules/safe-buffer
       on-headers@1.0.1 /tmp/app/node_modules/on-headers
       pug@2.0.0-beta11 /tmp/app/node_modules/pug
       pug-code-gen@1.1.1 /tmp/app/node_modules/pug-code-gen
       constantinople@3.1.0 /tmp/app/node_modules/constantinople
       acorn@3.3.0 /tmp/app/node_modules/acorn
       is-expression@2.1.0 /tmp/app/node_modules/is-expression
       object-assign@4.1.1 /tmp/app/node_modules/object-assign
       js-stringify@1.0.2 /tmp/app/node_modules/js-stringify
       pug-runtime@2.0.3 /tmp/app/node_modules/pug-runtime
       pug-error@1.3.2 /tmp/app/node_modules/pug-error
       with@5.1.1 /tmp/app/node_modules/with
       acorn-globals@3.1.0 /tmp/app/node_modules/acorn-globals
       acorn@4.0.13 /tmp/app/node_modules/acorn-globals/node_modules/acorn
       source-map@0.4.4 /tmp/app/node_modules/source-map
       amdefine@1.0.1 /tmp/app/node_modules/amdefine
       is-promise@2.1.0 /tmp/app/node_modules/is-promise
       pug-walk@1.1.5 /tmp/app/node_modules/pug-walk
       uglify-js@2.8.29 /tmp/app/node_modules/uglify-js
       is-buffer@1.1.6 /tmp/app/node_modules/is-buffer
       repeat-string@1.6.1 /tmp/app/node_modules/repeat-string
       wordwrap@0.0.2 /tmp/app/node_modules/wordwrap
       pug-lexer@3.1.0 /tmp/app/node_modules/pug-lexer
       character-parser@2.2.0 /tmp/app/node_modules/character-parser
       function-bind@1.1.1 /tmp/app/node_modules/function-bind
       acorn@4.0.13 /tmp/app/node_modules/pug-lexer/node_modules/acorn
       pug-strip-comments@1.0.2 /tmp/app/node_modules/pug-strip-comments
       doctypes@1.1.0 /tmp/app/node_modules/doctypes
       pug-attrs@2.0.2 /tmp/app/node_modules/pug-attrs
       void-elements@2.0.1 /tmp/app/node_modules/void-elements
       pug-filters@2.1.5 /tmp/app/node_modules/pug-filters
       clean-css@3.4.28 /tmp/app/node_modules/clean-css
       commander@2.8.1 /tmp/app/node_modules/commander
       graceful-readlink@1.0.1 /tmp/app/node_modules/graceful-readlink
       jstransformer@1.0.0 /tmp/app/node_modules/jstransformer
       promise@7.3.1 /tmp/app/node_modules/promise
       asap@2.0.6 /tmp/app/node_modules/asap
       resolve@1.5.0 /tmp/app/node_modules/resolve
       path-parse@1.0.5 /tmp/app/node_modules/path-parse
       source-map@0.5.7 /tmp/app/node_modules/uglify-js/node_modules/source-map
       yargs@3.10.0 /tmp/app/node_modules/yargs
       camelcase@1.2.1 /tmp/app/node_modules/camelcase
       cliui@2.1.0 /tmp/app/node_modules/cliui
       center-align@0.1.3 /tmp/app/node_modules/center-align
       align-text@0.1.4 /tmp/app/node_modules/align-text
       kind-of@3.2.2 /tmp/app/node_modules/kind-of
       longest@1.0.1 /tmp/app/node_modules/longest
       lazy-cache@1.0.4 /tmp/app/node_modules/lazy-cache
       right-align@0.1.3 /tmp/app/node_modules/right-align
       decamelize@1.2.0 /tmp/app/node_modules/decamelize
       window-size@0.1.0 /tmp/app/node_modules/window-size
       is-regex@1.0.4 /tmp/app/node_modules/is-regex
       has@1.0.1 /tmp/app/node_modules/has
       is-expression@3.0.0 /tmp/app/node_modules/pug-lexer/node_modules/is-expression
       pug-linker@2.0.3 /tmp/app/node_modules/pug-linker
       pug-load@2.0.9 /tmp/app/node_modules/pug-load
       pug-parser@2.0.2 /tmp/app/node_modules/pug-parser
       token-stream@0.0.1 /tmp/app/node_modules/token-stream
       serve-favicon@2.4.5 /tmp/app/node_modules/serve-favicon
       uglify-to-browserify@1.0.2 /tmp/app/node_modules/uglify-to-browserify
       Installing any new modules (package.json)
-----> Installing App Management
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
       ├── body-parser@1.18.2
       ├── cookie-parser@1.4.3
       ├── debug@2.6.9
       ├── express@4.15.5
       ├── morgan@1.9.0
       ├── pug@2.0.0-beta11
       └── serve-favicon@2.4.5
       
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (1.8M)
Uploaded droplet (20.9M)
Uploading complete
Stopping instance ee6f2f17-ac19-40eb-88b5-eee3425f60ba
Destroying container
Successfully destroyed container

1 of 1 instances running

App started


OK

App bluemix-travis-test was started using this command `npm start`

Showing health and status for app bluemix-travis-test in org PhytelDevelopment / space dev as mihovil.strujic@ibm.com...
OK

requested state: started
instances: 1/1
usage: 128M x 1 instances
urls: bluemix-travis-test.mybluemix.net
last uploaded: Thu Jan 18 23:10:49 UTC 2018
stack: cflinuxfs2
buildpack: SDK for Node.js(TM) (ibm-node.js-6.12.2, buildpack-v3.17-20180105-1100)

     state     since                    cpu    memory          disk          details
#0   running   2018-01-18 06:11:54 PM   0.0%   15.6M of 128M   88.1M of 1G
```

**Comment by MichaelOrtho** [comment]
@BanzaiMan: `cf` client (current) is breaking it! This is when I updated `cf` CLI:
```
$cf -v
cf version 6.34.1+bbdf81482.2018-01-17

$cf push
Pushing from manifest to org PhytelDevelopment / space dev as mihovil.strujic@ibm.com...
Using manifest file /Users/mihovils/Documents/Code/IBM/bluemix-test/manifest.yml
Getting app info...
Updating app with these attributes...
  name:                bluemix-travis-test
  path:                /Users/mihovils/Documents/Code/IBM/bluemix-test
  buildpack:           SDK for Node.js(TM) (ibm-node.js-6.12.2, buildpack-v3.17-20180105-1100)
  command:             npm start
  disk quota:          1G
  health check type:   port
  instances:           1
  memory:              128M
  stack:               cflinuxfs2
  routes:
    bluemix-travis-test.mybluemix.net

Updating app bluemix-travis-test...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 1.96 MiB / 1.96 MiB [==================================================================================================================================================] 100.00% 4s

Waiting for API to complete processing files...
Job (e62657c8-e976-4287-abaf-03a7ee29f6d9) failed: The app upload is invalid: Symlink(s) point outside of root folder
FAILED
```

**Comment by MichaelOrtho** [comment]
@BanzaiMan Release of CF 9 days ago broke it because they added feature to push symlinks and they can be in `node_modules` folder. When I deleted node_modules folder before `cf push`, it passed.

But... `node_modules` are not part of codebase but is created during build, before deployment. Just before deployment starts, I thought Travis is clearing all artifacts created in Travis, but if `node_modules` is there, that means it is not cleaned. Thoughts?

**Comment by MichaelOrtho** [comment]
@BanzaiMan I have a workaround and a bug to report: Travis is not cleaning before deploy regardless of skip_cleanup setting.

So because of that, I added a workaround to manually clean artifacts created in TravisCI:
```
...
before_deploy:
- rm -R ./node_modules
...
```

**Comment by dshuffma-ibm** [comment]
fyi you can add `node_modules` to your `.cfignore` file.  or create the file if you do not have one. 

![image](https://user-images.githubusercontent.com/16085295/35130508-37b8228c-fc8f-11e7-8d54-ff133c1d135c.png)


that was all I needed.

**Comment by BanzaiMan** [comment]
Hi, @MichaelOrtho and @dshuffma-ibm, Thanks for the updates. So, it does sound like it is working as expected.

The question is: how should we fix it? Is documenting this change good enough? (In CloudFoundry and Bluemix documentation)

**Comment by blt9001** [comment]
I can confirm the `before_deploy` work-around works successfully for me on previously failing builds with this same issue.  Note - Prior to implementing the fix, I noticed I did have `skip_cleanup: true` in my .travis.yml within `deploy`, I tested setting to `false`, which did not fix the issue, ie - if the default cleanup is supposed to be set to false, it is not removing the node_modules directory, even when applied explicitly.

**Comment by BanzaiMan** [comment]
@blt9001 Did you have `node_modules` in `.gitignore`? The cleanup happens with `git` (`git stash --all`, `git stash pop`), so cleanup is ineffective in that case.

**Comment by MichaelOrtho** [comment]
@BanzaiMan I have `node_modules` in `.gitignore` and if you go to GitHub repository, you will see that there is no `node_modules` folder. 
What if we change `git stash` to `git checkout .`?

**Comment by blt9001** [comment]
@BanzaiMan Yes - from .gitignore:
`...
# Dependency directories
node_modules```

**Comment by BanzaiMan** [comment]
@MichaelOrtho I believe that change is ineffective. `git` ignores `node_modules` entirely, so `node_modules` will be left intact, and `cf` will balk when deploying.

It seems to me that educating users with this change and advising to add the offending directories to `.cfignore` is the best option.

**Comment by blt9001** [comment]
@BanzaiMan  - if this was a change to the cf ci that caused the issue - perhaps updating the  https://docs.travis-ci.com/user/deployment/bluemixcloudfoundry/ documentation with a note to confirm either a `before_deploy` removal script or an entry in .cfignore for the node_modules would be appropriate.    Would it effect the instructions regarding travis setup of bluemixcloudfoundry?

**Comment by BanzaiMan** [comment]
As @MichaelOrtho mentioned earlier in https://github.com/travis-ci/dpl/issues/734#issuecomment-357978383.

**Comment by MichaelOrtho** [comment]
@BanzaiMan Problem is different. `cf` added deployment of symlinks and as `node_modules` have symlinks, if that folder is present, `cf` will fail regardless where you are deploying it. It is not Bluemix specific.

I would assume that Bluemix CLI is built on CF so they will get that update sooner or later and then will start creating same issue.

One suggestion. Maybe during Travis process we can do this:
1) clone into folder X
2) copy X to Y
3) do all travis build/test/whatever
4) if `skip_cleaning`:`false`, deploy X and not Y

That way we would push original GIT content and 100% be sure that there is nothing else there.

**Comment by BanzaiMan** [comment]
@MichaelOrtho Thanks for the explanation. That makes a lot of sense.

Altering the build process the way you describe is a much larger change that requires a lot of consideration and verification. Frankly, I do not think that will work.

I believe the documentation update and user education is the right solution here.
