### ISSUE TITLE
Allow ELASTIC_BEANSTALK_LABEL to be set as a option as well

### ISSUE THREAD

**Issue by LorneCurrie** [travis-ci/dpl#738]
Currently, ELASTIC_BEANSTALK_LABEL is set as an env variable but would be good to allow a user to set the ELASTIC_BEANSTALK_LABEL as a option in the in the deploy provider.

**Comment by LorneCurrie** [comment]
@BanzaiMan are you happy for me to do a pull request for this issue?

**Comment by BanzaiMan** [comment]
Sure!

**Comment by LorneCurrie** [comment]
Hi, is there a way I can reopen this?  I would like to submit some code for this issue
