### ISSUE TITLE
Allow AWS access keys to be provided by env vars when deploying to Lambda

### ISSUE THREAD

**Issue by tdmalone** [travis-ci/dpl#745]
When deploying to [OpsWorks](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/ops_works.rb#L13-L38), [ElasticBeanstalk](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/elastic_beanstalk.rb#L17-L31), [S3](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/s3.rb#L21-L34) and [CodeDeploy](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/code_deploy.rb#L16-L31), the AWS access keys can be provided via either option, or environment variable.

Lambda deployments [only directly support options](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/lambda.rb#L15-L20).

Would it be possible for environment variable support for `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to be extended to Lambda uploads?

**Comment by gebn** [comment]
I've just unexpectedly hit this limitation. As environment variables can be updated via the Travis API, this would make automatic key rotations much easier.

**Comment by tdmalone** [comment]
Thanks for the PR!

In the meantime until the PR is merged, I realised an easy workaround: you can just set eg. secret_access_key to $AWS_SECRET_ACCESS_KEY and provide it via an env var anyway.

**Comment by gebn** [comment]
Ah sweet, thanks for the heads up! Confirmed this works:

    deploy:
      provider: lambda
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      ...
