### ISSUE TITLE
Github Pages support for other repos (eg {user}.github.io)

### ISSUE THREAD

**Issue by tobylane** [travis-ci/dpl#751]
I'd like to be able to set a target repo slug, say tobylane/tobylane.github.io

If this had the access it could make the repo too?

**Comment by BanzaiMan** [comment]
I _think_ the `project_name` option is supposed to allow you to do this. (The documentation lacks examples, so it's a little hard to deduce this, but if my reading of the source code is right, it should do the job.)

**Comment by tobylane** [comment]
I set `project_name: tobylane/tobylane.github.io` and the deploy says `Deploy tobylane/tobylane.github.io to github.com/tobylane/CorsixTH.git:gh-pages` but the commit was as if I hadn't added that line.

**Comment by BanzaiMan** [comment]
@tobylane https://travis-ci.org/tobylane/CorsixTH/jobs/338591036#L2279 Thanks for the report. I think this is a separate bug, where the provider assumes that that the local branch name and the deployment target branch are identical. (In this case, you are building the `docs2` branch but trying to push to the `gh-pages` branch.)

If you switch the branch to `gh-pages`, the deployment should work.

**Comment by tobylane** [comment]
Switch the target branch or the source? I set the target and source branches [in this commit.](https://github.com/tobylane/CorsixTH/blob/7daa4b4f08d823f6bd55b8e411c63952be77444a/.travis.yml) but the deploy line is still backwards.

**Comment by BanzaiMan** [comment]
Use the branch named `gh-pags`, and deploy from there.

**Comment by tobylane** [comment]
It still overwrites the local branch.

**Comment by BanzaiMan** [comment]
What do you mean, "still"? This is the first time you mention overwriting the local branch.

The deployment to the `gh-pages` branch is now working for you, no? https://github.com/tobylane/CorsixTH/tree/gh-pages

**Comment by BanzaiMan** [comment]
Actually, this was working the whole time. https://github.com/tobylane/CorsixTH/commits/gh-pages

**Comment by tobylane** [comment]
My intent was to write into another repo. The deploy line I quoted correctly worked out I wanted to move between repos but not the order, the rest of the deploy script doesn't appear to have done anything to tobylane/tobylane.github.io.

**Comment by BanzaiMan** [comment]
Oh, I'm so sorry. I think I misunderstood what you were asking, even thought you clearly stated this.

The option you want is `repo`, not `project_name`. https://docs.travis-ci.com/user/deployment/pages#Further-configuration

(I still believe you need to use the `gh-pages` branch; you'll have to tweak this, because of my bad advice earlier.)

**Comment by tobylane** [comment]
I can't use gh-pages as a source branch as Travis will never see it, right?

Thank you, works as expected. I have to push to master in a .github.io repo and docs2 to master worked.

**Comment by webknjaz** [comment]
@BanzaiMan project name is only used for commit message
https://github.com/travis-ci/dpl/blob/e6a53d8/lib/dpl/provider/pages.rb#L176

@tobylane I think, you can explicitly tell travis to not ignore your gh-pages if you need this: https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches

P.S. Feel free to contribute your use case to https://github.com/travis-ci/docs-travis-ci-com/blob/master/user/deployment/pages.md if you find smth unclear

**Comment by tobylane** [comment]
I don't understand it well enough to edit docs.

The commit message is `Deploy tobylane/tobylane.github.io to github.com/tobylane/tobylane.github.io.git:master` but I think it should be more like `Deploy tobylane/CorsixTH:docs2 to tobylane/tobylane.github.io:master`

**Comment by webknjaz** [comment]
Sounds reasonable. I will consider changing it.
