### ISSUE TITLE
Allow absolute path to be used in GitHub Pages deployment

### ISSUE THREAD

**Issue by brianhou** [travis-ci/dpl#753]
I'd like the `local-dir` option to support absolute paths in addition to relative paths. If this sounds reasonable, I'd be happy to open a PR.

**Comment by BanzaiMan** [comment]
Yes, please!

**Comment by webknjaz** [comment]
@brianhou Sounds fair. I guess your use case is running dpl manually outside of Travis?
Please tag me for review in your PR. TIA.

**Comment by webknjaz** [comment]
unstale

**Comment by webknjaz** [comment]
unstale
