### ISSUE TITLE
Broken gh-pages deployment

### ISSUE THREAD

**Issue by ldez** [travis-ci/dpl#762]
We (@mmatur and me) may have found an issue on gh-pages deployment.

Since version `dpl-1.9.1.travis.2611.5` our [deployment](https://travis-ci.org/containous/traefik/builds/347825463#L1633) on gh-pages is no more working.
We have this error message `gh-token must be provided for Pages provider to work.`

We have done no change on our travis configuration. And the last green deployment was with [version](https://travis-ci.org/containous/traefik/builds/346774791#L1711) `dpl-1.8.48.travis.2486.5`

We tested on several repositories (organization or personal)  and we always reproduce the same problem.

**Comment by BanzaiMan** [comment]
Drop `edge: true` for now.

**Comment by BanzaiMan** [comment]
@ldez Where do you see this error message? It might have been there originally, but the linked job has been restarted and the error is now different.

**Comment by ldez** [comment]
@BanzaiMan here https://travis-ci.org/containous/traefik/builds/347267764#L1619

**Comment by BanzaiMan** [comment]
OK. https://travis-ci.org/containous/traefik/builds/347825463#L1633 is weird, but the issue persists still https://travis-ci.org/BanzaiMan/travis_production_test/builds/348385535#L465.

**Comment by BanzaiMan** [comment]
This should be fixed by https://github.com/travis-ci/dpl/commit/b7d4d08d60f1a45da06a81a3babf3a00719591cb (https://travis-ci.org/travis-ci/dpl/builds/348388928; `1.9.1.travis.2669.5` and later). Test: https://travis-ci.org/BanzaiMan/travis_production_test/builds/348388556#L362

**Comment by BanzaiMan** [comment]
This is available now. Please restart the failing build, or push a new commit with `edge: true`, whichever is more preferable.

**Comment by ldez** [comment]
I restarted a build but it always fail https://travis-ci.org/containous/traefik/builds/347825463#L1673

**Comment by BanzaiMan** [comment]
Interesting. I was finally able to reproduce it; https://travis-ci.org/BanzaiMan/travis_production_test/builds/348411309 It appears to me that `edge` now doesn't work as a second deployment provider.

**Comment by BanzaiMan** [comment]
It's a separate issue, so it should be tracked separately. By itself, `page` should work.

**Comment by BanzaiMan** [comment]
@ldez See https://github.com/travis-ci/dpl/issues/763; use `edge: true` everywhere.
