### ISSUE TITLE
Uploading to S3 takes time with many files

### ISSUE THREAD

**Issue by mboudreau** [travis-ci/dpl#765]
Hi Travis Team,

I noticed today that when I'm doing an upload to s3 that includes many thousands of files (214mb total), Travis seems to takes a long time to accomplish its task.  I looked through the codebase and found that [Travis is uploading the files synchronously on a singe thread](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/s3.rb#L57).  This wouldn't be an issue for most projects which probably only has a few hundred files or just a few big ones, but you can definitely see it crawl when uploading 3200 files which took our build 1h7m to accomplish.

My suggestion would be to make the S3 provider multithreaded when it comes to uploading the files. [ I found this example online that shows how this can be done easily enough](https://gist.github.com/fleveque/816dba802527eada56ab) and would increase the performance of the Travis upload drastically.

My team would be creating a PR for this change, but wanted to know if the Travis Team is okay with the idea and how many threads would be okay for it to use as we don't know the hardware the CI boxes have.

Cheers.

**Comment by BanzaiMan** [comment]
Hello there! Indeed, this sounds like an awesome improvement. Let me know if I can be of help.

**Comment by mboudreau** [comment]
@BanzaiMan You haven't answered my question around how many threads would it be okay for travis to have for this?  I was thinking 10 to start off with.

**Comment by BanzaiMan** [comment]
Let's be conservative, and start with something like 5. Having it configurable is a good idea, and we change the default in the future, if a higher value proves to be manageable.

**Comment by mboudreau** [comment]
Great, thanks!

**Comment by BanzaiMan** [comment]
#768 has been merged, and it will be in the 1.9.2 release.
