### ISSUE TITLE
Deploy error with dpl 1.9.1

### ISSUE THREAD

**Issue by rafael-nogueras** [travis-ci/dpl#766]
I am seeing the following error when my build attempts to deploy:

```
$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl --pre

Fetching: dpl-1.9.1.travis.2679.5.gem (100%)
Successfully installed dpl-1.9.1.travis.2679.5
1 gem installed

dpl.1
Installing deploy dependencies

ERROR:  Could not find a valid gem 'dpl-script' (= 1.9.1.travis.2679.5) in any repository
ERROR:  Possible alternatives: lscript, ops_script, tpscript, applescript, bin_script

/home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- dpl/provider/script (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.9.1.travis.2679.5/lib/dpl/provider.rb:92:in `rescue in block in new'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.9.1.travis.2679.5/lib/dpl/provider.rb:67:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.9.1.travis.2679.5/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.9.1.travis.2679.5/lib/dpl/provider.rb:66:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.9.1.travis.2679.5/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.9.1.travis.2679.5/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.9.1.travis.2679.5/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.6/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.6/bin/dpl:23:in `<main>'

failed to deploy
```

This started happening all of a sudden (i.e. with no changes in the `.travis.yml` file) on March 6th, some time in the evening; I suspect it has to do with the fact that version 1.9.1 of the `dpl` gem was published on that same day (https://rubygems.org/gems/dpl/versions/1.9.1.travis.2679.5).

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by jmauro** [comment]
Hello @BanzaiMan, we are encountering the exact same issue: [librenms](https://travis-ci.org/criteo-cookbooks/librenms)

**Comment by BanzaiMan** [comment]
Actually, I figured out why. The version in question didn't have accompanying provider gems built and released, so deployment failed. I've yanked the bad versions, and fixed the deployment process for the pre-releases, so we should be good now (`1.9.1.travis.2689.5` and later).

**Comment by jmauro** [comment]
Hello @BanzaiMan,
Thanks for fixing this error but we are still having issue it seems this PR has not been included in the gem: https://github.com/travis-ci/dpl/pull/690/files

**Comment by BanzaiMan** [comment]
@jmauro In the logs, you see that your build is using `chef` 12.22.1. https://travis-ci.org/criteo-cookbooks/librenms/builds/350899868#L1275 If this version is not sufficient to deploy your code, https://github.com/travis-ci/dpl/pull/690 would not help you, as it would have chosen the same version.

**Comment by BanzaiMan** [comment]
Or, maybe this line is supposed to fix it? https://github.com/travis-ci/dpl/pull/690/files#diff-b47ed76e37137357d0384cd7c36eb3ffR13s

**Comment by dev-head** [comment]
same issue as reported for us running an enterprise version.

**Comment by BanzaiMan** [comment]
@dev-head What issue are you having? Deployment issues with pre-release 1.9.1.travis.X.Y should be fixed. If it's about chef_supermarket, it never worked, and it should be treated separately.

**Comment by rafael-nogueras** [comment]
I can confirm the builds are running just fine for me now. Thanks for fixing it so quickly, guys! :-)
