### ISSUE TITLE
Unable to push on gh-pages

### ISSUE THREAD

**Issue by ldez** [travis-ci/dpl#771]
Since the deployment of 1.9, the gh-pages provider is broken.

```
Couldn't push the build to github.com/containous/traefik.git:gh-pages
```

https://travis-ci.org/containous/traefik/builds/351290353

**Comment by BanzaiMan** [comment]
Closing as a duplicate of #767, which itself is a duplicate of https://github.com/travis-ci/travis-ci/issues/9312.
