### ISSUE TITLE
Heads-up about new PyPI

### ISSUE THREAD

**Issue by brainwane** [travis-ci/dpl#779]
I'm the project manager for the new Python Package Index (Warehouse), which is currently in pre-production at http://pypi.org/ . On [the Warehouse roadmap](https://wiki.python.org/psf/WarehouseRoadmap), it looks like the full switch will happen sometime in April, so here's a heads-up about what's changing.

The full switch will include redirecting browser and `pip install` traffic from the old site; then, sometime in late April or early May, the legacy site will be entirely shut down.

dpl will probably be able to seamlessly switch to the new site, and thanks to redirects, may not have to change anything immediately. [Here's a migration guide.](https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi) Note that there is now no need to "register" a project before initial upload.

As of the middle of last year (as you saw in #655), package releases must go through the new PyPI, and as of late February, new user account registration is only available on the new site.

Things that are going away, or already have (sometimes for policy or spam-fighting reasons), include:

* pythonhosted.com documentation hosting (pypa/warehouse#582)
* [download counts visible in the API](https://warehouse.readthedocs.io/api-reference/xml-rpc/#changes-to-legacy-api) (instead, use [the Google BigQuery service](https://packaging.python.org/guides/analyzing-pypi-package-downloads/))
* package maintainers being able to upload a new release via the web UI (instead, the recommended command-line tool is [Twine](http://twine.readthedocs.io/), which I believe you already use)
* package maintainers being able to log in and update release descriptions via the web UI (to update release metadata, they need to upload a new release; see [distutils-sig discussion](https://mail.python.org/pipermail/distutils-sig/2017-December/031826.html))
* users being able to upload a package without verifying their email address with PyPI first

Thank you for integrating with PyPI, and please [let us know](https://github.com/pypa/warehouse/issues/new) if you have any questions or problems with the new site!

Followup to #655, slightly related to #727 and maybe #377.

**Comment by webknjaz** [comment]
Now the default is https://pypi.org/, so https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/pypi.rb#L4 should be switched to it.

**Comment by ssbarnea** [comment]
pypi upload seems to be broken on travis for months. https://github.com/travis-ci/travis-ci/issues/9848

**Comment by webknjaz** [comment]
Not at all. I'm using it in numerous projects. Maybe that bug is environment-specific.

**Comment by ssbarnea** [comment]
@webknjaz I am trying to make dpl make a pypi release for more than a week. Most problems seem to be related to the fact that code is attempting to install pip/twine/... without --user and not running as root... thus failing to upgrade pip. 

See: https://github.com/pycontribs/jira/blob/master/.travis.yml
Attempt to fix: https://github.com/travis-ci/dpl/pull/834

**Comment by webknjaz** [comment]
It's related to the fact that in `language: python` Travis creates a virtualenv, but you use `language: nodejs` without `sudo: required`. `--user` might help, but I'm not sure about compatibility.
Now, I recommend:
```yaml
jobs:
  fast_finish: true
  include:
  - stage: Deploy to PYPI
    if: tag IS present
    language: python
    install: skip
    script: skip
    deploy:  # your config
```

**Comment by ssbarnea** [comment]
@webknjaz Thanks, this may explain the weird behaviour where sometimes it was working, sometimes it didn't. Still, I think that the python deployer should work regardless the values of language tag. Lucky for me I already know what kind of trick is needed because I used it recently. This is more of pip bug (or lack of feature) where you want --user for non venv, and for venv you want to avoid it. Now pip has no flag for this and you need to use venv detection and define variable based on this. I updated my fork to do this and soon we will find out if it works well or not.

**Comment by webknjaz** [comment]
Sure, I agree with the problem :) Just wanted to share a workaround. I think I saw an issue about the same problem you faced with somewhere around.

**Comment by webknjaz** [comment]
unstale

**Comment by webknjaz** [comment]
unstale

**Comment by brainwane** [comment]
Does https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi help?

**Comment by webknjaz** [comment]
It looks like no server is hardcoded anymore: https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/pypi.rb
Thanks to @ssbarnea (Ref https://github.com/travis-ci/dpl/pull/834)

**Comment by svenfuchs** [comment]
can this be closed, or is this still an issue? https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/pypi.rb uses `https://upload.pypi.org/legacy/` as the default server, which can be overwritten.

**Comment by brainwane** [comment]
I believe this is now resolved -- thanks everyone!
