### ISSUE TITLE
my CloudFiles Deploy seems to be uploading twice

### ISSUE THREAD

**Issue by pr1ntr** [travis-ci/dpl#781]
I am not sure what is happening here but I am lead to believe my config is making Travis upload the same files twice to CloudFiles.

How I came to this conclusion is because CloudFiles CDN is serving me the uncompressed versions of the same files (all my files are hashed). But on the container, they are the correct size (not cached). The only way to get them to report correctly is to manually purge them and they are served at the right size.

My build compresses the files in place before the deploy step which makes this extra strange. (eg.,  
`/build/static/media/* -> compress -> /build/static/media/*` ) I don't know if thats causing any issues.

I am not really sure if Travis is the issue but maybe someone can look at my config and point out some red flags. Thanks.

My .travis.yml
```branches:
  only:
    - /^master$/
    - /^deploy\/staging/
    - /^deploy\/develop/
    - /^deploy\/production/

sudo: false
dist: trusty
addons:
    apt:
        packages:
            - sshpass
language: node_js
node_js:
  - "8.9.3"
before_deploy: "cd build"
deploy:
  provider: cloudfiles
  username: $RACKSPACE_USERNAME
  api_key: $RACKSPACE_API_KEY
  region: $RACKSPACE_REGION
  container: $RACKSPACE_CONTAINER_NAME
  skip_cleanup: true
  on:
    branch: deploy/production


before_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then export CONFIG_ENV="develop";
    elif [ "$TRAVIS_BRANCH" == "deploy/develop" ]; then export CONFIG_ENV="develop";
    elif [ "$TRAVIS_BRANCH" == "deploy/staging" ]; then export CONFIG_ENV="staging";
    elif [ "$TRAVIS_BRANCH" == "deploy/production" ]; then export CONFIG_ENV="production";
    else export CONFIG_ENV="cancel"; fi;
  - yarn
script:
  - if [ "$ENV" != "cancel" ]; then
      CONFIG_ENV=$CONFIG_ENV yarn configure;
      export $(cat .env | grep -v ^# | xargs -0);
      CI=false yarn build;
      sshpass -p "$SSH_PASS" scp -r -o StrictHostKeyChecking=no build/*  "$SSH_USER@$SSH_HOST:$FOLDER";
      echo "Uploaded Build to $CONFIG_ENV";
    fi;
```
Travis Output:
```[0K
[32;1mThe command "if [ "$ENV" != "cancel" ]; then CONFIG_ENV=$CONFIG_ENV yarn configure; export $(cat .env | grep -v ^# | xargs -0); CI=false yarn build; sshpass -p "$SSH_PASS" scp -r -o StrictHostKeyChecking=no build/*  "$SSH_USER@$SSH_HOST:$FOLDER"; echo "Uploaded Build to $CONFIG_ENV"; fi;" exited with 0.[0m
travis_fold:start:before_deploy
[0Ktravis_time:start:2d16c51e
[0K$ cd build

travis_time:end:2d16c51e:start=1521081476334136860,finish=1521081476338388271,duration=4251411
[0Ktravis_fold:end:before_deploy
[0Ktravis_fold:start:dpl_0
[0Ktravis_time:start:14ff9e82
[0K$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.9.1
1 gem installed

travis_time:end:14ff9e82:start=1521081480805080309,finish=1521081482173407484,duration=1368327175
[0Ktravis_fold:end:dpl_0
[0Ktravis_time:start:310133f0
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m
Successfully installed net-ssh-4.2.0
Successfully installed mime-types-data-3.2016.0521
Successfully installed mime-types-3.1
Successfully installed mini_portile2-2.3.0
Building native extensions. This could take a while...
Successfully installed nokogiri-1.8.2
Successfully installed builder-3.2.3
Successfully installed excon-0.60.0
Successfully installed formatador-0.2.5
Successfully installed fog-core-2.1.0
Successfully installed multi_json-1.13.1
Successfully installed fog-json-1.1.0
Successfully installed fog-xml-0.1.3
Successfully installed ipaddress-0.8.3
Successfully installed fog-rackspace-0.1.5
Successfully installed dpl-cloud_files-1.9.1
15 gems installed

!!! Rackspace Cloud Files support is experimental !!!


travis_fold:end:dpl.1
Authenticated as [secure]
travis_fold:start:dpl.2
[33mPreparing deploy[0m

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m

travis_fold:end:dpl.3

travis_time:end:310133f0:start=1521081482180493089,finish=1521081576924607638,duration=94744114549
[0K
Done. Your build exited with 0.```

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by pr1ntr** [comment]
Can I do that for a private repo?

**Comment by BanzaiMan** [comment]
I don’t understand the question. Can you do what?

**Comment by pr1ntr** [comment]
https://api.travis-ci.com/v3/job/114761925/log.txt?log.token=-tJCyWlPGu_1KJlgHunKIw

**Comment by BanzaiMan** [comment]
Sorry, I removed the URL, which is potentially sensitive. I got the information I need, so I’ll investigate and respond shortly.

**Comment by pr1ntr** [comment]
Thank you

**Comment by BanzaiMan** [comment]
I reviewed the deployment code (https://github.com/travis-ci/dpl/blob/v1.9.1/lib/dpl/provider/cloud_files.rb#L29-L31) and the logs, but so far nothing indicates to me that a single file is uploaded multiple times. Could you list files in the `build` directory before the deployment by adding `ls` to `before_deploy`?

**Comment by pr1ntr** [comment]
So this is only the production deploy so I can't really do a dry run of this. Can I just show you what its like on the file sys or do you need to see it in the travis log? I can confirm that the build script only generates one set of files.

**Comment by pr1ntr** [comment]
Maybe add a debug prop for this provider so we can see a more verbose output?

**Comment by BanzaiMan** [comment]
@pr1ntr Sure, we can try that.

```yaml
deploy:
  provider: cloud_files
  edge:
    branch: cloudfiles-verbose
  ⋮
```

**Comment by pr1ntr** [comment]
I wish I had seen this like 5 min ago before I did the production deployment. I did add the directory structure to the deploy. Can be seen here: https://api.travis-ci.com/v3/job/115356703/log.txt?log.token=FJAxCoz_9eUxXhjR3b77cw

**Comment by pr1ntr** [comment]
I'll try the verbose flash on the next one, however, I haven't seen the issue since. So maybe a fluke? Let's keep this open for a few more days and if its fine we can close.

**Comment by pr1ntr** [comment]
I guess this is no longer an issue. Thanks @BanzaiMan
