### ISSUE TITLE
dpl requires Ruby version >= 2.2

### ISSUE THREAD

**Issue by minotogna** [travis-ci/dpl#782]
Hello,

is the dpl ruby version changed?

If i run this, i get the following error:

$ gem install dpl
ERROR:  Error installing dpl:
	dpl requires Ruby version >= 2.2.

**Comment by minotogna** [comment]
This might be a problem in debian jessie, for which available ruby version is 2.1.5

https://packages.debian.org/jessie/ruby

**Comment by BanzaiMan** [comment]
Please ask them to update to Ruby >= 2.2, or use `dpl` 1.8.47.
