### ISSUE TITLE
Lambda provider doesn't support JAR files for Java deployment

### ISSUE THREAD

**Issue by DwayneJengSage** [travis-ci/dpl#798]
Following instructions here:
https://github.com/travis-ci/dpl#lambda

This is my .travis.yml:
https://github.com/Sage-Bionetworks/BridgeMasterScheduler/blob/445815b67332535e63e5238d92a1e311363cb65e/.travis.yml

We use the Maven Shade plugin to generate an "uber-jar" to deploy to Lambda. Uploading this JAR manually to Lambda seems to work just fine. However, when we try to deploy using Travis, we get a ClassNotFoundException:

Class not found: org.sagebionetworks.bridge.scheduler.SchedulerLauncher: java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: org.sagebionetworks.bridge.scheduler.SchedulerLauncher
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)

It looks like DPL is always zipping the file (https://github.com/travis-ci/dpl/blob/32b6a836ed7c69a2e306362d46a2c831f6f06885/lib/dpl/provider/lambda.rb#L134). I've manually confirmed that zipping the JAR file and uploading it to Lambda gets us the same error.

Are there any known workarounds? Will you support JAR files for Lambda deployments through Travis?

**Comment by BanzaiMan** [comment]
Ruby SDK doesn't seem to support anything but ZIP archives.

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Lambda/Types/FunctionCode.html

Can you not create a ZIP file?

**Comment by jgriffith** [comment]
I am also experiencing this same behavior.   JAR files are zipped by dpl when they shouldn't be.

**Comment by BanzaiMan** [comment]
Is there a list of file types that Lambda is supposed to accept?

As I mentioned earlier, the Ruby client only accepts ZIP files (via `zip_file` option) https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Lambda/Client.html#update_function_code-instance_method, so I'm not sure how one is supposed to achieve what @DwayneJengSage mentioned in the description:

> Uploading this JAR manually to Lambda seems to work just fine.

**Comment by jgriffith** [comment]
On this page of the AWS docs it says you can upload a JAR file.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-java-how-to-create-deployment-package.html

"Your deployment package can be a .zip file or a standalone jar; it is your choice."

I think this is the line of code should have an or statement, "zip or jar"
https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/lambda.rb#L135

Without the or statement, the dpl function zips the .jar file an breaks the lambda deployment.

**Comment by DwayneJengSage** [comment]
@BanzaiMan The Maven Shade plugin generates a JAR file. It would take a significant amount of extra configuration to make a ZIP file instead.

@jgriffith I'll give that workaround a try, thanks!

**Comment by DwayneJengSage** [comment]
Workaround was provided, but issue was not solved. Please re-open.
