### ISSUE TITLE
DPL deploys to S3 with an empty content-type if it can't automatically detect it

### ISSUE THREAD

**Issue by sylveon** [travis-ci/dpl#803]
This makes uploading obscure binary file types a pain, because they end up not downloaded by the browser and instead showed to the user as plaintext (like [this](https://files.charlesmilette.net/HoarseEntireOcelot)). It should fallback to `application/octet-stream` instead.

![](https://files.charlesmilette.net/SatisfiedGrowlingCattle)

Here's the complete build log: https://travis-ci.org/sylveon/terminology-themes/builds/370328797

**Comment by peternewman** [comment]
I think this is a duplicate of https://github.com/travis-ci/dpl/issues/519 and fixed in #529 .

**Comment by sylveon** [comment]
Indeed, it seems like so. But the branch referred in the issue is outdated, so using it right now would probably create more trouble than fixed. Is there possibility of updating this PR with master so I can try it out, @BanzaiMan?

**Comment by BanzaiMan** [comment]
Closing as a duplicate.
