### ISSUE TITLE
Run additional commands specified via `run:` when Heroku deployment is over

### ISSUE THREAD

**Issue by cotsog** [travis-ci/dpl#806]
This was raised by @johangus [in this ticket](https://secure.helpscout.net/conversation/560649627/69974?folderId=30784).

It seems it can happen that we will run the commands found in the `run:` key of the Heroku deployment before the deployment is actually terminated on the server.

It would be nice to ensure the deployment is done when running the commands.

**Comment by BanzaiMan** [comment]
I am not sure if this analysis is correct:

> It seems it can happen that we will run the commands found in the `run:` key of the Heroku deployment before the deployment is actually terminated on the server.

After triggering the build via Heroku API, we verify that the deployment is now returning success: https://github.com/travis-ci/dpl/blob/v1.9.6/lib/dpl/provider/heroku/api.rb#L53-L67

The fact that the code execution went on to `run` means that Heroku returned success.

**Comment by cotsog** [comment]
We've added a note in the docs explaining that even though the deployment was successful on Heroku, it might not have replaced the previous one yet. See https://github.com/travis-ci/docs-travis-ci-com/pull/1808.
