### ISSUE TITLE
`api': uninitialized constant RHC (NameError)

### ISSUE THREAD

**Issue by tim-walton** [travis-ci/dpl#810]
Following the instructions to configure for OpenShift deployment, I am getting the following when trying to deploy from travis-ci:

```
Successfully installed rhc-1.38.7
Fetching: dpl-openshift-1.9.6.gem
Fetching: dpl-openshift-1.9.6.gem (100%)
Fetching: dpl-openshift-1.9.6.gem (100%)
Successfully installed dpl-openshift-1.9.6
15 gems installed

travis_fold:end:dpl.1
travis_fold:start:dpl.2
[33mPreparing deploy[0m

travis_fold:end:dpl.2
No stash entries found.
/home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-openshift-1.9.6/lib/dpl/provider/openshift.rb:14:in `api': uninitialized constant RHC (NameError)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-openshift-1.9.6/lib/dpl/provider/openshift.rb:18:in `user'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-openshift-1.9.6/lib/dpl/provider/openshift.rb:26:in `check_auth'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:182:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:181:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```
[https://travis-ci.org/tim-walton/kangs](https://travis-ci.org/tim-walton/kangs)

**Comment by BanzaiMan** [comment]
Sorry for the troubles.

See #705. We should drop OpenShift.

**Comment by tim-walton** [comment]
Well at least its not me. I'd like to tackle this issue.

**Comment by tim-walton** [comment]
Awesome, already started.

**Comment by mfrancis95** [comment]
I'm getting this issue. Would like to see it fixed.

**Comment by laszlo-laszlo** [comment]
I have the same issue. My .travis.yml is:
sudo: required
services:
- docker
before_install:
- docker build -t laszlolaszlo/docker-react -f Dockerfile.dev .
script:
- docker run laszlolaszlo/docker-react npm run test -- --coverage
deploy:
  provider: openshift
  user: "$OPENSHIFT_USER"
  password:
    secure: "$OPENSHIFT_PASSWD"
  app: docker-react
  domain: "$OPENSHIFT_DOMAIN"
  on:
    repo: laszlo-laszlo/docker-react

**Comment by Agusnez** [comment]
Any updates on this? I'm having the same issues. When using [dpl2](https://docs.travis-ci.com/user/deployment-v2/providers/openshift/#status) logs says that my user doesn't have access to X project.
