### ISSUE TITLE
Visual Studio Code Extension Publishing

### ISSUE THREAD

**Issue by nikeee** [travis-ci/dpl#820]
It would be nice if one can publish VSCode Extensions directly from Travis.

The process is pretty similar to npm deployment: https://code.visualstudio.com/docs/extensions/publish-extension

**Comment by hanjoosten** [comment]
Not sure if it helps, but did you look into [this documentation](http://jasonpoon.ca/2016/11/15/continuous-delivery-of-visual-studio-code-extensions/)?

**Comment by nikeee** [comment]
I'm aware that it's possible to configure it the right way. However, in this FR, it is proposed to offer a similar experience like the npm publishing:
https://docs.travis-ci.com/user/deployment/npm/

As the deployment process is pretty similar to NPM packages (VSC extensions are like NPM packages), we could provide it directly as configuration.

**Comment by hanjoosten** [comment]
It would be nice. I am currently struggling getting my repo deployed in a proper way.

**Comment by nikeee** [comment]
I think this issue is still valid.

**Comment by nikeee** [comment]
I'd like to take on this issue by adding a modified copy of the [`npm` Provider](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/npm.rb). Is there anything to be aware of?

**Comment by nikeee** [comment]
It's still valid, I think.

**Comment by mehrad77** [comment]
Still valid I guess

**Comment by svenfuchs** [comment]
if it is, i guess it needs to be reopened :)

**Comment by mehrad77** [comment]
oh no, don't close it

**Comment by svenfuchs** [comment]
@mehrad77 would you like to take a shot at this? not using Visual Studio Code over here ...

**Comment by mehrad77** [comment]
is it really solved?

**Comment by baldimir** [comment]
It would be nice to have this.
