### ISSUE TITLE
npm deploy step uses encrypted email / API key

### ISSUE THREAD

**Issue by astorije** [travis-ci/dpl#825]
Context: I made 2 releases to npm using Travis tonight, one went fine and the other did not.

**The one that went fine:**

- [Travis config](https://github.com/thelounge/thelounge/blob/master/.travis.yml#L43-L46)
- [Job that deployed OK](https://travis-ci.org/thelounge/thelounge/jobs/393945780#L630) (via `travis-ci.org`)

**The one that did not deploy:**

- [Travis config](https://github.com/thelounge/thelounge-theme-classic/blob/master/.travis.yml#L12-L15)
- [Job that failed to deploy](https://travis-ci.com/thelounge/thelounge-theme-classic/builds/76639090#L507) (via `travis-ci.com`)

A you can see, the latter one tried to login to the npm registry using the encrypted keys. Do you have any clue why it did not use the decrypted email / API key?

FYI, those 2 encrypted values for the failed build were obtained by doing:

```sh
travis encrypt "j*e@a*i.fr" --add deploy.email
travis encrypt 254...-...-...491 --add deploy.api_key
```

Thanks in advance!

**Comment by webknjaz** [comment]
@astorije I assume you moved your project from .org to .com and have leftover `secure: `, which worked on .org. And you didn't change that after the migration.

At .com you have a separate project entity for building your repo, also having a different symmetric key, which it uses to decrypt your variables. That said, it decrypts your old values into malformed random strings rather then what you put there originally.
You need to regenerate those secret values with a new key:

```bash
REPO_USER={{ YOUR_REPO_USER }}
REPO_NAME={{ YOUR_REPO_NAME }}
travis login -r "${YOUR_REPO_USER}/${REPO_NAME}" --api-endpoint 'https://api.travis-ci.com/'
travis encrypt -r "${YOUR_REPO_USER}/${REPO_NAME}" --api-endpoint 'https://api.travis-ci.com/'
```

**Comment by astorije** [comment]
Hey @webknjaz,

> @astorije I assume you moved your project from .org to .com and have leftover secure:, which worked on .org. And you didn't change that after the migration.

In fact no, this is a brand new set up that was not on .org, so these values are new.
However, I did not set `--api-endpoint` so I'll try new values with that.

> That said, it decrypts your old values into malformed random strings rather then what you put there originally.

If you look at the config and the console output, it did not even decrypt into random strings, the outputted values are exactly the ones in the config.

**Comment by webknjaz** [comment]
Oh, I see, so I've guessed the wrong issue :)
But when you go for secure remember to pass entrypoint explicitly, because the CLI does the wrong assumptions.

**Comment by webknjaz** [comment]
Okay, after checking log and config I think that it is encrypted wrong again. Use explicit entrypoint please.

**Comment by astorije** [comment]
Yes! That worked when using the correct endpoint, I had no idea, thanks!

**Comment by webknjaz** [comment]
Yeah, I stepped onto this when I completely migrated one of the orgs I maintain and after some experimenting I came up with this workaround :)
I'm glad I could help you :tada:
