### ISSUE TITLE
[GitHub Pages] Add option to treat commits as merges from $TRAVIS_COMMIT

### ISSUE THREAD

**Issue by xsanda** [travis-ci/dpl#852]
When deploying to GitHub Pages, there is usually a lot of overlap between the source content (the code in `$TRAVIS_COMMIT`) and the target branch. The source commit is as much a parent of the result as existing head of the target branch is. There should be the option (`keep-parent`?) to make the source commit a parent of the deployment commit, i.e. make the deployment commit a merge from the source branch into the target branch, if `keep-history` is enabled, or a new branch off the source commit if `keep-history` is disabled. (Note that merging into a newly-created orphan without any commits has the same result as creating a new branch, so it makes no difference to the `github_pull_or_commit` logic).

This could be implemented by calling `github_merge if @keep_parent` directly after this: https://github.com/travis-ci/dpl/blob/4d914880dfb191f60f4a99973eef9010709dd525/lib/dpl/provider/pages.rb#L196

where `github_merge` could be implemented as:

```ruby
def github_merge
  source_branch = context.env['TRAVIS_BRANCH']
  source_commit = context.env['TRAVIS_COMMIT']
  print_step "Merging source commit into #{@target_branch}"
  unless context.shell "git remote set-branches --add origin #{source_branch} && git fetch -q --depth 1 origin #{source_branch}" and context.shell "git merge --no-ff --no-commit -q --allow-unrelated-histories #{source_commit} > /dev/null"
    raise 'Could not merge source commit: it likely isn\'t the most recent commit in its branch.'
  end
end
```

This relies on the remote `origin` having been set, so `git remote add origin '#{gh_remote_url}'` needs to be added to `github_init`. (This means the url does not need to be specified in git push, and can be replaced with `origin`.)

This implementation of `github_merge` requires the commit to be the newest in its branch for it to merge into the target branch, because GitHub doesn't support fetching arbitrary historical commits. Alternatively, we could
- fetch the full history of the branch (could be expensive in space and time); or
- continue with the commit, without having merged, if the merge fails.

However, if the commit in question is no longer the top of its branch, then it probably should not be deployed, for fear of a race condition in which two consecutive commits are pushed in short succession, and the second one deploys faster than the first one does. There is still the risk of this race condition if the second commit is pushed, built and deployed in the time the first commit is deploying, but this is not a new problem: such a race condition could just as easily occur in the current setup. Perhaps a failure to merge should not be treated as an error at all, simply a log entry stating that the deployment was not performed because source commit was not the latest commit in its branch.

I've not considered pull-request builds yet: does GitHub Pages deployment ever occur on these?

**Comment by webknjaz** [comment]
Hey @xsanda, pages website is more or less a build artifact and I don't really see a need to bind it on the level of git tree.
Also, consider that this provider allows users to publish to _other_ repos as well as `dpl` tool itself can be used outside of Travis CI as a standalone deployer script. Which means that there might be even no original source deployed to GitHub.
