### ISSUE TITLE
Deploying to pypi is broken due to missing twine

### ISSUE THREAD

**Issue by ngoldbaum** [travis-ci/dpl#853]
Take a look at this job:

https://travis-ci.org/yt-project/unyt/jobs/415529207

It's failing with the following error message:

```
pyenv: twine: command not found
The `twine' command exists in these Python versions:
  2.7.15
```

However earlier in the "installing deploy dependencies" step, it looks like twine is getting installed, so there must be some mismatch between python installations. Is this something I'm doing wrong on my end that I could fix, maybe related to my using `pyenv` to install a bunch of python versions for my test suite? Maybe `dpl` could be smarter about explicitly using a python installation managed by travis?

**Comment by xsanda** [comment]
Could this be related? https://github.com/travis-ci/dpl/issues/779#issuecomment-403548804

**Comment by ngoldbaum** [comment]
It certainly might be I don't see any warnings about permissions issues though and the pre-deployment step reports that twine was successfully installed, so maybe not.

I guess the subsequent comment would be a good workaround. However it seems like this could be fixed in `dpl` as well without needing to re-implement deploying to pypi in my `.travis.yml`.
