### ISSUE TITLE
S3 docs mention non-existing 'endpoint' option

### ISSUE THREAD

**Issue by ulope** [travis-ci/dpl#865]
The [S3 deployment docs](
https://docs.travis-ci.com/user/deployment/s3#using-s3-compatible-object-storage) state that an `endpoint` parameter is supported to use other S3 compatible object stores.

However this option isn't actually supported. There is no mention of `endpoint` in [the current master of s3.rb](https://github.com/travis-ci/dpl/blob/7d058fcf67f4aa2a9428a7783344cea179cb099f/lib/dpl/provider/s3.rb).

Related: https://github.com/travis-ci/travis-ci/issues/9819

**Comment by BanzaiMan** [comment]
Looks like I forgot about https://github.com/travis-ci/dpl/pull/712 before updating the docs.

**Comment by ulope** [comment]
Please make a new release that includes the fix from #712. 
With #712 merged and the accompanying deletion of the `ha-s3-endpoint` branch it's again become impossible for us to upload to DigitalOcean spaces.

Setting `edge: true` in the `s3` provider section has no effect.

**Comment by BanzaiMan** [comment]
1.10.1 has it.
