### ISSUE TITLE
Deployment in Bintray upload files in different pathes for 1 pattern

### ISSUE THREAD

**Issue by mypsycho** [travis-ci/dpl#868]
Hi @eyalbe4,

Using bintray deployment, I want to deploy several files in 1 build and the outcomes are weird.
I setted 1 upload rule: 
```json
{ 
"includePattern" : "releng/update-site/target/(repository/.*)", 
"uploadPattern" : "0.1.nightly/$1",
 "matrixParams": { "override": 1 } 
}
```
and my job produces this tree folder 
```
repository
|   artifacts.jar
|   artifacts.xml.xz
|   content.jar
|   content.xml.xz
|   p2.index
+---features
|       org.mypsycho.emf.modit.feature_0.1.0.v20180825-2345.jar
\---plugins
        org.mypsycho.emf.modit_0.1.0.v20180825-2345.jar
```
but uploaded files have this layout

```
+---0.1.nightly
|   \---repository
|       +---features
|       |       org.mypsycho.emf.modit.feature_0.1.0.v20180825-2345.jar
|       |
|       \---plugins
|               org.mypsycho.emf.modit_0.1.0.v20180825-2345.jar
|
\---Mod-it   // package name
    \---0.1.nightly   // version name
        \---0.1.nightly   // pattern path
            \---repository
                    artifacts.jar
                    artifacts.xml.xz
                    content.jar
                    content.xml.xz
                    p2.index
```
Some files have a path prefixed by the package and version names and others don't.
The build is here :
https://travis-ci.org/mypsycho/ModIt/builds/423427501

As my configuration is very basic, I don't see what is wrong.

Original issue was:
https://github.com/travis-ci/travis-ci/issues/10071#issuecomment-421467799

Thanks for your answer.

BR

**Comment by PhilMFischer** [comment]
I have exactly the same issue here at https://github.com/DLR-SC/Maven-Tycho-Demo .

Are there any news to it?

**Comment by mypsycho** [comment]
Hi @PhilMFischer,

unfortunately, i am working on a refactor in my project.
So I didnt test this part recently.

But i am glad it's a bug and not a misuse.

**Comment by mypsycho** [comment]
Hello @PhilMFischer,
I don't know if you are still interested in deploying on a P2 repository on bintray.

As I tried using bintray API, it occurs to me that the issue is on bintray side, not travis integration.
I split list of uploaded file in 2 patterns (root and sub-levels).

```
    "files": [
        {
	        "includePattern" : "releng/update-site/target/repository/([^/]+)", 
	        "uploadPattern" : "$1", 
	        "matrixParams": { "override": 1 } 
        },
        {
	        "includePattern" : "releng/update-site/target/repository/([^/]+)/(.+)", 
	        "uploadPattern" : "p2/${mvn.build.majorVersion}.${mvn.build.minorVersion}.nightly/$1/$2", 
	        "matrixParams": { "override": 1 } 
        }
 	],
```

See if you want the result at https://github.com/mypsycho/ModIt/blob/master/releng/publish/bintray.json

Note this is not the file actually used by Travis but a template Maven updates.

BR.
