### ISSUE TITLE
Add option to allow gh_pages deploys to merge new and existing content

### ISSUE THREAD

**Issue by georgegillams** [travis-ci/dpl#873]
When creating a gh_pages deploy from Travis, the method used to copy the newly built docs into the repo is an `rsync` command with the `--delete` flag.

https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/pages.rb#L200

So that we can retain historic versions of our build, we would like to be able to configure usage of the `--delete` flag from our `.travis.yml`.

Would it be ok if we open a PR to add this option in? We would implement it as a non-breaking change.

**Comment by dinoio** [comment]
Teach me how to find comand flag
