### ISSUE TITLE
wait_until_deployed triggers rate exceeded sometimes

### ISSUE THREAD

**Issue by kzidane** [travis-ci/dpl#878]
AWS API rate limits are dynamic, so sometimes while waiting for EB deployment to finish for example, the build would fail with this error:

```
Deploying application
2018-09-28 17:39:44 UTC [INFO] Environment update is starting.
2018-09-28 17:39:54 UTC [INFO] Deploying new version to instance(s).
/home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.139/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Rate exceeded (Aws::ElasticBeanstalk::Errors::Throttling)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.139/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.139/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.139/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.139/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.139/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.139/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.139/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-elastic_beanstalk-1.10.2/lib/dpl/provider/elastic_beanstalk.rb:157:in `block in wait_until_deployed'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-elastic_beanstalk-1.10.2/lib/dpl/provider/elastic_beanstalk.rb:156:in `loop'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-elastic_beanstalk-1.10.2/lib/dpl/provider/elastic_beanstalk.rb:156:in `wait_until_deployed'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-elastic_beanstalk-1.10.2/lib/dpl/provider/elastic_beanstalk.rb:54:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.2/lib/dpl/provider.rb:196:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.2/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.2/lib/dpl/provider.rb:196:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.2/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.2/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.2/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

One way to get around is maybe catching this and retrying?

**Comment by BanzaiMan** [comment]
The current behavior is that we check every 5 seconds in a loop _forever_. Your log indicates that the deployment failed after just 2 attempts. The rate limit may be dynamic, but I would be really surprised but it is reached by just 2 tries. Are you using your credentials elsewhere?

We probably should have an upper limit on the number of retries, all the same.

**Comment by BanzaiMan** [comment]
It may be making 2 API calls, which might be excessive. I'll need to look into this more. (The number of API calls does not seem too bad, though, from your logs.)

**Comment by kzidane** [comment]
@BanzaiMan thanks for following up on this! We use credentials for many other repositories but that was the only one being built and deployed at this time. We actually emailed AWS support about this incident first and they recommended exponential backoff but I don't think that's a good solution in this case. Could it be because these are called back to back https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/elastic_beanstalk.rb#L157-L162?

**Comment by dmalan** [comment]
Hi @BanzaiMan, all, just wanted to bump this before the bot closes, as I'm afraid we still run into this issue periodically with EB. Looks like AWS indeed recommends polling with backoff. Cf. https://forums.aws.amazon.com/message.jspa?messageID=366822#jive-message-406788. And afraid our own support tickets with them have recommended the same. 

Thank you!

**Comment by kzidane** [comment]
Hey @BanzaiMan, we just ran into the issue again! Any updates on this? https://travis-ci.com/cs50/lab50/builds/102050639#L588

**Comment by BanzaiMan** [comment]
AWS is complaining about this, so I am not really sure what we can do here. Are you running more than one deployment with this key?

**Comment by kzidane** [comment]
@BanzaiMan per https://github.com/travis-ci/dpl/issues/878#issuecomment-425595049, no. I suppose one thing we could try is catching this error and retrying instead of failing the build?

**Comment by BanzaiMan** [comment]
That is certainly feasible.

**Comment by BanzaiMan** [comment]
Could you try:

```yaml
deploy:
  provider: elastic_beanstalk
  edge:
    branch: eb-retry
  ⋮ # rest
```

If the deployment sees this error (or any that derives from `Aws::Errors::ServiceError`), the error will be logged.

**Comment by kzidane** [comment]
@BanzaiMan it's not deterministic, but I'll change all of our EB `.travis.yml` to use that version of `dpl` and let you know if we run into it again. Thanks so much!!

**Comment by BanzaiMan** [comment]
@kzidane Keep me posted. The erratic nature of this problem is unfortunate, so we'll just have to be patient.

**Comment by MariadeAnton** [comment]
Hi @kzidane  - How's this going? Have the results been more consistent? Thank you!

**Comment by kzidane** [comment]
Yeah, we haven't run into it again and I believe I saw it handling the
error correctly once so all seems good. Thanks!


Kareem

**Comment by MariadeAnton** [comment]
Thanks so much for the swift reply, @kzidane!

@BanzaiMan would it make sense to put this into the next dpl release? Let me know how I can help!

**Comment by BanzaiMan** [comment]
@MariadeAnton Yes, I think so.

**Comment by BanzaiMan** [comment]
The workaround has been merged and released, so the `edge` configuration is no longer necessary.

**Comment by kzidane** [comment]
Thanks a lot!

Kareem
