### ISSUE TITLE
Travis not deploying rubygem

### ISSUE THREAD

**Issue by circa10a** [travis-ci/dpl#908]
Trying to deploy `0.3.0` of my rubygem, but it just seems to skip the `gem push`.

Was able to deploy locally using `gem push` and ensured my api key secret variable was named correctly.

[yml file](https://github.com/circa10a/href-scraper/blob/master/.travis.yml)
[Build log](https://travis-ci.org/circa10a/href-scraper/builds/417623967)

Hopefully I'm just missing something simple?

**Comment by BanzaiMan** [comment]
@circa10a  Please test https://github.com/travis-ci/dpl/pull/926

Thanks.

**Comment by circa10a** [comment]
Bundle seems to be failing now - https://travis-ci.org/circa10a/href-scraper/builds/455803245

Not sure what's causing it, here's my [.travis.yml](https://github.com/circa10a/href-scraper/blob/master/.travis.yml)

**Comment by BanzaiMan** [comment]
https://travis-ci.org/circa10a/href-scraper/builds/455803245#L457-L461 says:

    You are trying to install in deployment mode after changing
    your Gemfile. Run `bundle install` elsewhere and add the
    updated Gemfile.lock to version control.
    
    The gemspecs for path gems changed

Can you follow this advice and try again?

**Comment by circa10a** [comment]
Sorry about that @BanzaiMan , been a while since I've played with gems.
Looks good! - https://rubygems.org/gems/href_scraper
