### ISSUE TITLE
Add zero-downtime deployment capability to CloudFoundry deployments

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/dpl#910]
With some care, it is possible to roll out CF app deployments with zero downtime. We should add such a capability to our deployment provider.

**Comment by TimonLukas** [comment]
I'd love to see this. It's already possible right now by manually installing the CF CLI and installing the `autopilot` plugin, but it would be amazing to be able to use the proper CloudFoundry integration [described here](https://docs.travis-ci.com/user/deployment/cloudfoundry/).

**Comment by abdonrd** [comment]
Any news here?

The new CLI v7 has news about this:
https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html

**Comment by abdonrd** [comment]
As I see here:

https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/cloudfoundry.rb#L28

This line download the CF CLI `v6.52` intead of the new `v7`.

**Comment by abdonrd** [comment]
@BanzaiMan can you reopen this issue? Thanks!

**Comment by abdonrd** [comment]
@BanzaiMan @TimonLukas I just created these two PRs: https://github.com/travis-ci/dpl/pull/1211 & https://github.com/travis-ci/dpl/pull/1210

**Comment by BanzaiMan** [comment]
@abdonrd Could you combine the PRs, so that you can test the desired functionality?
