### ISSUE TITLE
s3: allow setting `force_path_style` option

### ISSUE THREAD

**Issue by vrutkovs** [travis-ci/dpl#921]
Minio is [aws-sdk compatible](https://docs.minio.io/docs/how-to-use-aws-sdk-for-ruby-with-minio-server.html), but requires `force_path_style: true` to be set in `s3_options`. Otherwise it tries to reach `https://bucket.server.com` instead of `https://server.com/bucket`

**Comment by BanzaiMan** [comment]
Interesting. What is the downside of this option? There must be, right, since the default is `false`?

**Comment by vrutkovs** [comment]
This seem to be required for buckets, which don't match domain names. I assume this might be handy for DigitalOcean Spaces, which don't have DNS configured for this bucket.

It seems the default should remain `false` (or even unset), but it would be nice to have an option to override this
