### ISSUE TITLE
Gitlab-ci dpl bluemixcloudfoundry error during deployment 'test' and 'rel' not recognized

### ISSUE THREAD

**Issue by ashok-gawas** [travis-ci/dpl#922]
Hi,

I am facing an issue during deployment of an app on IBM cloud using bluemixcloudfoundry dpl provider. Here are the error details:

`
'test' is not recognized as an internal or external command, operable program or batch file. 
'rel' is not recognized as an internal or external command, operable program or batch file. 
Failed to push app   
Installing deploy dependencies   
Preparing deploy   
Deploying application
Job failed: exit status 1
`

Please help

Note: I am running the pipeline using the runner created on my local windows machine.

**Comment by BanzaiMan** [comment]
Hello, there.

Since this is an issue with GitLab integration, I suggest getting in touch with their support.

Thanks.
