### ISSUE TITLE
Release title not set when travis creates release

### ISSUE THREAD

**Issue by Setheck** [travis-ci/dpl#925]
This may be somewhat related to https://github.com/travis-ci/dpl/issues/425
However, It is more apparent when you have the GitHub slack integration, where the release notification displays
`Release - null`

Seems to me that, setting the tag to the release title might be a sane default? (Thats actually what they do in the docs... https://developer.github.com/v3/repos/releases/#create-a-release )
Octokit already allows for a `:name` option to be passed in, and the following line of dpl could be simply modified to to include `:name => get_tag` or etc.
https://github.com/travis-ci/dpl/blob/80aa7d8d159b4de1437f6104e588f7d6c349fd2e/lib/dpl/provider/releases.rb#L112

Thanks!

**Comment by Setheck** [comment]
I still feel like defaulting name to the tag should be the default...
Thoughts?

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate, then. We can discuss what the default should be in that ticket.
