### ISSUE TITLE
Github deployments are broken when deploying to multiple repositories

### ISSUE THREAD

**Issue by xPaw** [travis-ci/dpl#928]
#923 appears to have broken Github deployments when deploying to multiple repositories

This PR appears to have broken deploying files to other repositories because target_commitish does not exist in the other repository.

It failed like this:
```Setting target_commitish to e53513b0dcace9014bf54b11508cbbbb9263e085
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': PATCH https://api.github.com/repos/thelounge/thelounge/releases/14115585: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: Release
  code: invalid
  field: target_commitish // See: https://developer.github.com/v3/repos/releases/#edit-a-release
```
Build: https://travis-ci.com/thelounge/thelounge-deb/builds/92133900
Config: https://github.com/thelounge/thelounge-deb/blob/v3.0.0-rc.5/.travis.yml

It used to work before. It appears to have attached the file correctly on the repo that it threw the error on, but the file is missing on the main repo (second deploy option)

https://github.com/thelounge/thelounge/releases/tag/v3.0.0-rc.5
https://github.com/thelounge/thelounge-deb/releases/tag/v3.0.0-rc.5

**Comment by BanzaiMan** [comment]
We should add a check if the `repo` is the same when supplying `tag_name` and `tag_commitish`.

As for the state of these two releases in question: The second deployment (the one for thelounge/theloung-deb) did not run after the first one added the file, but failed to update the release.

**Comment by BanzaiMan** [comment]
Could you test the potential fix with the following?

```yaml
deploy:
  provider: releases
  edge:
    branch: releases-check-repo
  ⋮ # rest
```

Thanks.

**Comment by xPaw** [comment]
Would I need to re-create the git tag to make a new build with that config?

**Comment by xPaw** [comment]
I just deleted the tag and created it again in `thelounge-deb` repository, and removed the attached file in `thelounge` repo.

Appears to have worked correctly, both repos got the file attached in the release.

Build: https://travis-ci.com/thelounge/thelounge-deb/builds/92185890

**Comment by BanzaiMan** [comment]
@xPaw Thanks for testing. We'll have a release next week. (It's a bit too close to Thanksgiving weekend, so I'd like to not have a release.)

**Comment by astorije** [comment]
@BanzaiMan, we just got the same issue at https://travis-ci.com/thelounge/thelounge/jobs/173300551, was this fix released? Thanks! 🙏
