### ISSUE TITLE
Add AWS_SESSION_TOKEN support in S3 deploy

### ISSUE THREAD

**Issue by angusfz** [travis-ci/dpl#932]
Need  AWS_SESSION_TOKEN support in S3 deploy provider.

**Comment by BanzaiMan** [comment]
Could you elaborate on what you mean by `AWS_SESSION_TOKEN` support?

**Comment by BanzaiMan** [comment]
I think I was less clear than I should have been. I understand *why* you want this support, but want to know more about *how*.

My understanding of the session token is that one has to connect to AWS STS to obtain a temporary session token. How would `dpl` obtain this?

One way would be to get it *outside of* Travis CI/`dpl`, and encrypt it in the repo settings or `.travis.yml`. The obvious restriction here is that the token has to be re-encrypted every so often and CI/CD would be very painful.

Another way would be to have `dpl` contact STS itself but that requires IAM credentials that allows the token generation anyway, which seems to defeat the purpose of the temporary token.

Did I miss something?

**Comment by angusfz** [comment]
@BanzaiMan  At the first, thanks for ur help and you didn't miss anything.
In our case, the IAM credential only has assume role permission for security reason. 
Although this won't help too much, but can gain some more time when credential leaking.
