### ISSUE TITLE
`target_commitish` is changed on already existing releases

### ISSUE THREAD

**Issue by LaurentTreguier** [travis-ci/dpl#934]
Recently, I've noticed that upon deployment with Github releases on an existing release, the `target_commitish` field of that release seems to be automatically changed to the commit of the tag, no matter what it was set to before.
This can be seen as Github tracks the number of commits added to a branch since the the last release using it as `target_commitish`.
From what I looked up (although I don't know Ruby or `dpl`), b4f060c0eec348c185e9099e682f54d11bae3f6e seems to do just that: forcing a `target_commitish` to be in the options at all times before updating a release.

EDIT: if it's of any relevance at all, here is the `.travis.yml` with which I'm encountering the problem: https://github.com/d-language-server/dls/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
> I've noticed that upon deployment with Github releases on an existing release

Could you explain what you are trying to accomplish? GitHub Releases needs a tag, and not passing this option when updating a release causes problems (as explained in the commit message).

**Comment by BanzaiMan** [comment]
Maybe there are circumstances under which the option isn't necessary. See, for example, https://github.com/travis-ci/dpl/pull/928.

**Comment by BanzaiMan** [comment]
> What I'm doing is making new releases directly on Github, and then waiting for the Travis build to upload some assets to this release afterwards.

And was this working before, or are you trying to set up your release process for the first time?

**Comment by LaurentTreguier** [comment]
It was working before, releases' `target_commitish` used to stay the same.

**Comment by LaurentTreguier** [comment]
At some point I tried setting it manually as a workaround in the `deploy` section of my `.travis.yml`, but somehow always got an error of some kind, with not much info regarding what went wrong (example: https://travis-ci.org/d-language-server/dls/jobs/465004445)
This is what my `deploy` section looked when trying to set it:
```yaml
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  target_commitish: $(echo release/$TRAVIS_TAG | sed 's/\.[0-9]*$/.x/g')
  file_glob: true
  file: dls-*.zip
  skip_cleanup: true
```

**Comment by BanzaiMan** [comment]
That sets the target of this release to something like `release/v0.19.x`, but neither a tag nor a commit by that name exists, so you can't update a Releases based on that value.

I am a little confused by this workflow:
> What I'm doing is making new releases directly on Github, and then waiting for the Travis build to upload some assets to this release afterwards.

By "making new releases directly on GitHub," I assume you mean https://github.com/d-language-server/dls/releases/new. How are you creating this release? What values do you provide in each of the text fields when you do? Is it a published release, or a draft? What commit or tag do you assign to the new release?

**Comment by BanzaiMan** [comment]
> neither a tag nor a commit by that name exists,

I lied. I see the branch `release/v0.19.x` now. I don't understand why that is not processable.

**Comment by LaurentTreguier** [comment]
> By "making new releases directly on GitHub," I assume you mean https://github.com/d-language-server/dls/releases/new. How are you creating this release? What values do you provide in each of the text fields when you do? Is it a published release, or a draft? What commit or tag do you assign to the new release?

Yes; this is how I make new releases, using https://github.com/d-language-server/dls/releases/new.
I use a new version for the tag (e.g. `v0.19.3`), set a release branch (e.g. `release/v0.19.x`) for `target_commitish`, that they call "Target", and publish it (not as a draft, and not as a prerelease).

![screenshot_2018-12-10 d-language-server dls](https://user-images.githubusercontent.com/7602755/49756743-fa677180-fcba-11e8-863b-3c62b1aa6bc1.png)

**Comment by BanzaiMan** [comment]
Thanks for the info.

While we look into it in more detail, you can use the older version with the following:

```yaml
deploy:
  provider: releases
  edge:
    branch: v1.10.5
  ⋮ # rest
```

**Comment by LaurentTreguier** [comment]
Thanks! For now I had simply changed the target_commitish afterwards.

**Comment by BanzaiMan** [comment]
Could you point to a build that fails to work? https://travis-ci.org/d-language-server/dls/builds/465007899, for example, builds on the tag `v0.19.2`, for https://github.com/d-language-server/dls/commit/7450df2cf45d4ce4255183f298b9048c15c548d3, which appears to be the correct commit to associate the release [Version 0.19.2](https://github.com/d-language-server/dls/releases/tag/v0.19.2) to. I must have missed something.

**Comment by LaurentTreguier** [comment]
https://travis-ci.org/d-language-server/dls/builds/465007899 should be a good example. It does use the correct commit, the problem is that it forces this commit to be set as `target_commitish` (as it is printed at the end of each build), instead of keeping the it intact.
[Version 0.19.2](https://github.com/d-language-server/dls/releases/tag/v0.19.2) is now using `release/v0.19.x` as `target_commitish` because I corrected it afterwards.

I can create a new dummy release without correcting anything afterwards, to properly reproduce it, if it's of any use

**Comment by LaurentTreguier** [comment]
I looked into this again and found a good enough workaround in another Github repo; putting this in the `before_deploy` section:
```shell
- export TARGET_COMMITISH="$(echo -n release/$TRAVIS_TAG | sed 's/.[0-9]*$/.x/')"
```
and this in `deploy`:
```shell
target_commitish: "$TARGET_COMMITISH"
```
forces `target_commitish` to stay the same upon deployment.
