### ISSUE TITLE
Bitballoon -> Netlify Drop

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/dpl#935]
https://www.netlify.com/blog/2018/08/14/announcing-netlify-drop---the-simplicity-of-bitballoon-with-the-added-power-of-netlify/

I can update the docs without changing the provider? :-( or we can update the entire thing

Thoughts?

**Comment by svenfuchs** [comment]
This will be resolved in `v2` https://github.com/travis-ci/dpl/blob/dpl-2/lib/dpl/providers/netlify.rb

A corresponding PR for our docs is here: https://github.com/travis-ci/docs-travis-ci-com/pull/2440/files

I think we can close this one here. 

Thank you!
