### ISSUE TITLE
Race condition can cause deploys to github to fail

### ISSUE THREAD

**Issue by msullivan** [travis-ci/dpl#937]
In https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/releases.rb#L106-L117, `dpl` checks whether a release exists and then, if it does not, creates the release.

Unfortunately, if the release has been created (by github, or by *another* travis job trying to deploy to the same release), then a *separate* release will be created and a file uploaded to it, but marking it as not a draft will fail, because a release with that name already exists.

This produces tracebacks like:
```
/home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': PATCH https://api.github.com/repos/mypyc/mypy_mypyc-wheels/releases/14527704: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: Release
  code: already_exists
  field: tag_name // See: https://developer.github.com/v3/repos/releases/#edit-a-release
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `patch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:46:in `patch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/client/releases.rb:55:in `update_release'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.6/lib/dpl/provider/releases.rb:154:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```

We get this relatively frequently in a 6 job configuration in which every job attempts to deploy to github releases: https://github.com/mypyc/mypy_mypyc-wheels/blob/75c631e1134f7fc945c98cc7a51a69ac2453b35f/.travis.yml

**Comment by msullivan** [comment]
It has not been fixed

**Comment by BanzaiMan** [comment]
I don't think we can reasonably prevent such race conditions. I suggest using Build stages to ensure that the deployments do not happen simultaneously. (You will still run into problems if you run multiple *builds* at the same time.)

**Comment by msullivan** [comment]
Using build stages to ensure the deployments aren't simultaneous isn't a satisfactory solution, since then the builds won't be parallel anymore.

I think there are some reasonable fixes for this in dpl. The most straightforward of which is deleting the draft release and retrying if the `update_release` fails due to the release already existing. 
There might be other, better approaches (checking for another created release immediately after creating a draft?) that depend more on the intricacies of github's API here.

**Comment by BanzaiMan** [comment]
Great ideas! I've outlined how to make this happen. https://github.com/travis-ci/dpl/blob/master/.github/CONTRIBUTING.md#testing-dpl-in-the-context-of-travis-ci-builds

**Comment by msullivan** [comment]
Still happens

**Comment by tcaduser** [comment]
This still happens
