### ISSUE TITLE
Allow to configure EBS deployment to automatically track new files created within the job

### ISSUE THREAD

**Issue by iriberri** [travis-ci/dpl#939]
Related: https://github.com/travis-ci/travis-ci/issues/9716

Right now, unless the `zip_file` option is used for the EBS deployment:

> a zip file will be created from all the files that are part of the repository under test (determined with `git ls-files`).

What happens with this is that if one is generating assets/something that they want to push to EBS as well, together with the rest of the repository, they'd need to run workarounds such as:

```yaml
before_deploy:
- git add --force {other target files here}
```

to add their newly created files to the repo.

It sounds like we could make this easier by adding an option to the deployment provider itself. I think this one should be closely related with the existing `skip_cleanup` option.

I don't know if it would make sense to expand the current behavior, so that the combination `zip_file not specified` + `skip_cleanup: true` would run internally a `git add --force` and add everything to EBS. This change in behavior could break builds, though. 💥

**Comment by iriberri** [comment]
@BanzaiMan no rush at all, but what do you think about this? I'd like to get some data on the current usage of this deployment provider (how folks are using `skip_cleanup` and the `zip_file` options) to better understand our possibilities and see if what I suggest above would break everything or not. I guess I'll only get to do this next year, though :)

**Comment by BanzaiMan** [comment]
Could it be more effectively addressed by https://github.com/travis-ci/dpl/issues/411? I wrote https://github.com/travis-ci/dpl/pull/885, but apparently it is not yet ready for merge.

**Comment by iriberri** [comment]
Ooooooooh - I had no idea about that. Will investigate that approach further :)

**Comment by BanzaiMan** [comment]
To clarify: The PR does attempt to take `.ebignore` file into account when creating the ZIP archive, but it does not quite work, according to the one report we've got so far.

**Comment by dylandechant** [comment]
this issue stems from here: https://github.com/travis-ci/travis-ci/issues/8385

our org is actively tracking this, @BanzaiMan if you need help testing please let me know :)

**Comment by BanzaiMan** [comment]
@dylandechant The PR I mentioned above attempts to solve the problem why making use of `.ebignore` file; namely, by running `git ls-files --exclude-from=.ebignore -z` to find the list of files to be included in the files. There is at least one user reporting (https://github.com/travis-ci/dpl/issues/411#issuecomment-445052848) that it is not sufficient. If you would like to test the PR, procedure is explained in https://github.com/travis-ci/dpl/pull/885#issuecomment-433135271.
