### ISSUE TITLE
AWS Lambda provider incorrectly parses base64 encoded environment_variables

### ISSUE THREAD

**Issue by nonword** [travis-ci/dpl#942]
AWS Lambda provider incorrectly parses base64 encoded environment_variables. Base64 encoded values frequently end in '='. Thus, it's [usually] not possible to configure an `environment_variable` whose value is base64 encoded.

This is happening because environmental variables [are parsed](https://github.com/travis-ci/dpl/blob/4899110679bfaa6b45040b8f7325df1b9c75a9cf/lib/dpl/provider/lambda.rb#L183) using [split_string_array_to_hash](https://github.com/travis-ci/dpl/blob/4899110679bfaa6b45040b8f7325df1b9c75a9cf/lib/dpl/provider/lambda.rb#L226-L233), which splits on '=' without specifying a `limit`, using the first token as key and the second as value.

For example, consider the following:

```
...
 - provider: lambda
   environment_variables:
    - "VAR_NAME=ZGVjb2RlZC12YWx1ZQo="
```

The above deploys the lambda with "VAR_NAME" set to "ZGVjb2RlZC12YWx1ZQo"

Given that the split is being performed specifically to build a key-value hash (i.e. only two tokens ever expected), a good fix may be to use the [`limit` param to split](https://apidock.com/ruby/String/split) as follows:

```
  keyval = val.split(delimiter, 2)
```

That should allow us to use base64 encoded `environmental_variable` values without effecting others.

Thanks

**Comment by BanzaiMan** [comment]
Nice catch! Do you mind opening a PR?
