### ISSUE TITLE
Add `retry_limit` configurable option to `provider: elasticbeanstalk`

### ISSUE THREAD

**Issue by cotsog** [travis-ci/dpl#973]
Some customers can run into API rate limitation when deploying to ElasticBeanstalk on Travis CI.

Fortunately, there's a `retry_limit` option that you can pass to the constructor of the ElasticBeanstalk client:

> :retry_limit (Integer) — default: 3 — The maximum number of times to retry failed requests. Only ~ 500 level server errors and certain ~ 400 level client errors are retried. Generally, these are throttling errors, data checksum errors, networking errors, timeout errors and auth errors from expired credentials.

See https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ElasticBeanstalk/Client.html.

It has been tested in a "hardcoded" fashion in this branch: https://github.com/travis-ci/dpl/blob/3c657c167302c720f43631d430e3a626b19ec095/lib/dpl/provider/elastic_beanstalk.rb#L97.

We should expose this setting in the .travis.yml file and modify the code accordingly.

**Comment by cotsog** [comment]
Might help with https://github.com/travis-ci/dpl/issues/878 too.

**Comment by iriberri** [comment]
Relevant PR here, related to issue #878 https://github.com/travis-ci/dpl/pull/972

**Comment by cotsog** [comment]
Thanks for the feedback. That sounds good to me. I'll close this on then.
