### ISSUE TITLE
elasticbeanstalk deployment with wait_until_deployed succeeds too soon

### ISSUE THREAD

**Issue by kzidane** [travis-ci/dpl#985]
https://travis-ci.com/cs50/mailman-eb/jobs/192588278#L485 once "Too many failures" is encountered the build seems to succeed immediately before the deployment actually succeeds.

**Comment by kzidane** [comment]
Hey @BanzaiMan! Was just wondering if you got a chance to look at this one?

**Comment by svenfuchs** [comment]
@kzidane does this issue still exist? i'm failing to find that repository ...

**Comment by kzidane** [comment]
@svenfuchs ah sorry, we renamed the repo a while ago. Here https://travis-ci.com/cs50/mailman/jobs/192588278#L483!

**Comment by cloudhary** [comment]
I'm facing a similar issue. My Beanstalk deployments take a longer time than the one that is allocated in the the current deploy code: https://github.com/travis-ci/dpl/blame/f21be87991a3007480a26f3df2bbecd7fddea153/lib/dpl/providers/elasticbeanstalk.rb#L115-L123

@svenfuchs would you be willing to make the timeout longer, or allow for the user to specify a longer timeout before calling "Too many failures"?

**Comment by cloudhary** [comment]
I'd be happy to make a PR to address this. We're currently debating using `eb-cli` instead in order to make our deploys wait for a success or failure from beanstalk. Fixing this by allowing user to specify timeout and using your existing codebase would be a far superior option than our own, handrolled eb-cli in the travis config. Let me know!

**Comment by svenfuchs** [comment]
@cloudhary absolutely, i'd be happy to accept your PR for this. thanks in advance!

**Comment by svenfuchs** [comment]
should be fixed in https://github.com/travis-ci/dpl/pull/1133

**Comment by kzidane** [comment]
@svenfuchs fyi I'm afraid this still seems to be an issue:
https://travis-ci.com/cs50/cs50.me/builds/136826707
https://travis-ci.com/cs50/cs50.me/builds/136827034
