### ISSUE TITLE
Deploy to github pages from pull requests

### ISSUE THREAD

**Issue by okalachev** [travis-ci/dpl#991]
It would be really nice to make pull request builds available to preview. I believe, it's not so difficult to implement.

One way is to add `target_dir` parameter to the provider to specify the directory in the target repo to be sync (other directories are left untouched). This parameter may be calculated in `before_deploy` stage. So PRs previews might be available from URL like:

```https://address.to.main.site/__pr_12345/```

Another repo with another domain can be used for PRs also (modifying the `repo` parameter).

I think such a parameter also can be useful in another situations, when you want to serve the generated site from a subdirectory, for some reason.

**Comment by BanzaiMan** [comment]
No deployments occur on PR builds for security reasons. https://docs.travis-ci.com/user/deployment/#pull-requests

**Comment by okalachev** [comment]
@BanzaiMan, and what about switching the target directory for files (based on the branch name), for making alpha/beta/feature previews? Not from PRs?

**Comment by forkbabu** [comment]
@BanzaiMan @okalachev is there a way to do this for jekyll websites hosted on github pages?
