### ISSUE TITLE
[provider: pypi] Add check_app phase for PyPI provider

### ISSUE THREAD

**Issue by di** [travis-ci/dpl#994]
Currently there is nothing done in the `check_app` phase for the PyPI provider.

This could use [`twine check`](https://twine.readthedocs.io/en/latest/#twine-check) to determine if the distributions are valid before attempting to upload.

It should be noted that this feature is only available in `twine>=1.12.0`.

**Comment by svenfuchs** [comment]
@di i have added `twine check` to the `pypi` provider as well as an option to opt out in this PR: https://github.com/travis-ci/dpl/pull/1063

Would you be able to give this a try?

I am going to close this issue here, let's continue the conversation on the PR.
