### ISSUE TITLE
Failed to deploy to Github releases 

### ISSUE THREAD

**Issue by Balachandarsmr** [travis-ci/dpl#999]
![Screenshot_2019-06-03-05-57-54](https://user-images.githubusercontent.com/29444683/58769525-85b82480-85c5-11e9-9686-ee4148d69333.jpg)
![Screenshot_2019-06-03-05-58-18](https://user-images.githubusercontent.com/29444683/58769530-8d77c900-85c5-11e9-8d8e-e2f77229fd71.jpg)
![Screenshot_2019-06-03-05-58-49](https://user-images.githubusercontent.com/29444683/58769533-94064080-85c5-11e9-9f9d-f2981fc6cabf.jpg)
![Screenshot_2019-06-03-05-58-59](https://user-images.githubusercontent.com/29444683/58769537-99638b00-85c5-11e9-82ed-0904b947887f.jpg)

**Comment by Balachandarsmr** [comment]
ERROR:  Error installing dpl-releases:
	The last version of public_suffix (>= 2.0.2, < 4.0) to support your Ruby & RubyGems was 3.0.3. Try installing it with `gem install public_suffix -v 3.0.3` and then running the current command again
	public_suffix requires Ruby version >= 2.3. The current ruby version is 2.2.0.

Please fix this

**Comment by BanzaiMan** [comment]
Where can I see the entire build log?

**Comment by Balachandarsmr** [comment]
This is entire build log
https://api.travis-ci.org/v3/job/540526061/log.txt

**Comment by BanzaiMan** [comment]
1.10.11 resolves this issue. Please restart the affected builds.
